(function () {
  const appData = window.INDONESIAN_FLASHCARD_DATA;
  if (!appData || !Array.isArray(appData.words)) {
    return;
  }

  const targetAdditional = 576;
  const startNumber = 25;
  const usedWords = new Set(appData.words.map((word) => word.word.toLowerCase()));

  const transitiveVerbs = [
    ["membayar", "支払う", "to pay", "tagihan", "請求書"],
    ["menerima", "受け取る", "to receive", "surat", "手紙"],
    ["mengirim", "送る", "to send", "paket", "荷物"],
    ["mengambil", "取る、受け取る", "to take; pick up", "uang", "お金"],
    ["menaruh", "置く", "to put", "kunci", "鍵"],
    ["memakai", "使う、身につける", "to use; wear", "sepatu", "靴"],
    ["menggunakan", "使用する", "to use", "komputer", "コンピューター"],
    ["mencoba", "試す", "to try", "baju", "服"],
    ["menjual", "売る", "to sell", "makanan", "食べ物"],
    ["menyewa", "借りる", "to rent", "kamar", "部屋"],
    ["memesan", "予約する、注文する", "to reserve; order", "tiket", "チケット"],
    ["menukar", "交換する、両替する", "to exchange", "uang", "お金"],
    ["memberi", "与える", "to give", "hadiah", "プレゼント"],
    ["mengajar", "教える", "to teach", "bahasa Indonesia", "インドネシア語"],
    ["mempelajari", "学ぶ", "to study; learn", "tata bahasa", "文法"],
    ["menonton", "見る、鑑賞する", "to watch", "film", "映画"],
    ["mendengarkan", "聞く", "to listen to", "lagu", "歌"],
    ["menelepon", "電話する", "to call", "dokter", "医者"],
    ["menghubungi", "連絡する", "to contact", "kantor", "会社"],
    ["mengundang", "招待する", "to invite", "teman", "友だち"],
    ["mengunjungi", "訪問する", "to visit", "museum", "博物館"],
    ["membantu", "手伝う、助ける", "to help", "ibu", "母"],
    ["membersihkan", "掃除する、きれいにする", "to clean", "kamar", "部屋"],
    ["mencuci", "洗う", "to wash", "pakaian", "服"],
    ["menyapu", "掃く", "to sweep", "lantai", "床"],
    ["mengepel", "モップをかける", "to mop", "lantai", "床"],
    ["menyetrika", "アイロンをかける", "to iron", "baju", "服"],
    ["memperbaiki", "修理する", "to repair", "sepeda", "自転車"],
    ["merusak", "壊す", "to damage", "mesin", "機械"],
    ["menyiapkan", "準備する", "to prepare", "sarapan", "朝食"],
    ["menyimpan", "保管する、貯める", "to keep; save", "uang", "お金"],
    ["membuang", "捨てる", "to throw away", "sampah", "ごみ"],
    ["mengganti", "替える、交換する", "to replace", "pakaian", "服"],
    ["melepas", "脱ぐ、外す", "to take off", "sepatu", "靴"],
    ["menyalakan", "つける", "to turn on", "lampu", "電気"],
    ["mematikan", "消す", "to turn off", "lampu", "電気"],
    ["mengunci", "鍵をかける", "to lock", "pintu", "ドア"],
    ["memotong", "切る", "to cut", "buah", "果物"],
    ["memasukkan", "入れる", "to put in", "buku", "本"],
    ["mengeluarkan", "出す", "to take out", "dompet", "財布"],
    ["menaikkan", "上げる", "to raise", "harga", "値段"],
    ["menurunkan", "下げる", "to lower", "harga", "値段"],
    ["mencatat", "メモする、記録する", "to note down", "alamat", "住所"],
    ["mencetak", "印刷する", "to print", "dokumen", "書類"],
    ["menyalin", "写す、コピーする", "to copy", "kalimat", "文"],
    ["menerjemahkan", "翻訳する", "to translate", "surat", "手紙"],
    ["menjelaskan", "説明する", "to explain", "aturan", "規則"],
    ["mengulang", "繰り返す、復習する", "to repeat", "pelajaran", "授業内容"],
    ["melanjutkan", "続ける", "to continue", "pekerjaan", "仕事"],
    ["menghentikan", "止める", "to stop", "mobil", "車"],
    ["memulai", "始める", "to start", "rapat", "会議"],
    ["menyelesaikan", "終える、完成させる", "to finish", "tugas", "課題"],
    ["mengerjakan", "取り組む、する", "to do; work on", "PR", "宿題"],
    ["mengumpulkan", "集める、提出する", "to collect; submit", "formulir", "用紙"],
    ["memeriksa", "確認する、検査する", "to check", "paspor", "パスポート"],
    ["mengukur", "測る", "to measure", "suhu", "温度"],
    ["menghitung", "数える、計算する", "to count", "uang", "お金"],
    ["menimbang", "量る", "to weigh", "barang", "品物"],
    ["menekan", "押す", "to press", "tombol", "ボタン"],
    ["menarik", "引く", "to pull", "pintu", "ドア"],
    ["mendorong", "押す", "to push", "kursi", "椅子"],
    ["mengangkat", "持ち上げる", "to lift", "koper", "スーツケース"],
    ["meletakkan", "置く", "to place", "gelas", "コップ"],
    ["mengembalikan", "返す", "to return", "buku", "本"],
    ["meminjam", "借りる", "to borrow", "payung", "傘"],
    ["meminjamkan", "貸す", "to lend", "buku", "本"],
    ["menyukai", "好む", "to like", "musik", "音楽"],
    ["mengenal", "知っている、知り合う", "to know; be acquainted", "tetangga", "近所の人"],
    ["memperkenalkan", "紹介する", "to introduce", "diri", "自分"],
    ["memotret", "写真を撮る", "to photograph", "pemandangan", "景色"],
    ["merekam", "録音する、録画する", "to record", "suara", "音"],
    ["menggambar", "描く", "to draw", "peta", "地図"],
    ["mewarnai", "色を塗る", "to color", "gambar", "絵"],
    ["menghafal", "暗記する", "to memorize", "kata", "単語"],
    ["mengingat", "覚えている、思い出す", "to remember", "janji", "約束"],
    ["melupakan", "忘れる", "to forget", "nama", "名前"],
    ["menanyakan", "尋ねる", "to ask about", "harga", "値段"],
    ["menyebut", "述べる、呼ぶ", "to mention; call", "nama", "名前"],
    ["menunjukkan", "示す、見せる", "to show", "jalan", "道"],
    ["menunjuk", "指す", "to point at", "gambar", "絵"],
    ["mengikuti", "参加する、従う", "to join; follow", "kelas", "授業"],
    ["menyeberangi", "横断する", "to cross", "jalan", "道"],
    ["mengantre", "列に並ぶ", "to queue for", "tiket", "チケット"],
    ["menjemput", "迎えに行く", "to pick up", "anak", "子ども"],
    ["mengantar", "送って行く", "to take; escort", "tamu", "客"],
    ["mendapatkan", "得る、手に入れる", "to get", "pekerjaan", "仕事"],
    ["menemukan", "見つける", "to find", "dompet", "財布"],
    ["kehilangan", "なくす、失う", "to lose", "kunci", "鍵"],
    ["mengadakan", "開催する", "to hold", "rapat", "会議"],
    ["menghadiri", "出席する", "to attend", "pesta", "パーティー"],
    ["menyampaikan", "伝える", "to convey", "pesan", "伝言"],
    ["menolak", "断る、拒否する", "to refuse", "ajakan", "誘い"],
    ["menyetujui", "同意する", "to agree to", "rencana", "計画"],
    ["merencanakan", "計画する", "to plan", "perjalanan", "旅行"],
    ["mengatur", "整える、調整する", "to arrange", "jadwal", "予定"],
    ["mengurus", "手続きする、世話する", "to handle", "visa", "ビザ"],
    ["menandatangani", "署名する", "to sign", "formulir", "用紙"],
    ["memfotokopi", "コピーする", "to photocopy", "paspor", "パスポート"],
    ["melampirkan", "添付する", "to attach", "foto", "写真"],
    ["menjaga", "守る、世話する", "to guard; care for", "kesehatan", "健康"],
    ["merawat", "世話する、看病する", "to take care of", "anak", "子ども"],
    ["mengobati", "治療する", "to treat", "pasien", "患者"],
    ["menawar", "値切る", "to bargain", "harga", "値段"],
    ["membungkus", "包む", "to wrap", "hadiah", "プレゼント"],
    ["menghias", "飾る", "to decorate", "kamar", "部屋"],
    ["mencicipi", "味見する", "to taste", "makanan", "食べ物"],
    ["menggoreng", "揚げる、炒める", "to fry", "ikan", "魚"],
    ["merebus", "ゆでる、煮る", "to boil", "telur", "卵"],
    ["memanggang", "焼く", "to grill; bake", "roti", "パン"],
    ["menuang", "注ぐ", "to pour", "air", "水"],
    ["mencampur", "混ぜる", "to mix", "gula", "砂糖"],
    ["mengaduk", "かき混ぜる", "to stir", "kopi", "コーヒー"],
    ["mengupas", "皮をむく", "to peel", "mangga", "マンゴー"],
    ["menyikat", "磨く", "to brush", "gigi", "歯"],
    ["melayani", "接客する、対応する", "to serve", "pelanggan", "客"],
    ["memanggil", "呼ぶ", "to call", "taksi", "タクシー"],
    ["mengejar", "追いかける", "to chase", "bus", "バス"],
    ["menyusul", "後から追いつく", "to catch up with", "teman", "友だち"],
    ["memarkir", "駐車する", "to park", "mobil", "車"],
    ["menyetir", "運転する", "to drive", "mobil", "車"],
    ["memperpanjang", "延長する", "to extend", "paspor", "パスポート"],
    ["memperpendek", "短くする", "to shorten", "tali", "ひも"],
    ["memperbesar", "大きくする", "to enlarge", "gambar", "画像"],
    ["memperkecil", "小さくする", "to reduce", "ukuran", "サイズ"],
    ["mempercepat", "速める", "to speed up", "proses", "過程"],
    ["memperlambat", "遅くする", "to slow down", "suara", "音"],
    ["mengurangi", "減らす", "to reduce", "gula", "砂糖"],
    ["menambah", "加える、増やす", "to add", "garam", "塩"],
    ["memenuhi", "満たす", "to fulfill", "syarat", "条件"],
    ["membutuhkan", "必要とする", "to need", "bantuan", "助け"],
    ["mengusulkan", "提案する", "to propose", "ide", "考え"],
    ["membatalkan", "取り消す", "to cancel", "pesanan", "予約"],
    ["menentukan", "決める", "to decide", "tanggal", "日付"],
    ["mengubah", "変える", "to change", "jadwal", "予定"],
    ["menyusun", "並べる、作成する", "to arrange", "rencana", "計画"],
    ["membandingkan", "比較する", "to compare", "harga", "値段"],
    ["memperhatikan", "注意する", "to pay attention to", "penjelasan", "説明"],
    ["mengerti", "理解する", "to understand", "arti kata", "単語の意味"],
    ["memahami", "理解する", "to understand", "kalimat", "文"],
    ["meminta maaf", "謝る", "to apologize", "kesalahan", "間違い"],
    ["mengucapkan", "述べる、言う", "to say; utter", "terima kasih", "ありがとう"],
    ["mengajak", "誘う", "to invite", "teman", "友だち"],
    ["menikmati", "楽しむ、味わう", "to enjoy", "liburan", "休暇"],
    ["menghemat", "節約する", "to save", "uang", "お金"],
    ["menghabiskan", "使い切る、過ごす", "to spend", "waktu", "時間"],
    ["menyewa", "借りる", "to rent", "sepeda", "自転車"],
    ["menitipkan", "預ける", "to leave in someone's care", "tas", "かばん"],
    ["mengambilkan", "取ってあげる", "to get for someone", "air", "水"],
    ["membawakan", "持ってきてあげる", "to bring for someone", "payung", "傘"],
    ["menyalakan ulang", "再起動する", "to restart", "komputer", "コンピューター"],
    ["memindahkan", "移動させる", "to move", "meja", "机"],
    ["mendekati", "近づく", "to approach", "pintu", "ドア"],
    ["menjauhi", "遠ざかる、避ける", "to avoid; keep away from", "bahaya", "危険"],
    ["mencari tahu", "調べる", "to find out", "informasi", "情報"]
  ];

  const intransitiveVerbs = [
    ["berjalan", "歩く", "to walk", "di taman", "公園で"],
    ["berlari", "走る", "to run", "di lapangan", "広場で"],
    ["berhenti", "止まる", "to stop", "di halte", "停留所で"],
    ["berangkat", "出発する", "to depart", "ke kantor", "会社へ"],
    ["tiba", "到着する", "to arrive", "di stasiun", "駅に"],
    ["kembali", "戻る", "to return", "ke rumah", "家へ"],
    ["naik", "乗る、上がる", "to ride; go up", "bus", "バスに"],
    ["turun", "降りる、下がる", "to get off; go down", "dari kereta", "電車から"],
    ["lewat", "通る", "to pass by", "jalan ini", "この道を"],
    ["belok", "曲がる", "to turn", "ke kanan", "右へ"],
    ["bermain", "遊ぶ", "to play", "di luar", "外で"],
    ["beristirahat", "休む", "to rest", "di kamar", "部屋で"],
    ["berolahraga", "運動する", "to exercise", "setiap pagi", "毎朝"],
    ["berbelanja", "買い物をする", "to shop", "di pasar", "市場で"],
    ["berlibur", "休暇を過ごす", "to go on holiday", "di Bali", "バリで"],
    ["bepergian", "出かける、旅行する", "to travel", "dengan keluarga", "家族と"],
    ["bekerja sama", "協力する", "to cooperate", "dengan teman", "友だちと"],
    ["berdoa", "祈る", "to pray", "di masjid", "モスクで"],
    ["bersekolah", "学校に通う", "to attend school", "di Jakarta", "ジャカルタで"],
    ["bertemu", "会う", "to meet", "dengan guru", "先生と"],
    ["bertanya", "質問する", "to ask", "kepada petugas", "係員に"],
    ["tersenyum", "ほほえむ", "to smile", "kepada tamu", "客に"],
    ["tertawa", "笑う", "to laugh", "bersama teman", "友だちと"],
    ["menangis", "泣く", "to cry", "karena sedih", "悲しくて"],
    ["sembuh", "治る", "to recover", "dari sakit", "病気から"],
    ["lahir", "生まれる", "to be born", "di Surabaya", "スラバヤで"],
    ["meninggal", "亡くなる", "to pass away", "tahun lalu", "去年"],
    ["pindah", "引っ越す、移る", "to move", "ke kota lain", "別の町へ"],
    ["menikah", "結婚する", "to marry", "bulan depan", "来月"],
    ["bercerai", "離婚する", "to divorce", "tahun ini", "今年"],
    ["bertamu", "客として訪ねる", "to visit as a guest", "ke rumah teman", "友人の家へ"],
    ["menginap", "泊まる", "to stay overnight", "di hotel", "ホテルに"],
    ["berubah", "変わる", "to change", "sedikit", "少し"],
    ["bertambah", "増える", "to increase", "setiap hari", "毎日"],
    ["membaik", "良くなる", "to improve", "pelan-pelan", "少しずつ"],
    ["memburuk", "悪くなる", "to get worse", "karena hujan", "雨のため"],
    ["berhasil", "成功する", "to succeed", "dalam ujian", "試験で"],
    ["gagal", "失敗する", "to fail", "sekali", "一度"],
    ["berkumpul", "集まる", "to gather", "di aula", "ホールに"],
    ["berpisah", "別れる", "to separate", "di stasiun", "駅で"],
    ["berlatih", "練習する", "to practice", "setiap hari", "毎日"],
    ["bernyanyi", "歌う", "to sing", "di kelas", "教室で"],
    ["menari", "踊る", "to dance", "di pesta", "パーティーで"],
    ["bersepeda", "自転車に乗る", "to ride a bicycle", "ke sekolah", "学校へ"],
    ["berlayar", "船で行く", "to sail", "ke pulau", "島へ"],
    ["terbang", "飛ぶ", "to fly", "ke Jakarta", "ジャカルタへ"],
    ["mengalir", "流れる", "to flow", "ke laut", "海へ"],
    ["berbunyi", "鳴る", "to sound", "keras", "大きく"],
    ["menyala", "点く", "to be on", "di malam hari", "夜に"],
    ["padam", "消える", "to go out", "tiba-tiba", "突然"],
    ["terbuka", "開いている", "to be open", "sejak pagi", "朝から"],
    ["tertutup", "閉まっている", "to be closed", "hari ini", "今日"],
    ["terlambat", "遅れる", "to be late", "ke sekolah", "学校に"],
    ["tertidur", "眠ってしまう", "to fall asleep", "di bus", "バスで"],
    ["terjatuh", "転ぶ、落ちる", "to fall", "di jalan", "道で"],
    ["tersesat", "道に迷う", "to get lost", "di kota", "町で"],
    ["terkejut", "驚く", "to be surprised", "karena suara", "音に"],
    ["terbakar", "燃える、焼ける", "to burn", "di dapur", "台所で"],
    ["terluka", "けがをする", "to be injured", "di kaki", "足を"],
    ["berjanji", "約束する", "to promise", "kepada teman", "友だちに"],
    ["berpikir", "考える", "to think", "tentang rencana", "計画について"],
    ["berharap", "期待する、望む", "to hope", "agar lulus", "合格するように"],
    ["berminat", "興味がある", "to be interested", "pada musik", "音楽に"],
    ["tertarik", "興味を持つ", "to be interested", "pada budaya", "文化に"],
    ["percaya", "信じる", "to believe", "kepada teman", "友だちを"],
    ["ragu", "迷う、疑う", "to doubt", "sedikit", "少し"],
    ["setuju", "賛成する", "to agree", "dengan ide itu", "その考えに"],
    ["menyerah", "あきらめる", "to give up", "sekarang", "今"],
    ["berkurban", "犠牲を払う", "to sacrifice", "untuk keluarga", "家族のために"],
    ["berkebun", "庭仕事をする", "to garden", "di halaman", "庭で"],
    ["berkemah", "キャンプする", "to camp", "di gunung", "山で"],
    ["berfoto", "写真を撮る", "to take a photo", "di pantai", "海岸で"],
    ["berenang-renang", "泳ぎ回る", "to swim around", "di kolam", "プールで"]
  ];

  const nouns = [
    ["alamat", "住所", "address"], ["desa wisata", "観光村", "tourist village"], ["nomor", "番号", "number"],
    ["nomor telepon", "電話番号", "telephone number"], ["email", "メール", "email"], ["surat", "手紙", "letter"],
    ["pesan", "伝言、メッセージ", "message"], ["paket", "荷物、小包", "package"], ["kartu", "カード", "card"],
    ["kartu nama", "名刺", "business card"], ["kartu identitas", "身分証", "identity card"], ["KTP", "住民身分証", "Indonesian ID card"],
    ["SIM", "運転免許証", "driver's license"], ["visa", "ビザ", "visa"], ["izin", "許可", "permission"],
    ["syarat", "条件", "requirement"], ["tanda tangan", "署名", "signature"], ["foto", "写真", "photo"],
    ["dokumen", "書類", "document"], ["salinan", "コピー、写し", "copy"], ["asli", "原本、本物", "original"],
    ["kopi", "写し、コピー", "copy"], ["daftar", "リスト、名簿", "list"], ["jadwal", "予定、スケジュール", "schedule"],
    ["janji", "約束、予約", "promise; appointment"], ["undangan", "招待状", "invitation"], ["acara", "行事、イベント", "event"],
    ["pesta", "パーティー", "party"], ["rapat", "会議", "meeting"], ["kelas malam", "夜間クラス", "evening class"],
    ["kursus", "講座", "course"], ["ujian", "試験", "exam"], ["nilai", "点数、価値", "score; value"],
    ["jawaban", "答え", "answer"], ["pertanyaan", "質問", "question"], ["latihan", "練習", "practice"],
    ["tugas", "課題、仕事", "task"], ["pelajaran", "授業、学課", "lesson"], ["kamus", "辞書", "dictionary"],
    ["arti", "意味", "meaning"], ["kalimat", "文", "sentence"], ["huruf", "文字", "letter"], ["suara", "声、音", "voice; sound"],
    ["lagu", "歌", "song"], ["musik", "音楽", "music"], ["film", "映画", "movie"], ["berita", "ニュース", "news"],
    ["koran", "新聞", "newspaper"], ["majalah", "雑誌", "magazine"], ["iklan", "広告", "advertisement"],
    ["papan petunjuk", "案内板", "signboard"], ["tanda", "印、標識", "sign; mark"], ["rambu", "標識", "traffic sign"],
    ["lampu lalu lintas", "信号", "traffic light"], ["trotoar", "歩道", "sidewalk"], ["perempatan", "十字路", "intersection"],
    ["pertigaan", "三叉路", "three-way intersection"], ["tikungan", "曲がり角", "bend; turn"], ["arah", "方向", "direction"],
    ["kanan", "右", "right"], ["kiri", "左", "left"], ["utara", "北", "north"], ["selatan", "南", "south"],
    ["timur", "東", "east"], ["barat", "西", "west"], ["pusat kota", "市中心部", "city center"],
    ["pinggir kota", "郊外", "outskirts"], ["daerah", "地域", "area"], ["provinsi", "州、県", "province"],
    ["pulau", "島", "island"], ["danau", "湖", "lake"], ["hutan", "森", "forest"], ["sawah", "田んぼ", "rice field"],
    ["kebun", "畑、庭園", "garden; plantation"], ["lapangan", "広場、グラウンド", "field"], ["kolam", "池、プール", "pond; pool"],
    ["kolam renang", "プール", "swimming pool"], ["gedung", "建物", "building"], ["lantai", "床、階", "floor"],
    ["atap", "屋根", "roof"], ["dinding", "壁", "wall"], ["tangga", "階段", "stairs"], ["lift", "エレベーター", "elevator"],
    ["gudang", "倉庫", "warehouse"], ["ruang tamu", "居間、客間", "living room"], ["ruang makan", "食堂", "dining room"],
    ["kamar mandi", "浴室、トイレ", "bathroom"], ["garasi", "車庫", "garage"], ["kos", "下宿", "boarding room"],
    ["apartemen", "アパート", "apartment"], ["kontrakan", "賃貸住宅", "rental house"], ["sewa", "賃貸、賃料", "rent"],
    ["biaya", "費用", "cost"], ["ongkos", "料金、運賃", "fare; fee"], ["tarif", "料金表、料金", "tariff; rate"],
    ["diskon", "割引", "discount"], ["kembalian", "お釣り", "change"], ["struk", "レシート", "receipt"],
    ["nota", "伝票、領収書", "note; receipt"], ["barang", "品物", "goods"], ["produk", "製品", "product"],
    ["ukuran", "サイズ", "size"], ["berat", "重さ", "weight"], ["panjang", "長さ", "length"], ["lebar", "幅", "width"],
    ["tinggi badan", "身長", "height"], ["bahan", "材料", "material"], ["kualitas", "品質", "quality"], ["merek", "ブランド", "brand"],
    ["pelanggan", "客、顧客", "customer"], ["kasir", "レジ係", "cashier"], ["toko buku", "書店", "bookstore"],
    ["apotek", "薬局", "pharmacy"], ["warung", "小さな店、食堂", "small shop; food stall"], ["minimarket", "コンビニ、小型スーパー", "minimarket"],
    ["pusat perbelanjaan", "ショッピングセンター", "shopping center"], ["lantai dua", "2階", "second floor"], ["pintu masuk", "入口", "entrance"],
    ["pintu keluar", "出口", "exit"], ["loket", "窓口", "ticket counter"], ["antrian", "列", "queue"], ["nomor antrian", "受付番号", "queue number"],
    ["koper", "スーツケース", "suitcase"], ["dompet", "財布", "wallet"], ["payung", "傘", "umbrella"], ["jas hujan", "レインコート", "raincoat"],
    ["kacamata", "眼鏡", "glasses"], ["kamera", "カメラ", "camera"], ["charger", "充電器", "charger"], ["baterai", "電池", "battery"],
    ["layar", "画面", "screen"], ["tombol", "ボタン", "button"], ["mesin", "機械", "machine"], ["alat", "道具", "tool"],
    ["sikat gigi", "歯ブラシ", "toothbrush"], ["pasta gigi", "歯磨き粉", "toothpaste"], ["sampo", "シャンプー", "shampoo"], ["tisu", "ティッシュ", "tissue"],
    ["sapu", "ほうき", "broom"], ["pel", "モップ", "mop"], ["ember", "バケツ", "bucket"], ["piring", "皿", "plate"],
    ["mangkuk", "茶碗、ボウル", "bowl"], ["gelas", "コップ", "glass"], ["sendok", "スプーン", "spoon"], ["garpu", "フォーク", "fork"],
    ["kompor", "コンロ", "stove"], ["panci", "鍋", "pot"], ["wajan", "フライパン", "frying pan"], ["minyak goreng", "食用油", "cooking oil"],
    ["tepung", "小麦粉、粉", "flour"], ["beras", "米", "rice grain"], ["bumbu", "調味料", "seasoning"], ["saus", "ソース", "sauce"],
    ["kecap", "しょうゆ風ソース", "soy sauce"], ["cuka", "酢", "vinegar"], ["keju", "チーズ", "cheese"], ["mentega", "バター", "butter"],
    ["kentang", "じゃがいも", "potato"], ["wortel", "にんじん", "carrot"], ["tomat", "トマト", "tomato"], ["bawang", "玉ねぎ、にんにく類", "onion; garlic"],
    ["cabai", "唐辛子", "chili"], ["kelapa", "ココナツ", "coconut"], ["kacang", "豆、ナッツ", "bean; nut"], ["udang", "えび", "shrimp"],
    ["cumi-cumi", "いか", "squid"], ["daging sapi", "牛肉", "beef"], ["daging ayam", "鶏肉", "chicken meat"], ["es krim", "アイスクリーム", "ice cream"],
    ["minuman", "飲み物", "drink"], ["makanan ringan", "軽食、スナック", "snack"], ["sarapan pagi", "朝食", "breakfast"], ["makan siang", "昼食", "lunch"],
    ["makan malam", "夕食", "dinner"], ["resep", "レシピ", "recipe"], ["rasa", "味", "taste"], ["bau", "におい", "smell"],
    ["cuaca", "天気", "weather"], ["udara", "空気", "air"], ["awan", "雲", "cloud"], ["hujan deras", "大雨", "heavy rain"],
    ["gerimis", "霧雨、小雨", "drizzle"], ["banjir", "洪水", "flood"], ["musim", "季節", "season"], ["musim hujan", "雨季", "rainy season"],
    ["musim kemarau", "乾季", "dry season"], ["suhu", "温度", "temperature"], ["derajat", "度", "degree"], ["panas matahari", "日差し", "sunlight"],
    ["kesehatan", "健康", "health"], ["penyakit", "病気", "disease"], ["demam", "熱", "fever"], ["batuk", "咳", "cough"],
    ["pilek", "風邪、鼻風邪", "cold"], ["pusing", "めまい、頭痛", "dizziness"], ["mual", "吐き気", "nausea"], ["luka", "傷", "wound"],
    ["pasien", "患者", "patient"], ["perawat", "看護師", "nurse"], ["klinik", "クリニック", "clinic"], ["resep obat", "処方箋", "prescription"],
    ["janji dokter", "診察予約", "doctor appointment"], ["asuransi", "保険", "insurance"], ["bantuan", "助け", "help"],
    ["masalah", "問題", "problem"], ["kesalahan", "間違い", "mistake"], ["alasan", "理由", "reason"], ["tujuan", "目的", "purpose"],
    ["rencana", "計画", "plan"], ["pengalaman", "経験", "experience"], ["kesempatan", "機会", "opportunity"], ["kebiasaan", "習慣", "habit"],
    ["kebutuhan", "必要なもの", "need"], ["keinginan", "願い、欲求", "desire"], ["keputusan", "決定", "decision"], ["pilihan", "選択", "choice"],
    ["aturan", "規則", "rule"], ["larangan", "禁止", "prohibition"], ["perintah", "命令", "command"], ["permintaan", "依頼", "request"],
    ["ajakan", "誘い", "invitation"], ["saran", "提案、助言", "suggestion"], ["pendapat", "意見", "opinion"], ["cerita", "話、物語", "story"],
    ["kabar", "知らせ、様子", "news; condition"], ["hubungan", "関係", "relationship"], ["perbedaan", "違い", "difference"], ["persamaan", "共通点", "similarity"],
    ["bagian", "部分", "part"], ["contoh", "例", "example"], ["cara", "方法", "way; method"], ["langkah", "手順、歩み", "step"],
    ["hasil", "結果", "result"], ["proses", "過程", "process"], ["waktu luang", "自由時間", "free time"], ["liburan", "休暇", "holiday"],
    ["perjalanan", "旅行", "trip"], ["pemandangan", "景色", "scenery"], ["oleh-oleh", "お土産", "souvenir"], ["tempat wisata", "観光地", "tourist spot"],
    ["pemandu wisata", "観光ガイド", "tour guide"], ["penumpang", "乗客", "passenger"], ["pengemudi", "運転者", "driver"], ["karcis", "切符", "ticket"],
    ["bagasi", "荷物、手荷物", "baggage"], ["jadwal penerbangan", "飛行機の時刻表", "flight schedule"], ["penerbangan", "フライト", "flight"],
    ["keberangkatan", "出発", "departure"], ["kedatangan", "到着", "arrival"], ["kapal", "船", "ship"], ["perahu", "小舟", "boat"],
    ["sepeda", "自転車", "bicycle"], ["sepeda motor", "オートバイ", "motorcycle"], ["angkot", "乗合ミニバス", "public minivan"],
    ["ojek", "バイクタクシー", "motorcycle taxi"], ["jalan tol", "高速道路", "toll road"], ["pom bensin", "ガソリンスタンド", "gas station"],
    ["bensin", "ガソリン", "gasoline"], ["bengkel", "修理工場", "repair shop"], ["ban", "タイヤ", "tire"]
  ];

  const adjectives = [
    ["aman", "安全な", "safe"], ["berbahaya", "危険な", "dangerous"], ["sibuk", "忙しい", "busy"], ["kosong", "空の、空いている", "empty"],
    ["penuh", "満員の、いっぱいの", "full"], ["cepat", "速い、早い", "fast"], ["lambat", "遅い", "slow"], ["dekat", "近い", "near"],
    ["jauh", "遠い", "far"], ["sempit", "狭い", "narrow"], ["luas", "広い", "wide; spacious"], ["berat", "重い", "heavy"],
    ["ringan", "軽い", "light"], ["tebal", "厚い", "thick"], ["tipis", "薄い", "thin"], ["keras", "硬い、激しい", "hard; loud"],
    ["lembut", "柔らかい", "soft"], ["halus", "なめらかな、細かい", "smooth"], ["kasar", "粗い、乱暴な", "rough"], ["tajam", "鋭い", "sharp"],
    ["tumpul", "鈍い", "blunt"], ["licin", "滑りやすい", "slippery"], ["basah", "濡れた", "wet"], ["kering", "乾いた", "dry"],
    ["segar", "新鮮な、さわやかな", "fresh"], ["busuk", "腐った", "rotten"], ["matang", "熟した、火が通った", "ripe; cooked"], ["mentah", "生の、未加工の", "raw"],
    ["asin", "塩辛い", "salty"], ["asam", "酸っぱい", "sour"], ["pahit", "苦い", "bitter"], ["gurih", "うま味のある", "savory"],
    ["lezat", "とてもおいしい", "delicious"], ["hangat", "暖かい", "warm"], ["sejuk", "涼しい", "cool"], ["gelap", "暗い", "dark"],
    ["terang", "明るい", "bright"], ["ribut", "騒がしい", "noisy"], ["tenang", "落ち着いた、静かな", "calm"], ["nyaman", "快適な", "comfortable"],
    ["lengkap", "完全な、そろった", "complete"], ["kurang", "足りない", "lacking"], ["cukup", "十分な", "enough"], ["lebih", "より多い、余分な", "more"],
    ["sederhana", "簡単な、質素な", "simple"], ["mewah", "豪華な", "luxurious"], ["modern", "現代的な", "modern"], ["tradisional", "伝統的な", "traditional"],
    ["terkenal", "有名な", "famous"], ["biasa", "普通の", "ordinary"], ["luar biasa", "並外れた", "extraordinary"], ["penting", "重要な", "important"],
    ["perlu", "必要な", "necessary"], ["berguna", "役に立つ", "useful"], ["sia-sia", "無駄な", "useless"], ["jelas", "明らかな", "clear"],
    ["kabur", "ぼんやりした", "unclear; blurry"], ["pasti", "確かな", "certain"], ["mungkin", "あり得る", "possible"], ["siap", "準備できた", "ready"],
    ["sibuk sekali", "とても忙しい", "very busy"], ["capek", "疲れた", "tired"], ["lelah", "疲れた", "tired"], ["mengantuk", "眠い", "sleepy"],
    ["takut", "怖い", "afraid"], ["marah", "怒った", "angry"], ["malu", "恥ずかしい", "embarrassed"], ["bangga", "誇りに思う", "proud"],
    ["khawatir", "心配な", "worried"], ["tenar", "有名な", "popular"], ["ramah", "親しみやすい", "friendly"], ["sopan", "礼儀正しい", "polite"],
    ["jujur", "正直な", "honest"], ["nakal", "いたずらな", "naughty"], ["rajin", "勤勉な", "diligent"], ["malas", "怠けた", "lazy"],
    ["pintar", "賢い", "smart"], ["bodoh", "愚かな", "stupid"], ["kaya", "裕福な", "rich"], ["miskin", "貧しい", "poor"],
    ["gratis", "無料の", "free of charge"], ["terakhir", "最後の", "last"], ["pertama", "最初の", "first"], ["kedua", "2番目の", "second"],
    ["ketiga", "3番目の", "third"], ["sendiri", "自分自身の、一人で", "own; alone"], ["bersama", "一緒の", "together"], ["lain", "他の", "other"],
    ["sama", "同じ", "same"], ["berbeda", "異なる", "different"], ["bening", "澄んだ", "clear"], ["keruh", "濁った", "cloudy"],
    ["rapi", "整った", "neat"], ["berantakan", "散らかった", "messy"], ["rusak", "壊れた", "broken"], ["baru saja", "たった今の", "just now"],
    ["lama", "長い、古い", "long; old"], ["sementara", "一時的な", "temporary"], ["tetap", "固定の、変わらない", "fixed"], ["langsung", "直接の", "direct"]
  ];

  const adverbs = [
    ["pelan-pelan", "ゆっくり", "slowly"], ["cepat-cepat", "急いで", "quickly"], ["sering", "よく、しばしば", "often"],
    ["jarang", "めったに〜ない", "rarely"], ["kadang-kadang", "ときどき", "sometimes"], ["selalu", "いつも", "always"],
    ["biasanya", "ふつう、たいてい", "usually"], ["segera", "すぐに", "immediately"], ["baru saja", "たった今", "just now"],
    ["hampir", "ほとんど、もう少しで", "almost"], ["kira-kira", "およそ", "approximately"], ["sekitar", "約、周辺に", "around"],
    ["terlalu", "〜すぎる", "too"], ["cukup", "かなり、十分に", "enough; quite"], ["sangat", "とても", "very"],
    ["sekali", "とても", "very"], ["lebih dulu", "先に", "first; beforehand"], ["nanti malam", "今夜あとで", "later tonight"],
    ["besok pagi", "明日の朝", "tomorrow morning"], ["kemarin sore", "昨日の夕方", "yesterday afternoon"], ["minggu depan", "来週", "next week"],
    ["bulan depan", "来月", "next month"], ["tahun depan", "来年", "next year"], ["minggu lalu", "先週", "last week"],
    ["bulan lalu", "先月", "last month"], ["tahun lalu", "去年", "last year"], ["di sini", "ここで、ここに", "here"],
    ["di sana", "そこで、そこに", "there"], ["di situ", "そこで、そこに", "there"], ["ke sini", "こちらへ", "to here"],
    ["ke sana", "あちらへ", "to there"], ["dari sini", "ここから", "from here"], ["dari sana", "そこから", "from there"],
    ["bersama-sama", "一緒に", "together"], ["sendirian", "一人で", "alone"], ["diam-diam", "黙って、こっそり", "quietly"],
    ["terus", "続けて、ずっと", "continuously"], ["langsung", "直接、すぐに", "directly"], ["kembali", "再び、戻って", "back; again"],
    ["sebaiknya", "〜したほうがよい", "had better"], ["seharusnya", "本来〜すべき", "should"], ["mungkin", "たぶん", "maybe"],
    ["pasti", "きっと、必ず", "certainly"], ["tentu saja", "もちろん", "of course"], ["sebenarnya", "実は", "actually"],
    ["akhirnya", "ついに", "finally"], ["mulanya", "最初は", "at first"], ["kemudian", "その後", "then"], ["lalu", "それから", "then"],
    ["baru", "新しく、〜したばかり", "newly; just"], ["masih", "まだ", "still"], ["pernah", "〜したことがある", "ever"], ["belum pernah", "まだ〜したことがない", "never yet"],
    ["sudah pernah", "すでに〜したことがある", "have ever"], ["tidak pernah", "一度も〜ない", "never"], ["boleh", "〜してよい", "may"], ["harus", "〜しなければならない", "must"],
    ["dapat", "〜できる", "can"], ["bisa", "〜できる", "can"], ["akan", "〜するつもり、〜だろう", "will"], ["sedang", "〜しているところ", "currently"],
    ["sedikit lagi", "もう少しで", "almost"], ["begitu", "そのように", "like that"], ["begini", "このように", "like this"], ["barangkali", "おそらく", "perhaps"]
  ];

  const functionWords = [
    ["sebagai", "〜として", "as", "前置詞", "Dia bekerja sebagai guru.", "彼は先生として働いています。"],
    ["seperti", "〜のように", "like; such as", "前置詞", "Rumah itu besar seperti hotel.", "その家はホテルのように大きいです。"],
    ["daripada", "〜よりも", "than", "前置詞", "Kopi lebih pahit daripada teh.", "コーヒーはお茶より苦いです。"],
    ["kepada", "〜へ、〜に", "to", "前置詞", "Saya memberi surat kepada guru.", "私は先生に手紙を渡します。"],
    ["oleh", "〜によって", "by", "前置詞", "Buku itu ditulis oleh guru.", "その本は先生によって書かれました。"],
    ["tanpa", "〜なしで", "without", "前置詞", "Saya pergi tanpa payung.", "私は傘なしで行きます。"],
    ["selama", "〜の間", "during; for", "前置詞", "Saya tinggal di Bali selama seminggu.", "私は1週間バリに滞在します。"],
    ["sejak", "〜以来", "since", "前置詞", "Saya belajar sejak tahun lalu.", "私は去年から勉強しています。"],
    ["sambil", "〜しながら", "while", "接続詞", "Saya makan sambil menonton TV.", "私はテレビを見ながら食べます。"],
    ["supaya", "〜するように", "so that", "接続詞", "Saya belajar supaya lulus ujian.", "私は試験に合格するように勉強します。"],
    ["agar", "〜するように", "so that", "接続詞", "Tolong datang pagi agar tidak terlambat.", "遅れないように朝来てください。"],
    ["sebelum itu", "その前に", "before that", "接続詞", "Sebelum itu, saya makan dulu.", "その前に、私は先に食べます。"],
    ["sesudah itu", "その後で", "after that", "接続詞", "Sesudah itu, kami pulang.", "その後で私たちは帰ります。"],
    ["walaupun", "〜だけれども", "although", "接続詞", "Walaupun hujan, saya pergi.", "雨だけれども、私は行きます。"],
    ["namun", "しかし", "however", "接続詞", "Dia sibuk, namun tetap datang.", "彼は忙しいですが、それでも来ます。"],
    ["jadi", "だから、つまり", "so; therefore", "接続詞", "Hari hujan, jadi saya di rumah.", "雨なので、私は家にいます。"],
    ["berarti", "つまり、意味する", "meaning; means", "接続詞", "Ini berarti kita harus menunggu.", "これは私たちが待たなければならないという意味です。"],
    ["yaitu", "すなわち", "namely", "接続詞", "Saya punya dua hobi, yaitu musik dan film.", "私には音楽と映画という2つの趣味があります。"],
    ["misalnya", "例えば", "for example", "接続詞", "Saya suka buah, misalnya mangga.", "私は果物、例えばマンゴーが好きです。"],
    ["selain itu", "そのほかに", "besides that", "接続詞", "Selain itu, harganya murah.", "そのほかに、値段が安いです。"],
    ["oleh karena itu", "そのため", "therefore", "接続詞", "Oleh karena itu, kami pulang.", "そのため、私たちは帰りました。"],
    ["bagaimanapun", "いずれにしても", "anyway; however", "接続詞", "Bagaimanapun, kita harus mencoba.", "いずれにしても、私たちは試すべきです。"],
    ["masing-masing", "それぞれ", "each", "副詞", "Masing-masing orang mendapat satu tiket.", "それぞれの人がチケットを1枚受け取ります。"],
    ["setiap", "毎〜、それぞれの", "each; every", "数詞", "Saya belajar setiap hari.", "私は毎日勉強します。"],
    ["beberapa", "いくつかの", "several", "数詞", "Saya membeli beberapa buku.", "私は本を数冊買います。"],
    ["sebagian", "一部", "part; some", "数詞", "Sebagian murid sudah pulang.", "生徒の一部はもう帰りました。"],
    ["separuh", "半分", "half", "数詞", "Saya makan separuh roti.", "私はパンを半分食べます。"],
    ["semacam", "一種の", "a kind of", "数詞", "Ini semacam obat tradisional.", "これは一種の伝統薬です。"],
    ["para", "〜たち", "plural marker", "数詞", "Para guru sedang rapat.", "先生たちは会議中です。"],
    ["seseorang", "誰か", "someone", "代名詞", "Seseorang menunggu di depan.", "誰かが前で待っています。"],
    ["sesuatu", "何か", "something", "代名詞", "Saya mencari sesuatu di tas.", "私はかばんの中で何かを探しています。"],
    ["siapa saja", "誰でも", "anyone", "代名詞", "Siapa saja boleh masuk.", "誰でも入れます。"],
    ["apa saja", "何でも", "anything", "代名詞", "Saya mau makan apa saja.", "私は何でも食べたいです。"],
    ["yang mana", "どちら、どれ", "which one", "疑問詞", "Yang mana milik Anda?", "どれがあなたのものですか。"],
    ["berapa lama", "どのくらいの期間", "how long", "疑問詞", "Berapa lama Anda tinggal di sini?", "あなたはここにどのくらい滞在しますか。"],
    ["berapa kali", "何回", "how many times", "疑問詞", "Berapa kali Anda ke Bali?", "あなたは何回バリへ行きましたか。"],
    ["jam berapa", "何時", "what time", "疑問詞", "Jam berapa kereta berangkat?", "電車は何時に出発しますか。"],
    ["bolehkah", "〜してもいいですか", "may I", "表現", "Bolehkah saya masuk?", "入ってもいいですか。"],
    ["maukah", "〜してくれますか", "would you", "表現", "Maukah Anda membantu saya?", "私を手伝ってくれますか。"],
    ["tidak apa-apa", "大丈夫です", "it is okay", "表現", "Tidak apa-apa, saya bisa menunggu.", "大丈夫です、私は待てます。"],
    ["hati-hati", "気をつけて", "be careful", "表現", "Hati-hati di jalan.", "道中気をつけてください。"],
    ["selamat jalan", "行ってらっしゃい、さようなら", "goodbye", "表現", "Selamat jalan, sampai jumpa.", "行ってらっしゃい、また会いましょう。"],
    ["selamat datang", "ようこそ", "welcome", "表現", "Selamat datang di Jakarta.", "ジャカルタへようこそ。"],
    ["selamat ulang tahun", "誕生日おめでとう", "happy birthday", "表現", "Selamat ulang tahun, Rina.", "リナさん、誕生日おめでとう。"],
    ["mohon maaf", "申し訳ありません", "please forgive me", "表現", "Mohon maaf, saya terlambat.", "申し訳ありません、遅れました。"],
    ["dengan senang hati", "喜んで", "with pleasure", "表現", "Dengan senang hati saya membantu.", "喜んでお手伝いします。"],
    ["sama-sama", "どういたしまして", "you are welcome", "表現", "Sama-sama, tidak apa-apa.", "どういたしまして、大丈夫です。"],
    ["apa kabar", "お元気ですか", "how are you", "表現", "Apa kabar hari ini?", "今日はお元気ですか。"],
    ["baik-baik saja", "元気です、大丈夫です", "fine", "表現", "Saya baik-baik saja.", "私は元気です。"]
  ];

  const months = [
    ["Januari", "1月", "January"], ["Februari", "2月", "February"], ["Maret", "3月", "March"], ["April", "4月", "April"],
    ["Mei", "5月", "May"], ["Juni", "6月", "June"], ["Juli", "7月", "July"], ["Agustus", "8月", "August"],
    ["September", "9月", "September"], ["Oktober", "10月", "October"], ["November", "11月", "November"], ["Desember", "12月", "December"]
  ];

  const numberWords = [
    ["tiga belas", "13", "thirteen"], ["empat belas", "14", "fourteen"], ["lima belas", "15", "fifteen"], ["enam belas", "16", "sixteen"],
    ["tujuh belas", "17", "seventeen"], ["delapan belas", "18", "eighteen"], ["sembilan belas", "19", "nineteen"], ["dua puluh", "20", "twenty"],
    ["tiga puluh", "30", "thirty"], ["empat puluh", "40", "forty"], ["lima puluh", "50", "fifty"], ["enam puluh", "60", "sixty"],
    ["tujuh puluh", "70", "seventy"], ["delapan puluh", "80", "eighty"], ["sembilan puluh", "90", "ninety"], ["dua ratus", "200", "two hundred"],
    ["seribu", "1000", "one thousand"], ["sejuta", "100万", "one million"], ["pertama", "第1の", "first"], ["kedua", "第2の", "second"]
  ];

  const rows = []
    .concat(transitiveVerbs.map(([word, japanese, english, object, objectJapanese]) => ({
      word,
      japanese,
      english,
      partOfSpeech: "動詞",
      category: "動詞",
      example: `Saya ${word} ${object}.`,
      exampleJapanese: `私は${objectJapanese}を${japanese}。`,
      note: "D級で覚えたい他動詞。目的語と一緒に例文ごと覚える。"
    })))
    .concat(intransitiveVerbs.map(([word, japanese, english, place, placeJapanese]) => ({
      word,
      japanese,
      english,
      partOfSpeech: "動詞",
      category: "動詞",
      example: `Saya ${word} ${place}.`,
      exampleJapanese: `私は${placeJapanese}${japanese}。`,
      note: "D級で覚えたい動詞。場所や時間の語と一緒に使いやすい。"
    })))
    .concat(functionWords.map(([word, japanese, english, partOfSpeech, example, exampleJapanese]) => ({
      word,
      japanese,
      english,
      partOfSpeech,
      category: partOfSpeech,
      example,
      exampleJapanese,
      note: "D級で覚えたい機能語・表現。短い文の中で使い方を確認する。"
    })))
    .concat(adverbs.map(([word, japanese, english]) => ({
      word,
      japanese,
      english,
      partOfSpeech: "副詞",
      category: "副詞",
      example: `Saya belajar ${word}.`,
      exampleJapanese: `私は${japanese}勉強します。`,
      note: "D級で覚えたい副詞。動詞や文全体をくわしく説明する。"
    })))
    .concat(months.map(([word, japanese, english]) => ({
      word,
      japanese,
      english,
      partOfSpeech: "名詞",
      category: "名詞",
      example: `Saya pergi pada bulan ${word}.`,
      exampleJapanese: `私は${japanese}に行きます。`,
      note: "月の名前。日付や予定を言うときに使う。"
    })))
    .concat(numberWords.map(([word, japanese, english]) => ({
      word,
      japanese,
      english,
      partOfSpeech: "数詞",
      category: "数詞",
      example: `Saya membeli ${word} tiket.`,
      exampleJapanese: `私はチケットを${japanese}枚買います。`,
      note: "数を表す語。値段、時間、数量でよく使う。"
    })))
    .concat(adjectives.map(([word, japanese, english]) => ({
      word,
      japanese,
      english,
      partOfSpeech: "形容詞",
      category: "形容詞",
      example: `Tempat ini ${word}.`,
      exampleJapanese: `この場所は${japanese}。`,
      note: "D級で覚えたい形容詞。名詞の後ろに置いて説明できる。"
    })))
    .concat(nouns.map(([word, japanese, english]) => ({
      word,
      japanese,
      english,
      partOfSpeech: word.includes(" ") ? "名詞句" : "名詞",
      category: word.includes(" ") ? "名詞句" : "名詞",
      example: `Saya perlu ${word}.`,
      exampleJapanese: `私は${japanese}が必要です。`,
      note: "D級で覚えたい名詞。手続き、旅行、日常生活で使いやすい。"
    })));

  const selectedRows = [];
  rows.forEach((row) => {
    const key = row.word.toLowerCase();
    if (!usedWords.has(key) && !selectedRows.some((item) => item.word.toLowerCase() === key)) {
      selectedRows.push(row);
    }
  });

  selectedRows.slice(0, targetAdditional).forEach((row, index) => {
    appData.words.push({
      id: `d-${String(startNumber + index).padStart(3, "0")}`,
      level: "D",
      word: row.word,
      japanese: row.japanese,
      english: row.english,
      partOfSpeech: row.partOfSpeech,
      category: row.category,
      example: row.example,
      exampleJapanese: row.exampleJapanese,
      note: row.note
    });
  });
})();
