(function () {
  const appData = window.INDONESIAN_FLASHCARD_DATA;
  if (!appData || !Array.isArray(appData.words)) {
    return;
  }

  const usedWords = new Set(appData.words.map((word) => word.word.toLowerCase()));
  const currentCWords = appData.words.filter((word) => word.level === "C");
  const currentMaxNumber = currentCWords.reduce((max, word) => {
    const match = /^c-(\d+)$/.exec(word.id);
    return match ? Math.max(max, Number(match[1])) : max;
  }, 0);

  const candidates = [];

  function sentenceCase(text) {
    return text.charAt(0).toUpperCase() + text.slice(1);
  }

  const jpMain = (text) => String(text || "").split("、")[0];

  function addCard(card) {
    candidates.push({
      level: "C",
      category: card.partOfSpeech,
      ...card
    });
  }

  // 実在する能動形と di- 受動形のペア。受動形の日本語は行ごとに明記する。
  // [能動形, 日本語, 英語, 受動形, 受動形の日本語, 目的語, 目的語の訳, 動作主, 動作主の訳, 助詞(省略時は「を」)]
  // 動作主が null の行は「〜されるべきだ」型の例文になる。
  const affixPairs = [
    ["mengelola", "管理する、運営する", "to manage", "dikelola", "管理される", "program itu", "その事業", "pemerintah daerah", "地方政府"],
    ["melindungi", "保護する", "to protect", "dilindungi", "保護される", "hak pekerja", "労働者の権利", "undang-undang", "法律"],
    ["mengembangkan", "開発する、発展させる", "to develop", "dikembangkan", "開発される", "usaha kecil", "小規模事業", "pemerintah", "政府"],
    ["membangun", "建設する", "to build", "dibangun", "建設される", "jembatan baru", "新しい橋", "perusahaan itu", "その会社"],
    ["memproduksi", "生産する", "to produce", "diproduksi", "生産される", "barang lokal", "地元製品", "pabrik itu", "その工場"],
    ["mendistribusikan", "配送する、分配する", "to distribute", "didistribusikan", "分配される", "bantuan", "支援物資", "petugas", "係員"],
    ["memutuskan", "決定する", "to decide", "diputuskan", "決定される", "perkara itu", "その件", "pengadilan", "裁判所"],
    ["meningkatkan", "向上させる、引き上げる", "to improve; increase", "ditingkatkan", "引き上げられる", "kualitas layanan", "サービスの質", "pemerintah", "政府"],
    ["memperluas", "拡大する", "to expand", "diperluas", "拡大される", "jaringan internet", "インターネット網", "perusahaan", "会社"],
    ["memperkuat", "強化する", "to strengthen", "diperkuat", "強化される", "kerja sama", "協力", "kedua negara", "両国"],
    ["menyediakan", "用意する、提供する", "to provide", "disediakan", "用意される", "air bersih", "清潔な水", "panitia", "主催者"],
    ["memenuhi", "満たす", "to fulfill", "dipenuhi", "満たされる", "syarat itu", "その条件", "semua peserta", "すべての参加者"],
    ["memisahkan", "分ける", "to separate", "dipisahkan", "分けられる", "sampah plastik", "プラスチックごみ", "warga", "住民"],
    ["meneliti", "調査する、研究する", "to research", "diteliti", "調査される", "kebiasaan masyarakat", "社会の習慣", "para ahli", "専門家たち"],
    ["mengamati", "観察する", "to observe", "diamati", "観察される", "perubahan cuaca", "天気の変化", "petugas", "係員"],
    ["mengawasi", "監視する、監督する", "to supervise", "diawasi", "監視される", "kegiatan siswa", "生徒の活動", "guru", "先生"],
    ["mengendalikan", "制御する", "to control", "dikendalikan", "制御される", "lalu lintas", "交通", "polisi", "警察"],
    ["mencegah", "防ぐ", "to prevent", "dicegah", "防がれる", "kecelakaan", "事故", null, null],
    ["menghindari", "避ける", "to avoid", "dihindari", "避けられる", "kemacetan", "渋滞", null, null],
    ["menyelamatkan", "救助する", "to rescue", "diselamatkan", "救助される", "korban banjir", "洪水の被災者", "tim penyelamat", "救助隊"],
    ["mengamankan", "警備する、確保する", "to secure", "diamankan", "警備される", "lokasi acara", "行事会場", "polisi", "警察"],
    ["mendidik", "教育する", "to educate", "dididik", "教育される", "anak-anak", "子どもたち", "orang tua", "親"],
    ["mengajar", "教える", "to teach", "diajar", "教えられる", "murid baru", "新しい生徒", "guru itu", "その先生"],
    ["melatih", "訓練する", "to train", "dilatih", "訓練される", "pegawai baru", "新入職員", "pelatih", "コーチ"],
    ["menguji", "試験する、試す", "to test", "diuji", "試される", "kemampuan bahasa", "語学力", "penguji", "試験官"],
    ["menerjemahkan", "翻訳する", "to translate", "diterjemahkan", "翻訳される", "dokumen resmi", "公式書類", "penerjemah", "翻訳者"],
    ["mencetak", "印刷する", "to print", "dicetak", "印刷される", "brosur wisata", "観光パンフレット", "percetakan", "印刷所"],
    ["menjual", "売る", "to sell", "dijual", "売られる", "produk lokal", "地元製品", "pedagang", "商人"],
    ["membeli", "買う", "to buy", "dibeli", "買われる", "barang itu", "その品物", "banyak orang", "多くの人"],
    ["memesan", "予約する、注文する", "to order; reserve", "dipesan", "予約される", "kamar hotel", "ホテルの部屋", "tamu", "客"],
    ["menyewa", "借りる", "to rent", "disewa", "賃借される", "rumah kecil", "小さな家", "keluarga muda", "若い家族"],
    ["meminjam", "借りる", "to borrow", "dipinjam", "借りられる", "buku referensi", "参考書", "mahasiswa", "大学生"],
    ["mengembalikan", "返す", "to return", "dikembalikan", "返される", "barang pinjaman", "借りた品物", "peminjam", "借り主"],
    ["mewarisi", "受け継ぐ", "to inherit", "diwarisi", "受け継がれる", "budaya lokal", "地域文化", "generasi muda", "若い世代"],
    ["mewakili", "代表する", "to represent", "diwakili", "代表される", "kelompok itu", "そのグループ", "ketua", "代表者"],
    ["menolak", "断る、拒否する", "to refuse", "ditolak", "断られる", "usulan itu", "その提案", "panitia", "委員会"],
    ["menyetujui", "承認する、同意する", "to approve", "disetujui", "承認される", "rencana kerja", "作業計画", "pemerintah", "政府"],
    ["mempercayai", "信頼する、信じる", "to trust", "dipercayai", "信じられる", "informasi itu", "その情報", "banyak orang", "多くの人"],
    ["melupakan", "忘れる", "to forget", "dilupakan", "忘れられる", "kejadian itu", "その出来事", "orang-orang", "人々"],
    ["memikirkan", "考える、検討する", "to think about", "dipikirkan", "検討される", "masalah itu", "その問題", null, null],
    ["merasakan", "感じる", "to feel", "dirasakan", "感じられる", "dampak perubahan itu", "その変化の影響", "warga", "住民"],
    ["menyukai", "好む", "to like", "disukai", "好かれる", "makanan manis", "甘い食べ物", "anak-anak", "子どもたち"],
    ["menikmati", "楽しむ、味わう", "to enjoy", "dinikmati", "楽しまれる", "pemandangan laut", "海の景色", "wisatawan", "観光客"],
    ["mengkhawatirkan", "心配する、懸念する", "to worry about", "dikhawatirkan", "心配される", "keselamatan anak", "子どもの安全", "orang tua", "親"],
    ["mendorong", "促す、後押しする", "to encourage", "didorong", "後押しされる", "perubahan itu", "その変化", "pemerintah", "政府"],
    ["memindahkan", "移す", "to move", "dipindahkan", "移される", "kantor cabang", "支店", "perusahaan", "会社"],
    ["mengalihkan", "切り替える、転換する", "to divert; shift", "dialihkan", "切り替えられる", "arus lalu lintas", "交通の流れ", "polisi", "警察"],
    ["mengisi", "記入する", "to fill in", "diisi", "記入される", "formulir itu", "その用紙", "peserta", "参加者"],
    ["mengosongkan", "空にする", "to empty", "dikosongkan", "空けられる", "ruang rapat", "会議室", "petugas", "係員"],
    ["memuat", "掲載する、載せる", "to publish; load", "dimuat", "掲載される", "berita itu", "そのニュース", "koran itu", "その新聞"],
    ["menulis", "書く", "to write", "ditulis", "書かれる", "artikel itu", "その記事", "wartawan", "記者"],
    ["membaca", "読む", "to read", "dibaca", "読まれる", "buku itu", "その本", "banyak orang", "多くの人"],
    ["menemukan", "見つける、発見する", "to find", "ditemukan", "発見される", "dompet itu", "その財布", "petugas stasiun", "駅員"],
    ["menghilangkan", "取り除く、なくす", "to remove", "dihilangkan", "取り除かれる", "rasa takut", "恐怖心", null, null],
    ["menjalankan", "実施する、動かす", "to run; carry out", "dijalankan", "実施される", "program bantuan", "支援プログラム", "pemerintah", "政府"],
    ["melaksanakan", "実施する", "to implement", "dilaksanakan", "実施される", "kegiatan sosial", "社会活動", "para siswa", "生徒たち"],
    ["menghasilkan", "生み出す", "to produce", "dihasilkan", "生み出される", "produk baru", "新製品", "pabrik itu", "その工場"],
    ["menyimpan", "保管する", "to store", "disimpan", "保管される", "data pelanggan", "顧客データ", "perusahaan", "会社"],
    ["mengumpulkan", "集める", "to collect", "dikumpulkan", "集められる", "formulir pendaftaran", "申込用紙", "panitia", "委員会"],
    ["menyusun", "作成する、編成する", "to compose; arrange", "disusun", "作成される", "laporan bulanan", "月次報告", "staf", "スタッフ"],
    ["membandingkan", "比較する", "to compare", "dibandingkan", "比較される", "dua produk itu", "その2つの商品", "pembeli", "買い手"],
    ["menilai", "評価する", "to evaluate", "dinilai", "評価される", "hasil kerja", "仕事の結果", "atasan", "上司"],
    ["mengukur", "測る", "to measure", "diukur", "測られる", "suhu tubuh", "体温", "perawat", "看護師"],
    ["menghitung", "計算する", "to calculate", "dihitung", "計算される", "biaya perjalanan", "旅行費用", "petugas", "係員"],
    ["memeriksa", "検査する、確認する", "to check", "diperiksa", "検査される", "dokumen perjalanan", "旅行書類", "petugas imigrasi", "入国審査官"],
    ["mengobati", "治療する", "to treat", "diobati", "治療される", "pasien demam", "熱のある患者", "dokter", "医者"],
    ["merawat", "看護する、手入れする", "to care for", "dirawat", "看護される", "pasien tua", "高齢の患者", "perawat", "看護師"],
    ["membuka", "開く、開始する", "to open", "dibuka", "開始される", "pendaftaran", "登録受付", "panitia", "委員会"],
    ["menutup", "閉じる、閉鎖する", "to close", "ditutup", "閉鎖される", "jalan utama", "主要道路", "polisi", "警察"],
    ["mengatur", "調整する、定める", "to arrange", "diatur", "定められる", "jadwal kerja", "勤務予定", "manajer", "マネージャー"],
    ["mengurus", "手続きする、処理する", "to handle", "diurus", "処理される", "izin tinggal", "滞在許可", "petugas", "係員"],
    ["mencatat", "記録する", "to record", "dicatat", "記録される", "hasil rapat", "会議の結果", "sekretaris", "書記"],
    ["melaporkan", "報告する", "to report", "dilaporkan", "報告される", "kejadian itu", "その出来事", "saksi", "目撃者"],
    ["menjelaskan", "説明する", "to explain", "dijelaskan", "説明される", "peraturan baru", "新しい規則", "guru", "先生"],
    ["menghubungi", "連絡する", "to contact", "dihubungi", "連絡を受ける", "kantor pusat", "本社", "kantor cabang", "支店", "に"],
    ["menentukan", "定める、決定する", "to determine", "ditentukan", "定められる", "tanggal ujian", "試験日", "sekolah", "学校"],
    ["mengubah", "変える", "to change", "diubah", "変更される", "rencana awal", "当初の計画", "tim", "チーム"],
    ["mengganti", "交換する、替える", "to replace", "diganti", "交換される", "kartu lama", "古いカード", "bank", "銀行"],
    ["menambah", "追加する、増やす", "to add", "ditambah", "追加される", "jumlah kursi", "座席数", "panitia", "委員会"],
    ["mengurangi", "減らす", "to reduce", "dikurangi", "減らされる", "biaya produksi", "生産費", "perusahaan", "会社"],
    ["menaikkan", "引き上げる", "to raise", "dinaikkan", "引き上げられる", "harga tiket", "チケット価格", "pengelola", "運営者"],
    ["menurunkan", "引き下げる", "to lower", "diturunkan", "引き下げられる", "tarif listrik", "電気料金", "pemerintah", "政府"],
    ["memperbaiki", "修理する、改善する", "to repair; improve", "diperbaiki", "修理される", "mesin yang rusak", "壊れた機械", "teknisi", "技術者"],
    ["mempercepat", "早める", "to speed up", "dipercepat", "早められる", "proses kerja", "作業工程", "tim", "チーム"],
    ["memperpanjang", "延長する", "to extend", "diperpanjang", "延長される", "masa berlaku visa", "ビザの有効期間", "kantor imigrasi", "入国管理局"]
  ];

  affixPairs.forEach((row) => {
    const [active, activeJp, activeEn, passive, passiveJp, object, objectJp, agent, agentJp, particle] = row;

    addCard({
      word: active,
      japanese: activeJp,
      english: activeEn,
      partOfSpeech: "動詞",
      example: `Mereka ${active} ${object}.`,
      exampleJapanese: `彼らは${objectJp}${particle || "を"}${jpMain(activeJp)}。`,
      note: "C級で重要な接辞つき動詞。目的語と一緒に覚える。"
    });

    if (passive) {
      addCard({
        word: passive,
        japanese: passiveJp,
        english: `${activeEn} (passive)`,
        partOfSpeech: "動詞",
        example: agent
          ? `${sentenceCase(object)} ${passive} oleh ${agent}.`
          : `${sentenceCase(object)} harus ${passive}.`,
        exampleJapanese: agent
          ? `${objectJp}は${agentJp}によって${passiveJp}。`
          : `${objectJp}は${passiveJp}べきだ。`,
        note: `di- 受動形。能動形は ${active}。`
      });
    }
  });

  // 実在する派生名詞。行ごとに例文を明記する。
  const derivedNouns = [
    ["pengiriman", "発送、送付", "shipping; delivery", "Pengiriman paket itu cepat.", "その荷物の発送は速いです。"],
    ["penerimaan", "受け入れ、受領", "acceptance; reception", "Penerimaan siswa baru dibuka bulan ini.", "新入生の受け入れは今月始まります。"],
    ["pembayaran", "支払い", "payment", "Pembayaran dapat dilakukan dengan kartu.", "支払いはカードで行えます。"],
    ["penggunaan", "使用、利用", "use; usage", "Penggunaan internet meningkat.", "インターネット利用は増えています。"],
    ["pemakaian", "使用", "usage; consumption", "Pemakaian listrik naik bulan ini.", "今月の電気使用量は増えました。"],
    ["pendaftaran", "登録", "registration", "Pendaftaran ditutup hari Jumat.", "登録は金曜日に締め切られます。"],
    ["pemilihan", "選択、選挙", "selection; election", "Pemilihan ketua diadakan besok.", "代表の選挙は明日行われます。"],
    ["pemilih", "有権者", "voter", "Jumlah pemilih meningkat.", "有権者数は増えました。"],
    ["penjelasan", "説明", "explanation", "Penjelasan guru mudah dipahami.", "先生の説明は分かりやすいです。"],
    ["keterangan", "説明、情報", "information; explanation", "Baca keterangan di bawah ini.", "下の説明を読んでください。"],
    ["penelitian", "研究、調査", "research", "Penelitian itu memakan waktu lama.", "その研究は長い時間がかかります。"],
    ["peneliti", "研究者", "researcher", "Peneliti itu bekerja di universitas.", "その研究者は大学で働いています。"],
    ["pengamat", "観察者、評論家", "observer; analyst", "Pengamat ekonomi memberi komentar.", "経済評論家がコメントします。"],
    ["pengawas", "監督者", "supervisor", "Pengawas ujian sudah datang.", "試験監督はもう来ています。"],
    ["pencegahan", "予防", "prevention", "Pencegahan lebih baik daripada pengobatan.", "予防は治療に勝ります。"],
    ["penyelamatan", "救助", "rescue", "Tim penyelamatan tiba di lokasi.", "救助隊が現場に到着しました。"],
    ["pengobatan", "治療", "treatment", "Pengobatan itu berjalan lancar.", "その治療は順調に進んでいます。"],
    ["perawatan", "手入れ、ケア", "care; maintenance", "Mesin ini perlu perawatan.", "この機械は手入れが必要です。"],
    ["pendidikan", "教育", "education", "Pendidikan anak sangat penting.", "子どもの教育はとても重要です。"],
    ["pengajar", "教員、講師", "instructor", "Pengajar kursus itu berpengalaman.", "その講座の教員は経験豊富です。"],
    ["pelatihan", "研修、訓練", "training", "Pegawai baru mengikuti pelatihan.", "新入職員は研修に参加します。"],
    ["penerjemah", "翻訳者", "translator", "Penerjemah itu menguasai tiga bahasa.", "その翻訳者は3つの言語に堪能です。"],
    ["penjualan", "販売", "sales", "Penjualan produk itu meningkat.", "その製品の販売は伸びています。"],
    ["pembelian", "購入", "purchase", "Pembelian tiket dilakukan online.", "チケットの購入はオンラインで行われます。"],
    ["pemesanan", "予約", "booking", "Pemesanan kamar bisa lewat internet.", "部屋の予約はインターネットでできます。"],
    ["pengembalian", "返却", "return", "Pengembalian buku paling lambat hari Senin.", "本の返却は遅くとも月曜日です。"],
    ["perwakilan", "代表、代表部", "representation; delegation", "Perwakilan perusahaan hadir dalam rapat.", "会社の代表が会議に出席します。"],
    ["kepercayaan", "信頼、信仰", "trust; belief", "Kepercayaan pelanggan harus dijaga.", "顧客の信頼は守られなければなりません。"],
    ["pemikiran", "考え、思想", "thought; idea", "Pemikiran itu menarik.", "その考えは興味深いです。"],
    ["perasaan", "気持ち、感情", "feeling", "Jangan menyakiti perasaan orang lain.", "他人の気持ちを傷つけないでください。"],
    ["pemindahan", "移転", "relocation; transfer", "Pemindahan kantor selesai bulan depan.", "事務所の移転は来月終わります。"],
    ["pengisian", "記入", "filling in", "Pengisian formulir memakan waktu.", "用紙の記入は時間がかかります。"],
    ["penyimpanan", "保管", "storage", "Penyimpanan data harus aman.", "データの保管は安全でなければなりません。"],
    ["pengumpulan", "収集、提出", "collection", "Pengumpulan tugas paling lambat besok.", "課題の提出は遅くとも明日です。"],
    ["penilaian", "評価", "evaluation", "Penilaian dilakukan setiap bulan.", "評価は毎月行われます。"],
    ["pemeriksaan", "検査", "inspection; examination", "Pemeriksaan kesehatan diadakan hari ini.", "健康診断は今日行われます。"],
    ["perubahan", "変化、変更", "change", "Ada perubahan jadwal.", "予定の変更があります。"],
    ["kenaikan", "上昇、値上がり", "increase; rise", "Kenaikan harga terjadi setiap tahun.", "値上がりは毎年起きます。"],
    ["penurunan", "下落、低下", "decrease; decline", "Penurunan harga membuat pembeli senang.", "値下がりは買い手を喜ばせます。"],
    ["peningkatan", "向上、増加", "improvement; increase", "Peningkatan kualitas menjadi tujuan utama.", "品質の向上が主な目標です。"],
    ["perpanjangan", "延長", "extension", "Saya mengurus perpanjangan visa.", "私はビザ延長の手続きをします。"],
    ["perluasan", "拡大、拡張", "expansion", "Perluasan jalan sedang berlangsung.", "道路の拡張が進んでいます。"],
    ["penguatan", "強化", "strengthening", "Kedua negara membahas penguatan kerja sama.", "両国は協力の強化を話し合います。"],
    ["penyediaan", "提供", "provision", "Penyediaan air bersih menjadi prioritas.", "清潔な水の提供が優先事項です。"],
    ["pembangunan", "建設、開発", "construction; development", "Pembangunan jalan itu belum selesai.", "その道路の建設はまだ終わっていません。"],
    ["pengelolaan", "管理、運営", "management", "Pengelolaan sampah perlu diperbaiki.", "ごみの管理は改善される必要があります。"],
    ["pengembangan", "開発", "development", "Pengembangan aplikasi itu berjalan cepat.", "そのアプリの開発は速く進んでいます。"],
    ["pengawasan", "監督", "supervision", "Pengawasan lingkungan perlu ditingkatkan.", "環境の監督は強化される必要があります。"],
    ["keamanan", "安全、治安", "security", "Keamanan kota ini baik.", "この町の治安は良いです。"]
  ];

  derivedNouns.forEach(([word, japanese, english, example, exampleJapanese]) => {
    addCard({
      word,
      japanese,
      english,
      partOfSpeech: "名詞",
      example,
      exampleJapanese,
      note: "接辞から作られる実在の派生名詞。読解で形から意味を推測できるようにする。"
    });
  });

  addCard({
    word: "berlaku",
    japanese: "有効である",
    english: "valid; in effect",
    partOfSpeech: "動詞",
    example: "Tiket ini berlaku selama satu bulan.",
    exampleJapanese: "このチケットは1か月間有効です。",
    note: "C級で読解・作文に役立つ語彙。masa berlaku は「有効期間」。"
  });

  const directRows = [
    ["sebaliknya", "反対に", "on the contrary", "接続詞", "Sebaliknya, harga barang itu turun.", "反対に、その商品の価格は下がりました。"],
    ["sedangkan", "一方で", "whereas", "接続詞", "Saya bekerja, sedangkan adik saya belajar.", "私は働いていますが、一方で弟は勉強しています。"],
    ["sementara itu", "一方、その間に", "meanwhile", "接続詞", "Sementara itu, warga menunggu bantuan.", "その間、住民は支援を待っていました。"],
    ["dengan demikian", "したがって", "therefore", "接続詞", "Dengan demikian, masalah itu selesai.", "したがって、その問題は解決しました。"],
    ["akibatnya", "その結果", "as a result", "接続詞", "Akibatnya, perjalanan menjadi lambat.", "その結果、移動は遅くなりました。"],
    ["oleh sebab itu", "そのため", "therefore", "接続詞", "Oleh sebab itu, jadwal diubah.", "そのため、予定が変更されました。"],
    ["namun demikian", "とはいえ", "nevertheless", "接続詞", "Namun demikian, pekerjaan tetap dilanjutkan.", "とはいえ、仕事は続けられました。"],
    ["meski begitu", "それでも", "even so", "接続詞", "Meski begitu, dia tetap datang.", "それでも、彼は来ました。"],
    ["seandainya", "もし〜ならば", "if; supposing", "接続詞", "Seandainya ada waktu, saya akan membantu.", "もし時間があれば、私は手伝います。"],
    ["asalkan", "〜しさえすれば", "as long as", "接続詞", "Anda boleh masuk asalkan membawa kartu.", "カードを持っていれば入れます。"],
    ["kecuali", "〜を除いて", "except", "接続詞", "Semua hadir kecuali Pak Budi.", "ブディさんを除いて全員出席しました。"],
    ["lagi pula", "そのうえ", "besides", "接続詞", "Lagi pula, tempat itu jauh.", "そのうえ、その場所は遠いです。"],
    ["justru", "むしろ、かえって", "instead; precisely", "副詞", "Dia justru merasa senang.", "彼はむしろうれしく感じました。"],
    ["terutama", "特に", "especially", "副詞", "Saya suka buah, terutama mangga.", "私は果物、特にマンゴーが好きです。"],
    ["khususnya", "特に", "particularly", "副詞", "Program itu penting, khususnya bagi anak-anak.", "そのプログラムは特に子どもたちにとって重要です。"],
    ["umumnya", "一般に", "generally", "副詞", "Umumnya, toko buka pukul sembilan.", "一般に、店は9時に開きます。"],
    ["sebagian besar", "大部分", "most", "副詞", "Sebagian besar peserta sudah hadir.", "参加者の大部分はすでに出席しています。"],
    ["setidaknya", "少なくとも", "at least", "副詞", "Setidaknya kita perlu dua hari.", "少なくとも私たちは2日必要です。"],
    ["sekurang-kurangnya", "少なくとも", "at least", "副詞", "Biaya itu sekurang-kurangnya seratus ribu rupiah.", "その費用は少なくとも10万ルピアです。"],
    ["berturut-turut", "連続して", "consecutively", "副詞", "Dia menang tiga kali berturut-turut.", "彼は3回連続で勝ちました。"],
    ["secara umum", "一般的に", "in general", "副詞", "Secara umum, hasilnya baik.", "一般的に、結果は良いです。"],
    ["secara langsung", "直接に", "directly", "副詞", "Saya berbicara secara langsung dengan manajer.", "私はマネージャーと直接話しました。"],
    ["secara tidak langsung", "間接的に", "indirectly", "副詞", "Hal itu memengaruhi kami secara tidak langsung.", "それは私たちに間接的に影響しました。"],
    ["secara bertahap", "段階的に", "gradually", "副詞", "Harga akan naik secara bertahap.", "価格は段階的に上がるでしょう。"],
    ["secara resmi", "公式に", "officially", "副詞", "Hasil ujian diumumkan secara resmi.", "試験結果は公式に発表されました。"],
    ["mendadak", "突然", "suddenly", "副詞", "Rapat itu dibatalkan mendadak.", "その会議は突然中止されました。"],
    ["rupanya", "どうやら", "apparently", "副詞", "Rupanya dia belum tahu.", "どうやら彼はまだ知りません。"],
    ["tampaknya", "〜のようだ", "apparently; seemingly", "副詞", "Tampaknya cuaca akan membaik.", "天気は良くなりそうです。"],
    ["sebaik-baiknya", "できるだけよく", "as well as possible", "副詞", "Kami bekerja sebaik-baiknya.", "私たちはできるだけよく働きます。"],
    ["secepatnya", "できるだけ早く", "as soon as possible", "副詞", "Tolong hubungi saya secepatnya.", "できるだけ早く私に連絡してください。"],
    ["selambat-lambatnya", "遅くとも", "at the latest", "副詞", "Kirim laporan selambat-lambatnya hari Jumat.", "遅くとも金曜日に報告書を送ってください。"],
    ["dalam rangka", "〜の一環として", "in the framework of", "前置詞", "Acara ini diadakan dalam rangka hari kemerdekaan.", "この行事は独立記念日の一環として開催されます。"],
    ["berdasarkan", "〜に基づいて", "based on", "前置詞", "Keputusan dibuat berdasarkan data.", "決定はデータに基づいて行われました。"],
    ["menurut", "〜によると", "according to", "前置詞", "Menurut laporan itu, harga naik.", "その報告によると、価格は上がりました。"],
    ["terhadap", "〜に対して", "toward; against", "前置詞", "Warga memberi tanggapan terhadap kebijakan itu.", "住民はその政策に対して反応を示しました。"],
    ["mengenai", "〜について", "regarding", "前置詞", "Kami berdiskusi mengenai jadwal baru.", "私たちは新しい予定について議論しました。"],
    ["sehubungan dengan", "〜に関連して", "in connection with", "前置詞", "Sehubungan dengan rapat, kantor tutup lebih awal.", "会議に関連して、会社は早く閉まります。"],
    ["termasuk", "〜を含めて", "including", "前置詞", "Biaya itu termasuk makan siang.", "その費用には昼食が含まれます。"],
    ["dibandingkan dengan", "〜と比べて", "compared with", "前置詞", "Harga ini murah dibandingkan dengan toko lain.", "この価格は他の店と比べて安いです。"],
    ["tergantung pada", "〜次第である", "depending on", "前置詞", "Hasilnya tergantung pada usaha kita.", "結果は私たちの努力次第です。"],
    ["berkaitan dengan", "〜に関係している", "related to", "前置詞", "Masalah itu berkaitan dengan transportasi.", "その問題は交通に関係しています。"],
    ["demi", "〜のために", "for the sake of", "前置詞", "Mereka bekerja demi keluarga.", "彼らは家族のために働きます。"],
    ["guna", "〜のために", "in order to", "前置詞", "Kami menabung guna membeli rumah.", "私たちは家を買うために貯金します。"]
  ];

  directRows.forEach(([word, japanese, english, partOfSpeech, example, exampleJapanese]) => {
    addCard({
      word,
      japanese,
      english,
      partOfSpeech,
      example,
      exampleJapanese,
      note: "C級で読解や作文に役立つ接続表現・機能語。"
    });
  });

  const simpleRows = [
    ["peraturan", "規則", "regulation", "名詞"], ["ketentuan", "規定", "provision; rule", "名詞"], ["kebijakan", "政策、方針", "policy", "名詞"],
    ["kegiatan", "活動", "activity", "名詞"], ["peristiwa", "出来事", "event", "名詞"], ["kejadian", "出来事、事件", "incident", "名詞"],
    ["kecelakaan", "事故", "accident", "名詞"], ["kerusakan", "損傷、故障", "damage", "名詞"], ["perbaikan", "修理、改善", "repair; improvement", "名詞"],
    ["penundaan", "延期", "delay; postponement", "名詞"], ["pembatalan", "中止、取り消し", "cancellation", "名詞"], ["pemberitahuan", "通知", "notification", "名詞"],
    ["pengumuman", "発表、お知らせ", "announcement", "名詞"], ["pernyataan", "声明、発言", "statement", "名詞"], ["tanggapan", "反応、返答", "response", "名詞"],
    ["kesimpulan", "結論", "conclusion", "名詞"], ["ringkasan", "要約", "summary", "名詞"], ["uraian", "説明、記述", "description", "名詞"],
    ["rincian", "詳細", "details", "名詞"], ["bukti", "証拠", "evidence", "名詞"], ["saksi", "証人", "witness", "名詞"], ["korban", "被害者", "victim", "名詞"],
    ["pelaku", "加害者、実行者", "perpetrator; actor", "名詞"], ["petugas", "係員", "officer; staff", "名詞"], ["pemilik", "所有者", "owner", "名詞"],
    ["penyewa", "借り主", "tenant; renter", "名詞"], ["pengunjung", "訪問者", "visitor", "名詞"], ["wisatawan", "観光客", "tourist", "名詞"],
    ["penduduk", "住民", "resident; population", "名詞"], ["warga", "住民、市民", "citizen; resident", "名詞"], ["komunitas", "共同体", "community", "名詞"],
    ["kelompok", "グループ", "group", "名詞"], ["organisasi", "組織", "organization", "名詞"], ["lembaga", "機関", "institution", "名詞"],
    ["perusahaan", "会社", "company", "名詞"], ["cabang", "支店", "branch", "名詞"], ["kantor pusat", "本社", "head office", "名詞句"],
    ["manajer", "管理者、マネージャー", "manager", "名詞"], ["atasan", "上司", "superior", "名詞"], ["bawahan", "部下", "subordinate", "名詞"],
    ["rekan kerja", "同僚", "coworker", "名詞句"], ["tenaga kerja", "労働力、労働者", "workforce", "名詞句"], ["lowongan", "求人、空き", "vacancy", "名詞"],
    ["lamaran", "応募", "application", "名詞"], ["wawancara", "面接", "interview", "名詞"], ["gaji", "給料", "salary", "名詞"], ["upah", "賃金", "wage", "名詞"],
    ["tunjangan", "手当", "allowance", "名詞"], ["cuti", "休暇", "leave", "名詞"], ["izin kerja", "就労許可", "work permit", "名詞句"],
    ["kontrak", "契約", "contract", "名詞"], ["perjanjian", "契約、合意", "agreement", "名詞"], ["tanggung jawab", "責任", "responsibility", "名詞句"],
    ["kewajiban", "義務", "obligation", "名詞"], ["hak", "権利", "right", "名詞"], ["keuntungan", "利益、利点", "benefit; profit", "名詞"],
    ["kerugian", "損失、損害", "loss", "名詞"], ["pendapatan", "収入", "income", "名詞"], ["pengeluaran", "支出", "expenditure", "名詞"],
    ["anggaran", "予算", "budget", "名詞"], ["modal", "資本", "capital", "名詞"], ["pinjaman", "融資、借金", "loan", "名詞"], ["tabungan", "貯金", "savings", "名詞"],
    ["pajak", "税金", "tax", "名詞"], ["bea cukai", "税関", "customs", "名詞句"], ["ekspor", "輸出", "export", "名詞"], ["impor", "輸入", "import", "名詞"],
    ["permintaan", "需要、依頼", "demand; request", "名詞"], ["penawaran", "供給、提案", "supply; offer", "名詞"], ["persediaan", "在庫", "stock; supply", "名詞"],
    ["kebutuhan pokok", "生活必需品", "basic necessities", "名詞句"], ["harga pokok", "原価", "basic cost", "名詞句"], ["kenaikan harga", "値上がり", "price increase", "名詞句"],
    ["penurunan harga", "値下がり", "price decrease", "名詞句"], ["lapangan kerja", "雇用機会", "job opportunity", "名詞句"], ["tingkat pengangguran", "失業率", "unemployment rate", "名詞句"],
    ["kemiskinan", "貧困", "poverty", "名詞"], ["kesejahteraan", "福祉、豊かさ", "welfare", "名詞"], ["bencana", "災害", "disaster", "名詞"],
    ["gempa bumi", "地震", "earthquake", "名詞句"], ["tanah longsor", "土砂崩れ", "landslide", "名詞句"], ["letusan gunung", "火山噴火", "volcanic eruption", "名詞句"],
    ["kebakaran", "火災", "fire", "名詞"], ["kekeringan", "干ばつ", "drought", "名詞"], ["pengungsian", "避難", "evacuation", "名詞"],
    ["pengungsi", "避難民", "evacuee; refugee", "名詞"], ["bantuan darurat", "緊急支援", "emergency aid", "名詞句"], ["posko", "対策本部、臨時拠点", "command post", "名詞"],
    ["lingkungan", "環境", "environment", "名詞"], ["sampah plastik", "プラスチックごみ", "plastic waste", "名詞句"], ["limbah", "廃棄物", "waste", "名詞"],
    ["daur ulang", "リサイクル", "recycling", "名詞句"], ["penghematan", "節約", "saving", "名詞"], ["energi", "エネルギー", "energy", "名詞"],
    ["listrik", "電気", "electricity", "名詞"], ["sumber daya", "資源", "resource", "名詞句"], ["air bersih", "清潔な水", "clean water", "名詞句"],
    ["saluran air", "排水路、水路", "water channel", "名詞句"], ["fasilitas umum", "公共施設", "public facility", "名詞句"], ["angkutan umum", "公共交通", "public transportation", "名詞句"],
    ["kemacetan lalu lintas", "交通渋滞", "traffic congestion", "名詞句"], ["kecelakaan lalu lintas", "交通事故", "traffic accident", "名詞句"],
    ["jalur", "路線、車線", "lane; route", "名詞"], ["rute", "ルート", "route", "名詞"], ["tujuan akhir", "最終目的地", "final destination", "名詞句"],
    ["peron", "ホーム", "platform", "名詞"], ["gerbong", "車両", "train car", "名詞"], ["kursi kosong", "空席", "empty seat", "名詞句"],
    ["keterlambatan", "遅延", "delay", "名詞"],
    ["pembayaran tunai", "現金払い", "cash payment", "名詞句"], ["pembayaran elektronik", "電子決済", "electronic payment", "名詞句"],
    ["saldo", "残高", "balance", "名詞"], ["rekening", "口座", "bank account", "名詞"], ["transfer", "振込", "transfer", "名詞"],
    ["bukti pembayaran", "支払い証明", "proof of payment", "名詞句"], ["layanan pelanggan", "顧客サービス", "customer service", "名詞句"],
    ["keluhan", "苦情", "complaint", "名詞"], ["solusi", "解決策", "solution", "名詞"],
    ["kesalahan teknis", "技術的な不具合", "technical error", "名詞句"], ["jaringan", "ネットワーク", "network", "名詞"], ["sinyal", "信号、電波", "signal", "名詞"],
    ["kata sandi", "パスワード", "password", "名詞句"], ["akun", "アカウント", "account", "名詞"], ["pengguna", "利用者", "user", "名詞"],
    ["keamanan data", "データ安全性", "data security", "名詞句"], ["informasi pribadi", "個人情報", "personal information", "名詞句"],
    ["laman web", "ウェブページ", "web page", "名詞句"], ["tautan", "リンク", "link", "名詞"], ["unggahan", "投稿、アップロード", "upload", "名詞"],
    ["unduhan", "ダウンロード", "download", "名詞"], ["lampiran", "添付", "attachment", "名詞"], ["berkas", "ファイル", "file", "名詞"],
    ["sertifikat", "証明書", "certificate", "名詞"], ["surat keterangan", "証明書", "certificate letter", "名詞句"],
    ["surat izin", "許可証", "permit letter", "名詞句"], ["surat lamaran", "応募書類", "application letter", "名詞句"],
    ["riwayat hidup", "履歴書", "curriculum vitae", "名詞句"], ["pengalaman kerja", "職務経験", "work experience", "名詞句"],
    ["keterampilan", "技能", "skill", "名詞"], ["kemampuan", "能力", "ability", "名詞"], ["kelebihan", "長所、余剰", "strength; excess", "名詞"],
    ["kekurangan", "短所、不足", "weakness; shortage", "名詞"], ["kesulitan", "困難", "difficulty", "名詞"], ["kemudahan", "便利さ、容易さ", "ease", "名詞"],
    ["kesempatan kerja", "就職機会", "employment opportunity", "名詞句"], ["pendidikan dasar", "基礎教育", "basic education", "名詞句"],
    ["pendidikan tinggi", "高等教育", "higher education", "名詞句"], ["biaya pendidikan", "教育費", "education cost", "名詞句"],
    ["beasiswa", "奨学金", "scholarship", "名詞"], ["lulusan", "卒業生", "graduate", "名詞"], ["ijazah", "卒業証書", "diploma", "名詞"],
    ["nilai rata-rata", "平均点", "average score", "名詞句"], ["mata pelajaran", "科目", "school subject", "名詞句"], ["jadwal pelajaran", "時間割", "class schedule", "名詞句"],
    ["absensi", "出欠", "attendance", "名詞"], ["kehadiran", "出席", "attendance; presence", "名詞"], ["ketidakhadiran", "欠席", "absence", "名詞"],
    ["pelanggaran", "違反", "violation", "名詞"], ["hukuman", "罰", "punishment", "名詞"], ["penghargaan", "表彰、評価", "award; appreciation", "名詞"],
    ["prestasi", "成果、成績", "achievement", "名詞"], ["perlombaan", "競技、コンテスト", "competition", "名詞"], ["peserta", "参加者", "participant", "名詞"],
    ["pemenang", "勝者", "winner", "名詞"], ["kekalahan", "敗北", "defeat", "名詞"], ["kemenangan", "勝利", "victory", "名詞"],
    ["kemampuan berbahasa", "語学力", "language ability", "名詞句"], ["percakapan sehari-hari", "日常会話", "daily conversation", "名詞句"],
    ["bahasa resmi", "公用語", "official language", "名詞句"], ["bahasa daerah", "地方語", "regional language", "名詞句"],
    ["terjemahan lisan", "通訳", "oral translation", "名詞句"], ["terjemahan tertulis", "翻訳文", "written translation", "名詞句"],
    ["budaya lokal", "地域文化", "local culture", "名詞句"], ["adat istiadat", "慣習", "customs", "名詞句"], ["upacara adat", "伝統儀式", "traditional ceremony", "名詞句"],
    ["hari libur nasional", "国民の祝日", "national holiday", "名詞句"], ["perayaan", "祝賀、祭り", "celebration", "名詞"],
    ["kesenian", "芸術", "arts", "名詞"], ["tarian", "踊り", "dance", "名詞"], ["alat musik", "楽器", "musical instrument", "名詞句"],
    ["kerajinan tangan", "手工芸品", "handicraft", "名詞句"], ["pameran", "展示会", "exhibition", "名詞"], ["pertunjukan", "公演", "performance", "名詞"],
    ["tiket masuk", "入場券", "entrance ticket", "名詞句"], ["jam buka", "営業時間", "opening hours", "名詞句"], ["jam tutup", "閉店時間", "closing time", "名詞句"],
    ["petunjuk arah", "道案内", "directions", "名詞句"], ["peta lokasi", "場所の地図", "location map", "名詞句"], ["tempat parkir", "駐車場", "parking area", "名詞句"],
    ["biaya masuk", "入場料", "entrance fee", "名詞句"], ["diskon khusus", "特別割引", "special discount", "名詞句"], ["harga satuan", "単価", "unit price", "名詞句"],
    ["harga grosir", "卸売価格", "wholesale price", "名詞句"], ["barang bekas", "中古品", "used goods", "名詞句"], ["barang baru", "新品", "new goods", "名詞句"],
    ["garansi", "保証", "warranty", "名詞"], ["mutu", "品質", "quality", "名詞"], ["ukuran sedang", "中サイズ", "medium size", "名詞句"],
    ["ukuran besar", "大サイズ", "large size", "名詞句"], ["ukuran kecil", "小サイズ", "small size", "名詞句"],
    ["sedang", "中くらいの、〜している", "medium; currently", "形容詞"], ["terbatas", "限られた", "limited", "形容詞"], ["tersedia", "利用可能な、在庫がある", "available", "形容詞"],
    ["teratur", "規則正しい", "regular; orderly", "形容詞"], ["permanen", "恒久的な", "permanent", "形容詞"],
    ["resmi", "公式の", "official", "形容詞"], ["tidak resmi", "非公式の", "unofficial", "形容詞"], ["wajib", "必須の", "mandatory", "形容詞"],
    ["sukarela", "任意の、自発的な", "voluntary", "形容詞"], ["adil", "公平な", "fair", "形容詞"], ["setara", "同等の", "equal", "形容詞"],
    ["tepat", "正確な、適切な", "exact; appropriate", "形容詞"], ["kurang tepat", "あまり適切でない", "less appropriate", "形容詞"], ["efektif", "効果的な", "effective", "形容詞"],
    ["efisien", "効率的な", "efficient", "形容詞"], ["praktis", "実用的な", "practical", "形容詞"], ["rumit", "複雑な", "complicated", "形容詞"],
    ["sah", "合法の、有効な", "valid; legal", "形容詞"], ["palsu", "偽物の", "fake", "形容詞"], ["lengket", "粘着性のある", "sticky", "形容詞"],
    ["rapuh", "壊れやすい", "fragile", "形容詞"], ["tahan lama", "長持ちする", "durable", "形容詞"], ["terpercaya", "信頼できる", "trustworthy", "形容詞"],
    ["memadai", "十分な", "adequate", "形容詞"], ["terjangkau", "手頃な", "affordable", "形容詞"], ["mendesak", "緊急の", "urgent", "形容詞"],
    ["terkini", "最新の", "latest", "形容詞"], ["terbaru", "最新の", "newest", "形容詞"], ["terdahulu", "以前の", "previous", "形容詞"],
    ["kedaluwarsa", "期限切れの", "expired", "形容詞"], ["ramah lingkungan", "環境にやさしい", "environmentally friendly", "形容詞"],
    ["hemat energi", "省エネルギーの", "energy-saving", "形容詞"], ["berisiko", "リスクがある", "risky", "形容詞"], ["bermanfaat", "役に立つ", "beneficial", "形容詞"]
  ];

  simpleRows.forEach(([word, japanese, english, partOfSpeech]) => {
    const example = partOfSpeech === "形容詞"
      ? `Hal itu ${word}.`
      : `Kami membahas ${word} itu.`;
    const exampleJapanese = partOfSpeech === "形容詞"
      ? `それは${jpMain(japanese)}ものです。`
      : `私たちはその${jpMain(japanese)}について話し合います。`;

    addCard({
      word,
      japanese,
      english,
      partOfSpeech,
      example,
      exampleJapanese,
      note: "C級で読解・作文に役立つ社会、仕事、生活関連の語彙。"
    });
  });

  // C級の語彙を増やすための追加リスト。全行に手書きの例文を付ける。
  // [word, japanese, english, partOfSpeech, example, exampleJapanese]
  const additionalRows = [
    // --- 動詞 ---
    ["membuat", "作る", "to make", "動詞", "Ibu membuat kue untuk tamu.", "母は客のためにお菓子を作ります。"],
    ["menjadi", "〜になる", "to become", "動詞", "Dia menjadi guru tahun lalu.", "彼は去年先生になりました。"],
    ["memiliki", "所有する、持つ", "to have; own", "動詞", "Keluarga itu memiliki dua mobil.", "その家族は車を2台持っています。"],
    ["mempunyai", "持つ", "to have", "動詞", "Saya mempunyai banyak teman di Indonesia.", "私はインドネシアにたくさんの友だちがいます。"],
    ["mengatakan", "言う", "to say", "動詞", "Dia mengatakan hal itu kepada saya.", "彼はそのことを私に言いました。"],
    ["berkata", "言う", "to say", "動詞", "Dia berkata dengan jujur.", "彼は正直に言いました。"],
    ["menceritakan", "語る、話して聞かせる", "to tell", "動詞", "Kakek menceritakan pengalamannya.", "祖父は自分の経験を語ります。"],
    ["menyatakan", "述べる、表明する", "to state", "動詞", "Pemerintah menyatakan daerah itu aman.", "政府はその地域が安全だと表明します。"],
    ["menganggap", "見なす、思う", "to consider", "動詞", "Saya menganggap hal itu penting.", "私はそのことを重要だと考えます。"],
    ["merasa", "感じる、思う", "to feel", "動詞", "Saya merasa lelah hari ini.", "私は今日疲れを感じます。"],
    ["berpendapat", "意見を持つ、考える", "to be of the opinion", "動詞", "Saya berpendapat bahwa rencana itu baik.", "私はその計画は良いと考えます。"],
    ["menyarankan", "勧める、提案する", "to suggest", "動詞", "Dokter menyarankan saya berolahraga.", "医者は私に運動するよう勧めます。"],
    ["menganjurkan", "勧める", "to recommend", "動詞", "Guru menganjurkan kami membaca buku ini.", "先生は私たちにこの本を読むよう勧めます。"],
    ["mengizinkan", "許可する", "to permit", "動詞", "Ayah mengizinkan saya pergi.", "父は私が行くのを許可します。"],
    ["melarang", "禁止する", "to forbid", "動詞", "Sekolah melarang siswa membawa ponsel.", "学校は生徒が携帯電話を持ち込むのを禁止しています。"],
    ["mewajibkan", "義務づける", "to require", "動詞", "Peraturan mewajibkan penggunaan helm.", "規則はヘルメットの使用を義務づけています。"],
    ["membiarkan", "放っておく、〜させておく", "to let; leave", "動詞", "Jangan membiarkan pintu terbuka.", "ドアを開けたままにしないでください。"],
    ["menghargai", "尊重する、評価する", "to appreciate", "動詞", "Kita harus menghargai pendapat orang lain.", "私たちは他人の意見を尊重しなければなりません。"],
    ["menghormati", "尊敬する", "to respect", "動詞", "Murid menghormati gurunya.", "生徒は先生を尊敬します。"],
    ["memuji", "ほめる", "to praise", "動詞", "Guru memuji hasil kerja siswa.", "先生は生徒の成果をほめます。"],
    ["mengkritik", "批判する", "to criticize", "動詞", "Warga mengkritik kebijakan baru itu.", "住民はその新しい政策を批判します。"],
    ["menyalahkan", "責める", "to blame", "動詞", "Jangan menyalahkan orang lain.", "他人を責めないでください。"],
    ["membela", "擁護する、守る", "to defend", "動詞", "Pengacara membela kliennya.", "弁護士は依頼人を擁護します。"],
    ["menipu", "だます", "to deceive", "動詞", "Penjual itu menipu pembeli.", "その売り手は買い手をだましました。"],
    ["mencuri", "盗む", "to steal", "動詞", "Seseorang mencuri sepeda saya.", "誰かが私の自転車を盗みました。"],
    ["menangkap", "捕まえる", "to catch", "動詞", "Polisi menangkap pelaku pencurian.", "警察は窃盗の犯人を捕まえました。"],
    ["melapor", "届け出る、報告する", "to report", "動詞", "Saya melapor kepada polisi.", "私は警察に届け出ます。"],
    ["terjadi", "起こる", "to happen", "動詞", "Kecelakaan terjadi tadi pagi.", "事故は今朝起きました。"],
    ["berlangsung", "行われる、続く", "to take place", "動詞", "Acara itu berlangsung selama dua jam.", "その行事は2時間行われました。"],
    ["menyelenggarakan", "開催する", "to organize", "動詞", "Kota itu menyelenggarakan festival budaya.", "その都市は文化祭を開催します。"],
    ["berkembang", "発展する", "to develop", "動詞", "Kota ini berkembang dengan cepat.", "この町は速く発展しています。"],
    ["tumbuh", "育つ、成長する", "to grow", "動詞", "Pohon itu tumbuh tinggi.", "その木は高く育ちます。"],
    ["meningkat", "増加する、上がる", "to increase", "動詞", "Jumlah wisatawan meningkat tahun ini.", "今年、観光客数は増えています。"],
    ["menurun", "減少する、下がる", "to decrease", "動詞", "Penjualan menurun bulan lalu.", "先月、販売は減少しました。"],
    ["mencapai", "達する、達成する", "to reach", "動詞", "Suhu mencapai 35 derajat.", "気温は35度に達します。"],
    ["meraih", "獲得する", "to achieve", "動詞", "Tim itu meraih juara pertama.", "そのチームは優勝を獲得しました。"],
    ["berusaha", "努力する", "to try; strive", "動詞", "Saya berusaha datang tepat waktu.", "私は時間どおりに来るよう努力します。"],
    ["berjuang", "奮闘する", "to struggle", "動詞", "Mereka berjuang melawan kemiskinan.", "彼らは貧困と闘っています。"],
    ["bertahan", "持ちこたえる", "to survive; endure", "動詞", "Toko kecil itu bertahan selama ini.", "その小さな店はこれまで持ちこたえてきました。"],
    ["menghadapi", "直面する", "to face", "動詞", "Kami menghadapi masalah baru.", "私たちは新しい問題に直面しています。"],
    ["mengalami", "経験する、遭う", "to experience", "動詞", "Daerah itu mengalami banjir.", "その地域は洪水に見舞われました。"],
    ["mengatasi", "克服する、対処する", "to overcome", "動詞", "Pemerintah berusaha mengatasi kemacetan.", "政府は渋滞の解消に努めています。"],
    ["menyadari", "気づく、自覚する", "to realize", "動詞", "Saya menyadari kesalahan saya.", "私は自分の間違いに気づきます。"],
    ["menduga", "推測する", "to suspect", "動詞", "Polisi menduga ada masalah lain.", "警察は他に問題があると推測します。"],
    ["menebak", "当てる、推測する", "to guess", "動詞", "Dia menebak jawabannya dengan benar.", "彼は答えを正しく当てました。"],
    ["memperkirakan", "予測する、見積もる", "to estimate", "動詞", "Ahli memperkirakan harga akan naik.", "専門家は価格が上がると予測します。"],
    ["membuktikan", "証明する", "to prove", "動詞", "Data itu membuktikan pendapatnya.", "そのデータは彼の意見を証明します。"],
    ["meyakinkan", "納得させる", "to convince", "動詞", "Dia meyakinkan orang tuanya.", "彼は両親を納得させます。"],
    ["menepati", "(約束を)守る", "to keep (a promise)", "動詞", "Dia selalu menepati janji.", "彼はいつも約束を守ります。"],
    ["melanggar", "違反する", "to violate", "動詞", "Pengemudi itu melanggar aturan lalu lintas.", "その運転者は交通規則に違反しました。"],
    ["mematuhi", "遵守する、従う", "to obey", "動詞", "Semua orang harus mematuhi hukum.", "すべての人は法律を守らなければなりません。"],
    ["mengeluh", "不平を言う", "to complain", "動詞", "Pelanggan mengeluh tentang layanan.", "客はサービスについて不平を言います。"],
    ["memprotes", "抗議する", "to protest", "動詞", "Warga memprotes rencana itu.", "住民はその計画に抗議します。"],
    ["menuntut", "要求する", "to demand", "動詞", "Pekerja menuntut kenaikan gaji.", "労働者は昇給を要求します。"],
    ["mengajukan", "申請する、提出する", "to submit; apply", "動詞", "Saya mengajukan permohonan visa.", "私はビザの申請を出します。"],
    ["menyerahkan", "提出する、引き渡す", "to hand over", "動詞", "Siswa menyerahkan tugas kepada guru.", "生徒は課題を先生に提出します。"],
    ["menerbitkan", "出版する、発行する", "to publish", "動詞", "Penerbit itu menerbitkan kamus baru.", "その出版社は新しい辞書を出版します。"],
    ["menghapus", "消す、削除する", "to delete; erase", "動詞", "Saya menghapus pesan itu.", "私はそのメッセージを削除します。"],
    ["mengetik", "入力する、タイプする", "to type", "動詞", "Dia mengetik laporan di komputer.", "彼はコンピューターで報告書を打ちます。"],
    ["mengunduh", "ダウンロードする", "to download", "動詞", "Saya mengunduh aplikasi baru.", "私は新しいアプリをダウンロードします。"],
    ["mengunggah", "アップロードする", "to upload", "動詞", "Dia mengunggah foto ke media sosial.", "彼はSNSに写真をアップロードします。"],
    ["memasang", "取り付ける、設置する", "to install", "動詞", "Petugas memasang lampu baru.", "係員は新しい電灯を取り付けます。"],
    ["mencabut", "引き抜く、取り消す", "to pull out; revoke", "動詞", "Pemerintah mencabut izin itu.", "政府はその許可を取り消しました。"],
    ["menempelkan", "貼る", "to stick; paste", "動詞", "Dia menempelkan pengumuman di dinding.", "彼は壁にお知らせを貼ります。"],
    ["melipat", "たたむ、折る", "to fold", "動詞", "Saya melipat pakaian.", "私は服をたたみます。"],
    ["menggantung", "つるす、掛ける", "to hang", "動詞", "Ibu menggantung baju di belakang pintu.", "母はドアの後ろに服を掛けます。"],
    ["menjatuhkan", "落とす", "to drop", "動詞", "Saya menjatuhkan kunci di jalan.", "私は道で鍵を落としました。"],
    ["menumpahkan", "こぼす", "to spill", "動詞", "Anak itu menumpahkan susu.", "その子は牛乳をこぼしました。"],
    ["memecahkan", "割る、解決する", "to break; solve", "動詞", "Kami memecahkan masalah itu bersama.", "私たちはその問題を一緒に解決します。"],
    ["pecah", "割れる", "to break", "動詞", "Gelas itu pecah.", "そのコップは割れました。"],
    ["bocor", "漏れる", "to leak", "動詞", "Atap rumah kami bocor.", "私たちの家の屋根は雨漏りします。"],
    ["macet", "渋滞する、動かない", "to be stuck; jammed", "動詞", "Jalan ini selalu macet pagi hari.", "この道は朝いつも渋滞します。"],
    ["hilang", "なくなる", "to be lost", "動詞", "Dompet saya hilang.", "私の財布がなくなりました。"],
    ["mati", "死ぬ、(電気などが)消える", "to die; be off", "動詞", "Lampu mati karena hujan.", "雨のため電気が消えました。"],
    ["hidup", "生きる、暮らす", "to live", "動詞", "Mereka hidup sederhana.", "彼らは質素に暮らしています。"],
    ["mogok", "故障する、ストライキする", "to break down; strike", "動詞", "Mobil kami mogok di jalan.", "私たちの車は道で故障しました。"],
    ["menanam", "植える", "to plant", "動詞", "Petani menanam padi.", "農民は稲を植えます。"],
    ["memelihara", "飼う、育てる", "to keep; raise", "動詞", "Kami memelihara kucing.", "私たちは猫を飼っています。"],
    ["menggigit", "かむ", "to bite", "動詞", "Anjing itu tidak menggigit.", "その犬はかみません。"],
    ["berteriak", "叫ぶ", "to shout", "動詞", "Anak itu berteriak minta tolong.", "その子は助けを求めて叫びます。"],
    ["berbisik", "ささやく", "to whisper", "動詞", "Dia berbisik kepada temannya.", "彼は友だちにささやきます。"],
    ["mengobrol", "おしゃべりする", "to chat", "動詞", "Kami mengobrol di kafe.", "私たちはカフェでおしゃべりします。"],
    ["bercanda", "冗談を言う", "to joke", "動詞", "Dia suka bercanda.", "彼は冗談を言うのが好きです。"],
    ["menghibur", "楽しませる、慰める", "to entertain; comfort", "動詞", "Musik itu menghibur penonton.", "その音楽は観客を楽しませます。"],
    ["terpaksa", "やむを得ず〜する", "to be forced to", "動詞", "Saya terpaksa pulang lebih awal.", "私はやむを得ず早く帰りました。"],
    ["sempat", "〜する余裕がある、〜し得た", "to have time to", "動詞", "Saya tidak sempat sarapan.", "私は朝食をとる時間がありませんでした。"],
    ["berpartisipasi", "参加する", "to participate", "動詞", "Warga berpartisipasi dalam kegiatan itu.", "住民はその活動に参加します。"],
    ["terlibat", "関与する", "to be involved", "動詞", "Banyak pihak terlibat dalam proyek ini.", "多くの関係者がこの事業に関与しています。"],
    ["terletak", "位置する", "to be located", "動詞", "Kantor itu terletak di pusat kota.", "その事務所は市中心部に位置します。"],
    ["terdapat", "存在する、ある", "there is; to be found", "動詞", "Terdapat banyak museum di kota ini.", "この町には多くの博物館があります。"],
    ["terdiri dari", "〜から成る", "to consist of", "動詞", "Tim itu terdiri dari lima orang.", "そのチームは5人から成ります。"],
    ["berisi", "中身が〜である", "to contain", "動詞", "Kotak itu berisi buku.", "その箱には本が入っています。"],
    ["mengandung", "含む", "to contain", "動詞", "Makanan ini mengandung banyak gula.", "この食べ物は多くの砂糖を含みます。"],
    ["menuju", "〜へ向かう", "to head to", "動詞", "Bus ini menuju bandara.", "このバスは空港へ向かいます。"],
    ["melewati", "通過する", "to pass", "動詞", "Kereta melewati jembatan panjang.", "電車は長い橋を通過します。"],
    ["memasuki", "(〜に)入る", "to enter", "動詞", "Kami memasuki musim hujan.", "私たちは雨季に入ります。"],
    ["meninggalkan", "去る、置いて行く", "to leave", "動詞", "Dia meninggalkan kota itu tahun lalu.", "彼は去年その町を去りました。"],
    ["menabung", "貯金する", "to save money", "動詞", "Saya menabung untuk membeli rumah.", "私は家を買うために貯金します。"],
    ["menawarkan", "提供する、勧める", "to offer", "動詞", "Toko itu menawarkan diskon besar.", "その店は大きな割引を提供します。"],
    ["membalas", "返信する、返す", "to reply; return", "動詞", "Saya belum membalas email itu.", "私はまだそのメールに返信していません。"],
    ["berwisata", "観光する", "to travel; tour", "動詞", "Kami berwisata ke Yogyakarta.", "私たちはジョグジャカルタへ観光に行きます。"],
    ["muncul", "現れる", "to appear", "動詞", "Masalah baru muncul minggu ini.", "今週、新しい問題が現れました。"],
    ["menghilang", "消える、姿を消す", "to disappear", "動詞", "Kucing itu menghilang sejak kemarin.", "その猫は昨日から姿を消しています。"],
    ["melarikan diri", "逃げる", "to escape", "動詞", "Pelaku melarikan diri ke luar kota.", "犯人は町の外へ逃げました。"],
    // --- 形容詞 ---
    ["yakin", "確信している", "sure; convinced", "形容詞", "Saya yakin dia akan datang.", "私は彼が来ると確信しています。"],
    ["ragu-ragu", "ためらう、自信がない", "hesitant", "形容詞", "Jangan ragu-ragu untuk bertanya.", "質問するのをためらわないでください。"],
    ["bingung", "困惑した、わからない", "confused", "形容詞", "Saya bingung memilih yang mana.", "私はどれを選ぶか迷っています。"],
    ["kaget", "驚いた", "startled", "形容詞", "Saya kaget mendengar berita itu.", "私はその知らせを聞いて驚きました。"],
    ["kecewa", "がっかりした", "disappointed", "形容詞", "Dia kecewa dengan hasilnya.", "彼は結果にがっかりしています。"],
    ["puas", "満足した", "satisfied", "形容詞", "Pelanggan puas dengan layanan itu.", "客はそのサービスに満足しています。"],
    ["bosan", "飽きた、退屈した", "bored", "形容詞", "Saya bosan dengan menu yang sama.", "私は同じメニューに飽きました。"],
    ["lucu", "おかしい、かわいい", "funny; cute", "形容詞", "Cerita itu lucu sekali.", "その話はとてもおかしいです。"],
    ["aneh", "変な", "strange", "形容詞", "Suara mesin itu aneh.", "その機械の音は変です。"],
    ["wajar", "当然の、普通の", "natural; reasonable", "形容詞", "Reaksi itu wajar.", "その反応は当然です。"],
    ["umum", "一般的な", "general; public", "形容詞", "Hal itu sudah menjadi pengetahuan umum.", "それはもう一般常識になっています。"],
    ["khusus", "特別な", "special", "形容詞", "Ada menu khusus hari ini.", "今日は特別メニューがあります。"],
    ["utama", "主要な", "main", "形容詞", "Keselamatan adalah hal utama.", "安全が最も重要なことです。"],
    ["cerah", "晴れた", "sunny; bright", "形容詞", "Langit cerah pagi ini.", "今朝、空は晴れています。"],
    ["mendung", "曇った", "cloudy", "形容詞", "Langit mendung, mungkin akan hujan.", "空が曇っているので、雨が降るかもしれません。"],
    ["lembap", "湿った", "humid; damp", "形容詞", "Udara di sini lembap.", "ここの空気は湿っています。"],
    ["deras", "(雨が)激しい", "heavy (rain)", "形容詞", "Hujan deras turun sejak sore.", "夕方から激しい雨が降っています。"],
    ["kencang", "強い、速い", "strong; fast", "形容詞", "Angin bertiup kencang.", "風が強く吹いています。"],
    ["akrab", "親しい", "close; intimate", "形容詞", "Kami akrab sejak kecil.", "私たちは小さいころから親しいです。"],
    ["asing", "外国の、なじみのない", "foreign; unfamiliar", "形容詞", "Dia belajar bahasa asing.", "彼は外国語を学んでいます。"],
    ["mirip", "似ている", "similar", "形容詞", "Anak itu mirip ayahnya.", "その子は父親に似ています。"],
    ["persis", "ちょうど、そっくり", "exactly", "形容詞", "Rumahnya persis di depan stasiun.", "彼の家はちょうど駅の前にあります。"],
    ["cocok", "合う、ぴったりの", "suitable", "形容詞", "Baju ini cocok untuk Anda.", "この服はあなたに合います。"],
    ["sesuai", "適合した、〜に沿った", "in accordance with", "形容詞", "Hasilnya sesuai dengan harapan.", "結果は期待どおりです。"],
    ["layak", "ふさわしい、値する", "worthy; feasible", "形容詞", "Film itu layak ditonton.", "その映画は見る価値があります。"],
    ["mampu", "〜できる、力がある", "able; capable", "形容詞", "Dia mampu menyelesaikan tugas itu.", "彼はその課題をやり遂げることができます。"],
    ["sanggup", "〜する能力がある", "capable", "形容詞", "Saya sanggup bekerja sampai malam.", "私は夜まで働くことができます。"],
    ["berani", "勇敢な、思い切って〜する", "brave", "形容詞", "Anak itu berani berbicara di depan kelas.", "その子は教室の前で堂々と話せます。"],
    ["serius", "真剣な", "serious", "形容詞", "Dia serius dengan rencananya.", "彼は自分の計画に真剣です。"],
    ["santai", "のんびりした", "relaxed", "形容詞", "Kami menghabiskan akhir pekan dengan santai.", "私たちは週末をのんびり過ごします。"],
    ["sabar", "我慢強い", "patient", "形容詞", "Guru itu sabar kepada murid-muridnya.", "その先生は生徒たちに忍耐強いです。"],
    ["tegas", "断固とした、明確な", "firm; decisive", "形容詞", "Aturan itu harus tegas.", "規則は明確でなければなりません。"],
    ["pelit", "けちな", "stingy", "形容詞", "Dia terkenal pelit.", "彼はけちで有名です。"],
    ["boros", "浪費癖のある", "wasteful", "形容詞", "Jangan boros dengan uang.", "お金を浪費しないでください。"],
    ["hemat", "倹約的な", "thrifty", "形容詞", "Keluarga itu hidup hemat.", "その家族は倹約して暮らしています。"],
    ["mahir", "熟達した", "skilled", "形容詞", "Dia mahir berbahasa Inggris.", "彼は英語に熟達しています。"],
    ["lancar", "流暢な、順調な", "fluent; smooth", "形容詞", "Bahasa Indonesianya lancar.", "彼のインドネシア語は流暢です。"],
    ["fasih", "流暢な", "fluent", "形容詞", "Dia berbicara dengan fasih.", "彼は流暢に話します。"],
    ["pandai", "上手な、賢い", "clever; good at", "形容詞", "Anak itu pandai menggambar.", "その子は絵を描くのが上手です。"],
    ["sempurna", "完璧な", "perfect", "形容詞", "Persiapannya sempurna.", "準備は完璧です。"],
    ["sukses", "成功した", "successful", "形容詞", "Acara itu sukses besar.", "その行事は大成功でした。"],
    ["sehari-hari", "日常の", "daily; everyday", "形容詞", "Ini kegiatan sehari-hari saya.", "これは私の日課です。"],
    ["setempat", "現地の", "local", "形容詞", "Tanyakan kepada penduduk setempat.", "現地の住民に尋ねてください。"],
    ["berbagai", "さまざまな", "various", "形容詞", "Toko itu menjual berbagai barang.", "その店はさまざまな品物を売っています。"],
    ["beragam", "多様な", "diverse", "形容詞", "Budaya Indonesia sangat beragam.", "インドネシアの文化はとても多様です。"],
    ["seluruh", "全体の", "entire; whole", "形容詞", "Seluruh peserta sudah hadir.", "参加者全員がすでに出席しています。"],
    ["sejumlah", "一定数の、いくつかの", "a number of", "形容詞", "Sejumlah toko tutup hari ini.", "いくつかの店は今日閉まっています。"],
    // --- 名詞 ---
    ["hobi", "趣味", "hobby", "名詞", "Hobi saya membaca buku.", "私の趣味は読書です。"],
    ["olahraga", "スポーツ、運動", "sports; exercise", "名詞", "Olahraga baik untuk kesehatan.", "運動は健康に良いです。"],
    ["pertandingan", "試合", "match; game", "名詞", "Pertandingan dimulai jam empat.", "試合は4時に始まります。"],
    ["penonton", "観客", "audience; spectator", "名詞", "Penonton memenuhi stadion.", "観客がスタジアムを埋めます。"],
    ["pemain", "選手、演者", "player", "名詞", "Pemain itu masih muda.", "その選手はまだ若いです。"],
    ["juara", "優勝者、チャンピオン", "champion", "名詞", "Dia menjadi juara tahun ini.", "彼は今年優勝者になりました。"],
    ["lomba", "コンテスト、競争", "contest", "名詞", "Anak saya ikut lomba menggambar.", "私の子どもは絵のコンテストに参加します。"],
    ["hadiah", "プレゼント、賞", "gift; prize", "名詞", "Dia menerima hadiah ulang tahun.", "彼は誕生日プレゼントを受け取ります。"],
    ["tim", "チーム", "team", "名詞", "Tim kami menang kemarin.", "私たちのチームは昨日勝ちました。"],
    ["pernikahan", "結婚式、結婚", "wedding; marriage", "名詞", "Pernikahan mereka diadakan di Bali.", "彼らの結婚式はバリで行われます。"],
    ["kelahiran", "誕生", "birth", "名詞", "Kami merayakan kelahiran anak pertama.", "私たちは第一子の誕生を祝います。"],
    ["kematian", "死", "death", "名詞", "Semua orang sedih atas kematian itu.", "皆がその死を悲しんでいます。"],
    ["ulang tahun", "誕生日", "birthday", "名詞句", "Besok ulang tahun ibu saya.", "明日は私の母の誕生日です。"],
    ["penginapan", "宿泊施設", "lodging", "名詞", "Kami mencari penginapan murah.", "私たちは安い宿を探します。"],
    ["kantin", "食堂", "canteen", "名詞", "Siswa makan siang di kantin.", "生徒は食堂で昼食を食べます。"],
    ["asrama", "寮", "dormitory", "名詞", "Mahasiswa itu tinggal di asrama.", "その大学生は寮に住んでいます。"],
    ["kebersihan", "清潔さ、衛生", "cleanliness", "名詞", "Jaga kebersihan tempat ini.", "この場所の清潔さを保ってください。"],
    ["budaya", "文化", "culture", "名詞", "Saya tertarik pada budaya Indonesia.", "私はインドネシアの文化に興味があります。"],
    ["sejarah", "歴史", "history", "名詞", "Kota ini punya sejarah panjang.", "この町には長い歴史があります。"],
    ["cerita rakyat", "民話", "folk tale", "名詞句", "Cerita rakyat itu terkenal di Jawa.", "その民話はジャワで有名です。"],
    ["dongeng", "おとぎ話", "fairy tale", "名詞", "Ibu membacakan dongeng untuk anaknya.", "母は子どもにおとぎ話を読んで聞かせます。"],
    ["kata", "単語、言葉", "word", "名詞", "Kata ini sulit diucapkan.", "この単語は発音しにくいです。"],
    ["kosakata", "語彙", "vocabulary", "名詞", "Saya menghafal kosakata baru setiap hari.", "私は毎日新しい語彙を暗記します。"],
    ["ejaan", "綴り", "spelling", "名詞", "Periksa ejaan sebelum mengirim surat.", "手紙を送る前に綴りを確認してください。"],
    ["lafal", "発音", "pronunciation", "名詞", "Lafal kata ini sulit.", "この単語の発音は難しいです。"],
    ["tata bahasa", "文法", "grammar", "名詞句", "Tata bahasa Indonesia tidak terlalu rumit.", "インドネシア語の文法はそれほど複雑ではありません。"],
    ["makna", "意味", "meaning", "名詞", "Kata itu punya dua makna.", "その単語には2つの意味があります。"],
    ["istilah", "用語", "term", "名詞", "Istilah ini dipakai dalam ekonomi.", "この用語は経済で使われます。"],
    ["singkatan", "略語", "abbreviation", "名詞", "KTP adalah singkatan dari kartu tanda penduduk.", "KTPは住民身分証の略語です。"],
    ["ungkapan", "表現、慣用句", "expression", "名詞", "Ungkapan ini sering dipakai sehari-hari.", "この表現は日常でよく使われます。"],
    ["peribahasa", "ことわざ", "proverb", "名詞", "Peribahasa itu berasal dari bahasa Melayu.", "そのことわざはマレー語に由来します。"],
    ["percakapan", "会話", "conversation", "名詞", "Kami berlatih percakapan setiap minggu.", "私たちは毎週会話を練習します。"],
    ["pidato", "演説、スピーチ", "speech", "名詞", "Pidato presiden disiarkan langsung.", "大統領の演説は生中継されます。"],
    ["diskusi", "討論、話し合い", "discussion", "名詞", "Diskusi itu berlangsung dua jam.", "その討論は2時間続きました。"],
    ["seminar", "セミナー", "seminar", "名詞", "Saya mengikuti seminar bahasa.", "私は語学セミナーに参加します。"],
    ["kuliah", "講義、大学の授業", "university lecture", "名詞", "Kuliah dimulai bulan September.", "講義は9月に始まります。"],
    ["jurusan", "専攻", "major; department", "名詞", "Jurusan saya ekonomi.", "私の専攻は経済です。"],
    ["universitas", "大学", "university", "名詞", "Kakak saya belajar di universitas.", "私の兄は大学で学んでいます。"],
    ["gelar", "学位、称号", "degree; title", "名詞", "Dia mendapatkan gelar sarjana.", "彼は学士号を取得しました。"],
    ["penghasilan", "収入", "income", "名詞", "Penghasilannya cukup untuk keluarganya.", "彼の収入は家族を養うのに十分です。"],
    ["profesi", "職業", "profession", "名詞", "Profesi dokter membutuhkan waktu belajar lama.", "医者という職業は長い学習期間を必要とします。"],
    ["pekerjaan", "仕事、職", "job; work", "名詞", "Dia mencari pekerjaan baru.", "彼は新しい仕事を探しています。"],
    ["karier", "キャリア", "career", "名詞", "Dia memulai kariernya di Jakarta.", "彼はジャカルタでキャリアを始めました。"],
    ["pengusaha", "実業家、経営者", "entrepreneur", "名詞", "Pengusaha itu membuka pabrik baru.", "その実業家は新しい工場を開きます。"],
    ["pejabat", "役人、高官", "official", "名詞", "Pejabat itu menghadiri upacara.", "その役人は式典に出席します。"],
    ["menteri", "大臣", "minister", "名詞", "Menteri pendidikan mengunjungi sekolah itu.", "教育大臣はその学校を訪問します。"],
    ["presiden", "大統領", "president", "名詞", "Presiden memberikan pidato tahun baru.", "大統領は新年の演説を行います。"],
    ["gubernur", "知事", "governor", "名詞", "Gubernur meninjau lokasi banjir.", "知事は洪水の現場を視察します。"],
    ["kepala desa", "村長", "village head", "名詞句", "Kepala desa memimpin rapat warga.", "村長は住民会議を主宰します。"],
    ["pemilu", "総選挙", "general election", "名詞", "Pemilu diadakan lima tahun sekali.", "総選挙は5年に一度行われます。"],
    ["partai", "政党", "political party", "名詞", "Partai itu menang dalam pemilu.", "その政党は選挙で勝ちました。"],
    ["undang-undang", "法律", "law; act", "名詞", "Undang-undang baru mulai berlaku tahun ini.", "新しい法律は今年から施行されます。"],
    ["hukum", "法、法律", "law", "名詞", "Semua orang sama di depan hukum.", "すべての人は法の前で平等です。"],
    ["pengadilan", "裁判所", "court", "名詞", "Perkara itu dibawa ke pengadilan.", "その件は裁判所に持ち込まれました。"],
    ["hakim", "裁判官", "judge", "名詞", "Hakim membacakan keputusan.", "裁判官は判決を読み上げます。"],
    ["pengacara", "弁護士", "lawyer", "名詞", "Dia bekerja sebagai pengacara.", "彼は弁護士として働いています。"],
    ["penjara", "刑務所", "prison", "名詞", "Pelaku dihukum lima tahun penjara.", "犯人は懲役5年の刑を受けました。"],
    ["denda", "罰金", "fine", "名詞", "Dia membayar denda di kantor polisi.", "彼は警察署で罰金を払います。"],
    ["kejahatan", "犯罪", "crime", "名詞", "Kejahatan di kota itu menurun.", "その町の犯罪は減っています。"],
    ["pencurian", "窃盗", "theft", "名詞", "Pencurian itu terjadi malam hari.", "その窃盗は夜に起きました。"],
    ["penipuan", "詐欺", "fraud", "名詞", "Hati-hati terhadap penipuan lewat telepon.", "電話による詐欺に気をつけてください。"],
    ["keadilan", "正義、公正", "justice", "名詞", "Warga menuntut keadilan.", "住民は正義を求めます。"],
    ["kebebasan", "自由", "freedom", "名詞", "Kebebasan berpendapat dijamin undang-undang.", "意見表明の自由は法律で保障されています。"],
    ["kemerdekaan", "独立", "independence", "名詞", "Indonesia merayakan hari kemerdekaan pada bulan Agustus.", "インドネシアは8月に独立記念日を祝います。"],
    ["perdamaian", "平和", "peace", "名詞", "Kedua negara menjaga perdamaian.", "両国は平和を守ります。"],
    ["perang", "戦争", "war", "名詞", "Perang itu berakhir puluhan tahun lalu.", "その戦争は数十年前に終わりました。"],
    ["konflik", "対立、紛争", "conflict", "名詞", "Konflik itu diselesaikan lewat dialog.", "その対立は対話によって解決されました。"],
    ["perundingan", "交渉", "negotiation", "名詞", "Perundingan berjalan dengan lancar.", "交渉は順調に進みます。"],
    ["kesepakatan", "合意", "agreement", "名詞", "Kedua pihak mencapai kesepakatan.", "両者は合意に達しました。"],
    ["kerja sama", "協力", "cooperation", "名詞句", "Kerja sama kedua kota itu berjalan baik.", "両都市の協力は順調です。"],
    ["persahabatan", "友情", "friendship", "名詞", "Persahabatan kami sudah lama.", "私たちの友情は長く続いています。"],
    ["pertemuan", "会合", "meeting", "名詞", "Pertemuan itu diadakan di hotel.", "その会合はホテルで開かれます。"],
    ["kunjungan", "訪問", "visit", "名詞", "Kunjungan presiden berlangsung dua hari.", "大統領の訪問は2日間行われます。"],
    ["keberatan", "異議、差し支え", "objection", "名詞", "Kalau tidak ada keberatan, kita mulai sekarang.", "差し支えなければ、今始めましょう。"],
    ["prosedur", "手続き", "procedure", "名詞", "Ikuti prosedur pendaftaran dengan benar.", "登録手続きに正しく従ってください。"],
    ["tahap", "段階", "stage; phase", "名詞", "Proyek itu masuk tahap kedua.", "その事業は第2段階に入ります。"],
    ["tingkat", "レベル、程度", "level", "名詞", "Tingkat kesulitan ujian ini tinggi.", "この試験の難易度は高いです。"],
    ["jenis", "種類", "kind; type", "名詞", "Toko itu menjual banyak jenis kopi.", "その店は多くの種類のコーヒーを売っています。"],
    ["macam", "種類", "sort; kind", "名詞", "Ada bermacam-macam pilihan.", "さまざまな選択肢があります。"],
    ["jumlah", "数、合計", "amount; total", "名詞", "Jumlah peserta bertambah.", "参加者数は増えています。"],
    ["rata-rata", "平均", "average", "名詞", "Rata-rata orang bekerja delapan jam sehari.", "平均して人は1日8時間働きます。"],
    ["persen", "パーセント", "percent", "名詞", "Harga naik sepuluh persen.", "価格は10パーセント上がりました。"],
    ["angka", "数字、数値", "figure; number", "名詞", "Angka pengangguran menurun.", "失業者数は減っています。"],
    ["data", "データ", "data", "名詞", "Data itu dikumpulkan tahun lalu.", "そのデータは去年集められました。"],
    ["fakta", "事実", "fact", "名詞", "Berita itu tidak sesuai dengan fakta.", "そのニュースは事実と合っていません。"],
    ["isu", "話題、問題", "issue", "名詞", "Isu lingkungan menjadi perhatian dunia.", "環境問題は世界の関心事になっています。"],
    ["topik", "テーマ、話題", "topic", "名詞", "Topik hari ini tentang pendidikan.", "今日のテーマは教育についてです。"],
    ["judul", "題名", "title", "名詞", "Saya lupa judul buku itu.", "私はその本の題名を忘れました。"],
    ["pengarang", "著者", "author", "名詞", "Pengarang novel itu terkenal.", "その小説の著者は有名です。"],
    ["penerbit", "出版社", "publisher", "名詞", "Penerbit itu ada di Jakarta.", "その出版社はジャカルタにあります。"],
    ["ekonomi", "経済", "economy", "名詞", "Ekonomi negara itu tumbuh cepat.", "その国の経済は速く成長しています。"],
    ["politik", "政治", "politics", "名詞", "Dia tidak tertarik pada politik.", "彼は政治に興味がありません。"],
    ["teknologi", "技術", "technology", "名詞", "Teknologi baru mengubah cara kerja kita.", "新しい技術は私たちの働き方を変えます。"],
    ["ilmu", "学問、知識", "science; knowledge", "名詞", "Ilmu itu berguna untuk masa depan.", "その知識は将来に役立ちます。"],
    ["ilmuwan", "科学者", "scientist", "名詞", "Ilmuwan itu menemukan obat baru.", "その科学者は新しい薬を発見しました。"],
    ["penemuan", "発見、発明", "discovery; invention", "名詞", "Penemuan itu mengubah dunia.", "その発見は世界を変えました。"],
    ["percobaan", "実験、試み", "experiment; attempt", "名詞", "Percobaan itu dilakukan di laboratorium.", "その実験は実験室で行われます。"],
    ["ponsel", "携帯電話", "mobile phone", "名詞", "Ponsel saya tertinggal di rumah.", "私は携帯電話を家に置き忘れました。"],
    ["aplikasi", "アプリ", "application; app", "名詞", "Aplikasi ini mudah digunakan.", "このアプリは使いやすいです。"],
    ["situs", "サイト", "website", "名詞", "Informasi ada di situs resmi.", "情報は公式サイトにあります。"],
    ["media sosial", "SNS", "social media", "名詞句", "Berita itu tersebar lewat media sosial.", "そのニュースはSNSで広まりました。"],
    ["api", "火", "fire", "名詞", "Jangan bermain api.", "火遊びをしないでください。"],
    ["asap", "煙", "smoke", "名詞", "Asap kebakaran terlihat dari jauh.", "火事の煙が遠くから見えます。"],
    ["debu", "ほこり", "dust", "名詞", "Meja itu penuh debu.", "その机はほこりだらけです。"],
    ["tanah", "土地、土", "land; soil", "名詞", "Harga tanah di kota naik.", "都市の土地価格は上がっています。"],
    ["batu", "石", "stone", "名詞", "Jalan itu penuh batu.", "その道は石だらけです。"],
    ["pasir", "砂", "sand", "名詞", "Anak-anak bermain pasir di pantai.", "子どもたちは海岸で砂遊びをします。"],
    ["rumput", "草", "grass", "名詞", "Rumput di taman itu hijau.", "その公園の草は緑です。"],
    ["pohon", "木", "tree", "名詞", "Pohon itu sudah tua.", "その木はもう古いです。"],
    ["bunga", "花、利子", "flower; interest", "名詞", "Saya membeli bunga untuk ibu.", "私は母に花を買います。"],
    ["daun", "葉", "leaf", "名詞", "Daun itu jatuh ke tanah.", "その葉は地面に落ちます。"],
    ["binatang", "動物", "animal", "名詞", "Di kebun binatang ada banyak binatang.", "動物園には多くの動物がいます。"],
    ["anjing", "犬", "dog", "名詞", "Anjing itu besar.", "その犬は大きいです。"],
    ["kucing", "猫", "cat", "名詞", "Kucing saya suka tidur.", "私の猫は寝るのが好きです。"],
    ["burung", "鳥", "bird", "名詞", "Burung itu terbang tinggi.", "その鳥は高く飛びます。"],
    ["sapi", "牛", "cow", "名詞", "Petani itu memelihara sapi.", "その農家は牛を飼っています。"],
    ["kambing", "ヤギ", "goat", "名詞", "Kambing makan rumput.", "ヤギは草を食べます。"],
    ["kuda", "馬", "horse", "名詞", "Dia bisa naik kuda.", "彼は馬に乗れます。"],
    ["gajah", "象", "elephant", "名詞", "Gajah adalah binatang besar.", "象は大きな動物です。"],
    ["monyet", "猿", "monkey", "名詞", "Ada banyak monyet di hutan itu.", "その森には猿がたくさんいます。"],
    ["ular", "ヘビ", "snake", "名詞", "Hati-hati, ada ular di rumput.", "気をつけて、草むらにヘビがいます。"],
    ["nyamuk", "蚊", "mosquito", "名詞", "Banyak nyamuk pada musim hujan.", "雨季には蚊が多いです。"],
    // --- 副詞・機能語 ---
    ["ternyata", "実は、〜と分かった", "it turns out", "副詞", "Ternyata dia sudah pindah.", "実は彼はもう引っ越していました。"],
    ["sebetulnya", "実のところ", "actually", "副詞", "Sebetulnya saya kurang paham.", "実のところ私はあまり理解していません。"],
    ["sekaligus", "同時に、一挙に", "at the same time", "副詞", "Dia belajar sekaligus bekerja.", "彼は働きながら同時に勉強します。"],
    ["sengaja", "わざと", "on purpose", "副詞", "Dia tidak sengaja memecahkan gelas.", "彼はわざとコップを割ったのではありません。"],
    ["kebetulan", "偶然", "by chance", "副詞", "Kebetulan kami naik kereta yang sama.", "偶然、私たちは同じ電車に乗りました。"],
    ["semoga", "〜でありますように", "hopefully", "副詞", "Semoga cepat sembuh.", "早く良くなりますように。"],
    ["mudah-mudahan", "〜だといいのですが", "hopefully", "副詞", "Mudah-mudahan besok tidak hujan.", "明日雨が降らないといいのですが。"],
    ["apalagi", "まして、なおさら", "especially; let alone", "副詞", "Kota ini ramai, apalagi pada akhir pekan.", "この町はにぎやかで、週末はなおさらです。"],
    ["tiba-tiba", "突然", "suddenly", "副詞", "Tiba-tiba lampu mati.", "突然電気が消えました。"],
    ["selanjutnya", "次に、その後", "next; subsequently", "副詞", "Selanjutnya, kita bahas jadwal.", "次に、予定について話し合いましょう。"],
    ["sebelumnya", "事前に、以前に", "beforehand; previously", "副詞", "Hubungi kami sebelumnya.", "事前に私たちに連絡してください。"],
    ["pertama-tama", "まず最初に", "first of all", "副詞", "Pertama-tama, isi formulir ini.", "まず最初に、この用紙に記入してください。"],
    ["selama ini", "これまで", "so far; all this time", "副詞", "Selama ini dia tinggal sendirian.", "これまで彼は一人で暮らしてきました。"],
    ["dahulu", "昔、以前", "formerly; in the past", "副詞", "Dahulu di sini ada pasar.", "昔ここには市場がありました。"],
    ["kelak", "将来、いつか", "someday; later", "副詞", "Kelak dia ingin menjadi dokter.", "将来、彼は医者になりたいと思っています。"],
    ["mendatang", "来たる、今後の", "upcoming", "形容詞", "Pemilu diadakan tahun mendatang.", "選挙は来年行われます。"],
    ["baru-baru ini", "最近", "recently", "副詞", "Baru-baru ini harga naik lagi.", "最近また価格が上がりました。"],
    ["akhir-akhir ini", "近ごろ", "lately", "副詞", "Akhir-akhir ini dia sering terlambat.", "近ごろ彼はよく遅刻します。"],
    ["kini", "今や", "now; nowadays", "副詞", "Kini semuanya bisa dilakukan lewat ponsel.", "今やすべて携帯電話でできます。"],
    ["tersebut", "前述の、その", "the said; aforementioned", "形容詞", "Masalah tersebut sudah diselesaikan.", "その問題はすでに解決されました。"],
    ["berikut", "次の、以下の", "following", "形容詞", "Perhatikan contoh berikut.", "次の例に注意してください。"],
    ["menjelang", "〜の直前に", "just before; toward", "前置詞", "Menjelang ujian, dia belajar keras.", "試験の直前、彼は懸命に勉強します。"],
    // --- 追加動詞(第2弾) ---
    ["membangunkan", "起こす", "to wake someone up", "動詞", "Ibu membangunkan saya jam lima.", "母は5時に私を起こします。"],
    ["menemani", "付き添う", "to accompany", "動詞", "Saya menemani ibu ke rumah sakit.", "私は母に付き添って病院へ行きます。"],
    ["menyapa", "あいさつする、声をかける", "to greet", "動詞", "Dia menyapa saya dengan ramah.", "彼は親しげに私にあいさつします。"],
    ["memperingatkan", "警告する", "to warn", "動詞", "Polisi memperingatkan pengendara.", "警察は運転者に警告します。"],
    ["mengingatkan", "思い出させる、注意する", "to remind", "動詞", "Dia mengingatkan saya tentang rapat.", "彼は私に会議のことを思い出させます。"],
    ["menjenguk", "見舞う", "to visit (a sick person)", "動詞", "Kami menjenguk teman di rumah sakit.", "私たちは病院に友だちを見舞います。"],
    ["mengundurkan diri", "辞任する、辞める", "to resign", "動詞", "Menteri itu mengundurkan diri.", "その大臣は辞任しました。"],
    ["melamar", "応募する、求婚する", "to apply; propose", "動詞", "Dia melamar pekerjaan di bank.", "彼は銀行の仕事に応募します。"],
    ["mempekerjakan", "雇う", "to employ", "動詞", "Perusahaan itu mempekerjakan seratus orang.", "その会社は100人を雇っています。"],
    ["memecat", "解雇する", "to fire", "動詞", "Perusahaan memecat karyawan itu.", "会社はその社員を解雇しました。"],
    ["pensiun", "退職する", "to retire", "動詞", "Ayah saya sudah pensiun.", "私の父はもう退職しました。"],
    ["magang", "インターンをする", "to intern", "動詞", "Dia magang di perusahaan Jepang.", "彼は日本企業でインターンをしています。"],
    ["lembur", "残業する", "to work overtime", "動詞", "Saya lembur sampai jam sembilan.", "私は9時まで残業します。"],
    ["berdiskusi", "討論する、話し合う", "to discuss", "動詞", "Kami berdiskusi tentang rencana liburan.", "私たちは休暇の計画について話し合います。"],
    ["berdebat", "議論する、討論する", "to debate", "動詞", "Mereka berdebat tentang politik.", "彼らは政治について議論します。"],
    ["bersaing", "競争する", "to compete", "動詞", "Kedua toko itu bersaing harga.", "その2つの店は価格で競争しています。"],
    ["berhati-hati", "注意する", "to be careful", "動詞", "Berhati-hatilah di jalan yang licin.", "滑りやすい道では注意してください。"],
    ["berpengaruh", "影響力がある", "to be influential", "動詞", "Tokoh itu sangat berpengaruh.", "その人物はとても影響力があります。"],
    ["memengaruhi", "影響を与える", "to influence", "動詞", "Cuaca memengaruhi hasil panen.", "天気は収穫の結果に影響します。"],
    ["mengakibatkan", "引き起こす", "to result in", "動詞", "Kecelakaan itu mengakibatkan kemacetan.", "その事故は渋滞を引き起こしました。"],
    ["menimbulkan", "生じさせる", "to cause; give rise to", "動詞", "Keputusan itu menimbulkan banyak pertanyaan.", "その決定は多くの疑問を生みました。"],
    ["mengganggu", "邪魔する、妨げる", "to disturb", "動詞", "Suara itu mengganggu tidur saya.", "その音は私の眠りを妨げます。"],
    ["merepotkan", "面倒をかける", "to trouble", "動詞", "Maaf, saya merepotkan Anda.", "すみません、お手数をおかけします。"],
    ["menyulitkan", "困難にする", "to make difficult", "動詞", "Aturan baru itu menyulitkan pedagang.", "新しい規則は商人を困らせます。"],
    ["memudahkan", "容易にする", "to make easy", "動詞", "Aplikasi ini memudahkan pembayaran.", "このアプリは支払いを容易にします。"],
    ["menolong", "助ける", "to help; rescue", "動詞", "Dia menolong orang yang jatuh.", "彼は転んだ人を助けます。"],
    ["menyumbang", "寄付する", "to donate", "動詞", "Warga menyumbang untuk korban banjir.", "住民は洪水の被災者のために寄付します。"],
    ["menyewakan", "貸し出す", "to rent out", "動詞", "Dia menyewakan kamarnya kepada mahasiswa.", "彼は部屋を大学生に貸しています。"],
    ["membagi", "分ける", "to divide", "動詞", "Guru membagi siswa menjadi empat kelompok.", "先生は生徒を4つのグループに分けます。"],
    ["membagikan", "配布する", "to distribute; hand out", "動詞", "Panitia membagikan minuman kepada peserta.", "委員会は参加者に飲み物を配ります。"],
    ["mengumumkan", "発表する", "to announce", "動詞", "Sekolah mengumumkan hasil ujian.", "学校は試験結果を発表します。"],
    ["menyiarkan", "放送する", "to broadcast", "動詞", "Stasiun TV menyiarkan pertandingan itu.", "テレビ局はその試合を放送します。"],
    ["mewawancarai", "インタビューする", "to interview", "動詞", "Wartawan mewawancarai gubernur.", "記者は知事にインタビューします。"],
    ["merayakan", "祝う", "to celebrate", "動詞", "Kami merayakan tahun baru bersama.", "私たちは一緒に新年を祝います。"],
    ["memperingati", "記念する", "to commemorate", "動詞", "Sekolah memperingati hari kemerdekaan.", "学校は独立記念日を記念します。"],
    ["berpuasa", "断食する", "to fast", "動詞", "Umat Islam berpuasa pada bulan Ramadan.", "イスラム教徒はラマダン月に断食します。"],
    ["beribadah", "礼拝する", "to worship", "動詞", "Mereka beribadah di masjid.", "彼らはモスクで礼拝します。"],
    ["merantau", "故郷を離れて働く", "to leave one's hometown", "動詞", "Banyak pemuda merantau ke kota.", "多くの若者が都会へ出て行きます。"],
    ["mudik", "帰省する", "to return to one's hometown", "動詞", "Kami mudik setiap Lebaran.", "私たちはレバラン(断食明け大祭)のたびに帰省します。"],
    ["menjemur", "干す", "to dry in the sun", "動詞", "Ibu menjemur pakaian di halaman.", "母は庭で服を干します。"],
    ["mengecek", "確認する、チェックする", "to check", "動詞", "Saya mengecek jadwal kereta.", "私は電車の時刻を確認します。"],
    ["memastikan", "確かめる", "to make sure", "動詞", "Saya memastikan semua data benar.", "私はすべてのデータが正しいことを確かめます。"],
    ["menyimak", "注意して聞く", "to listen carefully", "動詞", "Siswa menyimak penjelasan guru.", "生徒は先生の説明を注意して聞きます。"],
    ["menandai", "印をつける", "to mark", "動詞", "Saya menandai tanggal penting di kalender.", "私はカレンダーの重要な日付に印をつけます。"],
    ["menggambarkan", "描写する、表す", "to describe", "動詞", "Buku itu menggambarkan kehidupan desa.", "その本は村の暮らしを描いています。"],
    ["menjelajahi", "探検する、巡る", "to explore", "動詞", "Kami menjelajahi kota tua.", "私たちは旧市街を巡ります。"],
    ["mendaki", "登る", "to climb", "動詞", "Mereka mendaki gunung itu.", "彼らはその山に登ります。"],
    ["memancing", "釣りをする", "to fish", "動詞", "Ayah suka memancing di sungai.", "父は川で釣りをするのが好きです。"],
    ["menyelam", "潜る", "to dive", "動詞", "Kami menyelam di laut Bali.", "私たちはバリの海で潜ります。"],
    ["berjemur", "日光浴する", "to sunbathe", "動詞", "Wisatawan berjemur di pantai.", "観光客は海岸で日光浴します。"],
    ["berbaring", "横になる", "to lie down", "動詞", "Dia berbaring di sofa.", "彼はソファに横になります。"],
    ["bersandar", "寄りかかる", "to lean", "動詞", "Jangan bersandar pada pintu.", "ドアに寄りかからないでください。"],
    ["bersalaman", "握手する", "to shake hands", "動詞", "Kami bersalaman sebelum rapat.", "私たちは会議の前に握手します。"],
    ["mengetuk", "ノックする、たたく", "to knock", "動詞", "Seseorang mengetuk pintu.", "誰かがドアをノックします。"],
    ["menggosok", "こする、磨く", "to rub; scrub", "動詞", "Dia menggosok jendela sampai bersih.", "彼は窓をきれいになるまで磨きます。"],
    ["mengelap", "拭く", "to wipe", "動詞", "Saya mengelap meja dengan kain.", "私は布で机を拭きます。"],
    ["menjahit", "縫う", "to sew", "動詞", "Nenek menjahit baju sendiri.", "祖母は自分で服を縫います。"],
    ["menggunting", "はさみで切る", "to cut with scissors", "動詞", "Dia menggunting kertas itu.", "彼はその紙をはさみで切ります。"],
    ["merobek", "破る", "to tear", "動詞", "Jangan merobek halaman buku.", "本のページを破らないでください。"],
    ["membakar", "燃やす、焼く", "to burn", "動詞", "Mereka membakar sampah di halaman.", "彼らは庭でごみを燃やします。"],
    ["menghangatkan", "温める", "to warm up", "動詞", "Saya menghangatkan sup di dapur.", "私は台所でスープを温めます。"],
    ["mendinginkan", "冷やす", "to cool", "動詞", "Saya mendinginkan minuman di kulkas.", "私は冷蔵庫で飲み物を冷やします。"],
    ["menyiram", "水をやる、かける", "to water; pour on", "動詞", "Saya menyiram bunga setiap pagi.", "私は毎朝花に水をやります。"],
    ["melempar", "投げる", "to throw", "動詞", "Anak itu melempar bola.", "その子はボールを投げます。"],
    ["menendang", "蹴る", "to kick", "動詞", "Pemain itu menendang bola dengan keras.", "その選手はボールを強く蹴ります。"],
    ["memukul", "打つ、たたく", "to hit", "動詞", "Dia memukul bola dengan raket.", "彼はラケットでボールを打ちます。"],
    ["melompat", "跳ぶ", "to jump", "動詞", "Kucing itu melompat ke atas meja.", "その猫は机の上に跳び乗ります。"],
    ["memanjat", "よじ登る", "to climb", "動詞", "Anak-anak memanjat pohon.", "子どもたちは木に登ります。"],
    ["berputar", "回る", "to rotate; spin", "動詞", "Kipas itu berputar cepat.", "その扇風機は速く回ります。"],
    ["bergerak", "動く", "to move", "動詞", "Kereta mulai bergerak.", "電車は動き始めます。"],
    ["bersembunyi", "隠れる", "to hide", "動詞", "Kucing bersembunyi di bawah meja.", "猫は机の下に隠れます。"],
    ["menyembunyikan", "隠す", "to hide something", "動詞", "Dia menyembunyikan hadiah untuk anaknya.", "彼は子どものためのプレゼントを隠します。"],
    ["menemui", "会いに行く", "to meet with", "動詞", "Saya akan menemui manajer besok.", "私は明日マネージャーに会いに行きます。"],
    // --- 追加名詞(第2弾) ---
    ["pemerintah", "政府", "government", "名詞", "Pemerintah menurunkan harga bensin.", "政府はガソリン価格を引き下げます。"],
    ["negara", "国、国家", "country; state", "名詞", "Indonesia adalah negara kepulauan.", "インドネシアは島国です。"],
    ["bangsa", "民族、国民", "nation; people", "名詞", "Bangsa Indonesia terkenal ramah.", "インドネシア国民は親切なことで有名です。"],
    ["warga negara", "国民", "citizen", "名詞句", "Setiap warga negara punya hak yang sama.", "すべての国民は同じ権利を持っています。"],
    ["dunia", "世界", "world", "名詞", "Berita itu tersebar ke seluruh dunia.", "そのニュースは全世界に広まりました。"],
    ["luar negeri", "外国、海外", "abroad", "名詞句", "Dia bekerja di luar negeri.", "彼は外国で働いています。"],
    ["dalam negeri", "国内", "domestic", "名詞句", "Produk dalam negeri makin bagus.", "国産品はますます良くなっています。"],
    ["ibu kota", "首都", "capital city", "名詞句", "Jakarta adalah ibu kota Indonesia.", "ジャカルタはインドネシアの首都です。"],
    ["surat kabar", "新聞", "newspaper", "名詞句", "Berita itu dimuat di surat kabar.", "そのニュースは新聞に掲載されました。"],
    ["wartawan", "記者", "journalist", "名詞", "Wartawan itu menulis tentang pemilu.", "その記者は選挙について書きます。"],
    ["siaran", "放送", "broadcast", "名詞", "Siaran berita mulai jam tujuh.", "ニュース放送は7時に始まります。"],
    ["saluran", "チャンネル、水路", "channel", "名詞", "Saya suka saluran TV itu.", "私はそのテレビチャンネルが好きです。"],
    ["hiburan", "娯楽", "entertainment", "名詞", "Kota ini punya banyak tempat hiburan.", "この町には娯楽施設がたくさんあります。"],
    ["istirahat", "休憩", "rest; break", "名詞", "Kita istirahat sepuluh menit.", "10分休憩しましょう。"],
    ["impian", "夢、憧れ", "dream; aspiration", "名詞", "Menjadi guru adalah impian saya.", "先生になることが私の夢です。"],
    ["mimpi", "夢(睡眠中の)", "dream", "名詞", "Saya mimpi aneh tadi malam.", "私は昨夜変な夢を見ました。"],
    ["harapan", "希望、期待", "hope", "名詞", "Anak-anak adalah harapan bangsa.", "子どもたちは国民の希望です。"],
    ["semangat", "意欲、元気", "spirit; enthusiasm", "名詞", "Dia bekerja dengan penuh semangat.", "彼は意欲満々で働きます。"],
    ["tenaga", "力、エネルギー", "energy; power", "名詞", "Pekerjaan itu membutuhkan banyak tenaga.", "その仕事は多くの力を必要とします。"],
    ["usia", "年齢", "age", "名詞", "Usia rata-rata peserta 30 tahun.", "参加者の平均年齢は30歳です。"],
    ["umur", "年齢", "age", "名詞", "Berapa umur anak Anda?", "お子さんは何歳ですか。"],
    ["masa depan", "将来", "future", "名詞句", "Kami menabung untuk masa depan.", "私たちは将来のために貯金します。"],
    ["masa lalu", "過去", "past", "名詞句", "Jangan terlalu memikirkan masa lalu.", "過去を考えすぎないでください。"],
    ["zaman", "時代", "era", "名詞", "Pada zaman itu belum ada internet.", "その時代にはまだインターネットがありませんでした。"],
    ["abad", "世紀", "century", "名詞", "Bangunan itu dibangun pada abad ke-18.", "その建物は18世紀に建てられました。"],
    ["generasi", "世代", "generation", "名詞", "Generasi muda suka teknologi baru.", "若い世代は新しい技術が好きです。"],
    ["alam", "自然", "nature", "名詞", "Kami menikmati alam di desa.", "私たちは村で自然を楽しみます。"],
    ["air terjun", "滝", "waterfall", "名詞句", "Air terjun itu tinggi sekali.", "その滝はとても高いです。"],
    ["kehidupan", "生活、人生", "life", "名詞", "Kehidupan di desa tenang.", "村の生活は穏やかです。"],
    ["gaya hidup", "生活様式", "lifestyle", "名詞句", "Gaya hidup sehat makin populer.", "健康的な生活様式はますます人気です。"],
    ["kepribadian", "人柄、個性", "personality", "名詞", "Dia punya kepribadian yang baik.", "彼は人柄が良いです。"],
    ["sifat", "性質、性格", "character; nature", "名詞", "Sifat anak itu sabar.", "その子の性格は我慢強いです。"],
    ["sikap", "態度", "attitude", "名詞", "Sikapnya sopan kepada semua orang.", "彼の態度は誰に対しても礼儀正しいです。"],
    ["perilaku", "行動、ふるまい", "behavior", "名詞", "Orang tua memperhatikan perilaku anaknya.", "親は子どもの行動に気を配ります。"],
    ["tindakan", "行為、措置", "action; measure", "名詞", "Pemerintah mengambil tindakan cepat.", "政府は迅速な措置を取ります。"],
    ["kegagalan", "失敗", "failure", "名詞", "Kegagalan adalah awal keberhasilan.", "失敗は成功のもとです。"],
    ["keberhasilan", "成功", "success", "名詞", "Keberhasilan itu hasil kerja keras.", "その成功は努力の結果です。"],
    ["kekayaan", "富、財産", "wealth", "名詞", "Negara itu punya kekayaan alam yang besar.", "その国は豊かな天然資源を持っています。"],
    ["kebanggaan", "誇り", "pride", "名詞", "Tim itu menjadi kebanggaan kota.", "そのチームは町の誇りです。"],
    ["kebahagiaan", "幸福", "happiness", "名詞", "Kebahagiaan keluarga paling penting.", "家族の幸福が最も重要です。"],
    ["penampilan", "外見、出演", "appearance; performance", "名詞", "Penampilan penyanyi itu menarik perhatian.", "その歌手の出演は注目を集めました。"],
    ["suasana", "雰囲気", "atmosphere", "名詞", "Suasana kafe itu nyaman.", "そのカフェの雰囲気は快適です。"],
    ["keadaan", "状態、状況", "condition", "名詞", "Keadaan pasien membaik.", "患者の状態は良くなっています。"],
    ["situasi", "状況", "situation", "名詞", "Situasi di lokasi sudah aman.", "現場の状況はもう安全です。"],
    ["kondisi", "状態", "condition", "名詞", "Kondisi jalan itu buruk.", "その道の状態は悪いです。"],
    ["posisi", "位置、地位", "position", "名詞", "Posisi hotel itu dekat pantai.", "そのホテルの位置は海岸に近いです。"],
    ["lokasi", "場所、現場", "location", "名詞", "Lokasi acara diubah.", "行事の場所は変更されました。"],
    ["perbatasan", "国境、境界", "border", "名詞", "Kota itu dekat perbatasan.", "その町は国境の近くにあります。"],
    ["lalu lintas", "交通", "traffic", "名詞句", "Lalu lintas pagi ini padat.", "今朝の交通は混雑しています。"],
    ["kendaraan", "車両、乗り物", "vehicle", "名詞", "Jumlah kendaraan terus bertambah.", "車両の数は増え続けています。"],
    ["pejalan kaki", "歩行者", "pedestrian", "名詞句", "Hati-hati terhadap pejalan kaki.", "歩行者に気をつけてください。"],
    ["helm", "ヘルメット", "helmet", "名詞", "Pengendara motor wajib memakai helm.", "バイクの運転者はヘルメットの着用が義務です。"],
    ["sabuk pengaman", "シートベルト", "seat belt", "名詞句", "Pakai sabuk pengaman selama perjalanan.", "走行中はシートベルトを着用してください。"],
    ["kecepatan", "速度", "speed", "名詞", "Kurangi kecepatan di dekat sekolah.", "学校の近くでは速度を落としてください。"],
    ["jarak", "距離", "distance", "名詞", "Jarak ke bandara sekitar 20 kilometer.", "空港までの距離は約20キロです。"],
    ["demonstrasi", "デモ", "demonstration", "名詞", "Demonstrasi itu berjalan tenang.", "そのデモは穏やかに進みました。"],
    ["pemadam kebakaran", "消防隊", "fire brigade", "名詞句", "Pemadam kebakaran tiba dengan cepat.", "消防隊は素早く到着しました。"],
    ["ambulans", "救急車", "ambulance", "名詞", "Ambulans membawa pasien ke rumah sakit.", "救急車は患者を病院へ運びます。"],
    ["keadaan darurat", "緊急事態", "emergency", "名詞句", "Dalam keadaan darurat, hubungi nomor ini.", "緊急時にはこの番号に連絡してください。"],
    ["pertolongan pertama", "応急手当", "first aid", "名詞句", "Dia belajar pertolongan pertama.", "彼は応急手当を学びます。"],
    ["operasi", "手術、作戦", "operation; surgery", "名詞", "Operasi itu berjalan lancar.", "手術は順調に進みました。"],
    ["suntikan", "注射", "injection", "名詞", "Anak itu takut suntikan.", "その子は注射を怖がります。"],
    ["vitamin", "ビタミン", "vitamin", "名詞", "Buah mengandung banyak vitamin.", "果物は多くのビタミンを含みます。"],
    ["gizi", "栄養", "nutrition", "名詞", "Makanan bergizi penting untuk anak.", "栄養のある食事は子どもにとって重要です。"],
    ["pola makan", "食生活", "diet; eating pattern", "名詞句", "Jaga pola makan Anda.", "食生活に気をつけてください。"],
    ["berat badan", "体重", "body weight", "名詞句", "Berat badan saya naik dua kilo.", "私の体重は2キロ増えました。"],
    ["kulit", "皮膚、皮", "skin", "名詞", "Kulit saya terbakar matahari.", "私の肌は日焼けしました。"],
    ["darah", "血", "blood", "名詞", "Tekanan darah saya normal.", "私の血圧は正常です。"],
    ["tulang", "骨", "bone", "名詞", "Susu baik untuk tulang.", "牛乳は骨に良いです。"],
    ["otot", "筋肉", "muscle", "名詞", "Otot kaki saya sakit setelah lari.", "走った後、脚の筋肉が痛いです。"],
    ["jantung", "心臓", "heart", "名詞", "Olahraga baik untuk jantung.", "運動は心臓に良いです。"],
    ["paru-paru", "肺", "lungs", "名詞", "Merokok merusak paru-paru.", "喫煙は肺を傷つけます。"],
    ["otak", "脳", "brain", "名詞", "Tidur cukup baik untuk otak.", "十分な睡眠は脳に良いです。"],
    ["napas", "呼吸、息", "breath", "名詞", "Tarik napas dalam-dalam.", "深く息を吸ってください。"],
    ["keringat", "汗", "sweat", "名詞", "Keringat keluar setelah berolahraga.", "運動の後、汗が出ます。"],
    ["dokter gigi", "歯医者", "dentist", "名詞句", "Saya pergi ke dokter gigi besok.", "私は明日歯医者へ行きます。"],
    ["kantor pos", "郵便局", "post office", "名詞句", "Saya mengirim paket di kantor pos.", "私は郵便局で小包を送ります。"],
    ["perangko", "切手", "stamp", "名詞", "Saya membeli perangko di kantor pos.", "私は郵便局で切手を買います。"],
    ["amplop", "封筒", "envelope", "名詞", "Masukkan surat ke dalam amplop.", "手紙を封筒に入れてください。"],
    ["kode pos", "郵便番号", "postal code", "名詞句", "Tulis kode pos dengan benar.", "郵便番号を正しく書いてください。"],
    ["pulsa", "携帯のチャージ、通話料", "phone credit", "名詞", "Saya membeli pulsa di minimarket.", "私はコンビニで携帯のチャージを買います。"],
    ["jam kerja", "勤務時間", "working hours", "名詞句", "Jam kerja kantor itu dari sembilan sampai lima.", "その会社の勤務時間は9時から5時までです。"],
    ["hari kerja", "平日", "weekday", "名詞句", "Bank buka pada hari kerja.", "銀行は平日に開いています。"],
    ["akhir pekan", "週末", "weekend", "名詞句", "Kami pergi ke pantai pada akhir pekan.", "私たちは週末に海岸へ行きます。"],
    ["bonus", "ボーナス", "bonus", "名詞", "Karyawan menerima bonus akhir tahun.", "社員は年末ボーナスを受け取ります。"],
    ["pabrik", "工場", "factory", "名詞", "Pabrik itu memproduksi sepatu.", "その工場は靴を生産しています。"],
    ["mesin cuci", "洗濯機", "washing machine", "名詞句", "Mesin cuci kami rusak.", "私たちの洗濯機は壊れています。"],
    ["kulkas", "冷蔵庫", "refrigerator", "名詞", "Simpan sayur di kulkas.", "野菜は冷蔵庫に保管してください。"],
    ["AC", "エアコン", "air conditioner", "名詞", "Tolong nyalakan AC.", "エアコンをつけてください。"],
    ["kipas angin", "扇風機", "electric fan", "名詞句", "Kami memakai kipas angin pada musim panas.", "私たちは暑い時期に扇風機を使います。"],
    ["setrika", "アイロン", "iron", "名詞", "Setrika itu masih panas.", "そのアイロンはまだ熱いです。"],
    ["televisi", "テレビ", "television", "名詞", "Kami menonton berita di televisi.", "私たちはテレビでニュースを見ます。"],
    ["radio", "ラジオ", "radio", "名詞", "Kakek mendengarkan radio setiap pagi.", "祖父は毎朝ラジオを聞きます。"],
    ["internet", "インターネット", "internet", "名詞", "Internet di sini cepat.", "ここのインターネットは速いです。"],
    ["printer", "プリンター", "printer", "名詞", "Printer di kantor rusak.", "会社のプリンターは壊れています。"],
    ["kabel", "ケーブル、コード", "cable", "名詞", "Kabel charger saya putus.", "私の充電ケーブルは切れました。"],
    ["stopkontak", "コンセント", "power outlet", "名詞", "Ada stopkontak di dekat meja?", "机の近くにコンセントはありますか。"],
    ["lemari", "戸棚、タンス", "cupboard; wardrobe", "名詞", "Baju ada di dalam lemari.", "服はタンスの中にあります。"],
    ["rak", "棚", "shelf", "名詞", "Buku itu ada di rak paling atas.", "その本は一番上の棚にあります。"],
    ["laci", "引き出し", "drawer", "名詞", "Kunci ada di dalam laci.", "鍵は引き出しの中にあります。"],
    ["cermin", "鏡", "mirror", "名詞", "Dia melihat dirinya di cermin.", "彼は鏡で自分を見ます。"],
    ["karpet", "じゅうたん", "carpet", "名詞", "Karpet ini lembut.", "このじゅうたんは柔らかいです。"],
    ["gorden", "カーテン", "curtain", "名詞", "Ibu menutup gorden pada malam hari.", "母は夜にカーテンを閉めます。"],
    ["bantal", "枕", "pillow", "名詞", "Bantal ini terlalu tinggi.", "この枕は高すぎます。"],
    ["selimut", "毛布", "blanket", "名詞", "Pakai selimut kalau dingin.", "寒ければ毛布を使ってください。"],
    ["kasur", "マットレス、布団", "mattress", "名詞", "Kasur baru itu nyaman.", "その新しいマットレスは快適です。"],
    ["sepak bola", "サッカー", "soccer", "名詞句", "Anak-anak bermain sepak bola di lapangan.", "子どもたちは広場でサッカーをします。"],
    ["bulu tangkis", "バドミントン", "badminton", "名詞句", "Bulu tangkis populer di Indonesia.", "バドミントンはインドネシアで人気です。"],
    ["renang", "水泳", "swimming", "名詞", "Renang adalah olahraga favorit saya.", "水泳は私のお気に入りのスポーツです。"],
    ["lari", "走ること、ランニング", "running", "名詞", "Lari pagi baik untuk kesehatan.", "朝のランニングは健康に良いです。"],
    ["senam", "体操", "gymnastics; exercise", "名詞", "Ibu-ibu senam di taman setiap pagi.", "お母さんたちは毎朝公園で体操をします。"],
    ["permainan", "遊び、ゲーム", "game", "名詞", "Permainan itu mudah dipelajari.", "その遊びは覚えやすいです。"],
    ["mainan", "おもちゃ", "toy", "名詞", "Anak itu punya banyak mainan.", "その子はおもちゃをたくさん持っています。"],
    ["boneka", "人形", "doll", "名詞", "Adik saya suka boneka.", "私の妹は人形が好きです。"],
    ["layang-layang", "凧", "kite", "名詞", "Anak-anak bermain layang-layang.", "子どもたちは凧揚げをします。"],
    ["gitar", "ギター", "guitar", "名詞", "Dia bisa bermain gitar.", "彼はギターが弾けます。"],
    ["piano", "ピアノ", "piano", "名詞", "Anak saya belajar piano.", "私の子どもはピアノを習っています。"],
    ["penyanyi", "歌手", "singer", "名詞", "Penyanyi itu terkenal di Asia.", "その歌手はアジアで有名です。"],
    ["penari", "踊り手", "dancer", "名詞", "Penari itu tampil di panggung.", "その踊り手は舞台で演じます。"],
    ["panggung", "舞台", "stage", "名詞", "Panggung itu besar.", "その舞台は大きいです。"],
    ["konser", "コンサート", "concert", "名詞", "Konser itu diadakan bulan depan.", "そのコンサートは来月開かれます。"],
    ["lukisan", "絵画", "painting", "名詞", "Lukisan itu dijual mahal.", "その絵画は高く売られます。"],
    ["pelukis", "画家", "painter", "名詞", "Pelukis itu tinggal di Bali.", "その画家はバリに住んでいます。"],
    ["patung", "彫像", "statue", "名詞", "Patung itu terkenal di kota ini.", "その彫像はこの町で有名です。"],
    ["karya", "作品", "work (of art)", "名詞", "Karya penulis itu banyak dibaca.", "その作家の作品は多く読まれています。"],
    ["novel", "小説", "novel", "名詞", "Novel itu menjadi film.", "その小説は映画になりました。"],
    ["puisi", "詩", "poem", "名詞", "Dia menulis puisi tentang alam.", "彼は自然についての詩を書きます。"],
    ["tokoh", "人物、登場人物", "figure; character", "名詞", "Tokoh utama cerita itu seorang guru.", "その物語の主人公は先生です。"],
    // --- 追加形容詞(第2弾) ---
    ["padat", "密集した、詰まった", "dense; packed", "形容詞", "Jadwal saya padat minggu ini.", "今週の私の予定は詰まっています。"],
    ["longgar", "緩い、余裕のある", "loose", "形容詞", "Baju ini terlalu longgar.", "この服は緩すぎます。"],
    ["ketat", "厳しい、きつい", "tight; strict", "形容詞", "Persaingan makin ketat.", "競争はますます厳しくなっています。"],
    ["disiplin", "規律正しい", "disciplined", "形容詞", "Siswa di sekolah itu disiplin.", "その学校の生徒は規律正しいです。"],
    ["kreatif", "創造的な", "creative", "形容詞", "Anak itu kreatif dalam menggambar.", "その子は絵を描くことにおいて創造的です。"],
    ["aktif", "活発な、積極的な", "active", "形容詞", "Dia aktif dalam kegiatan sosial.", "彼は社会活動に積極的です。"],
    ["pasif", "消極的な", "passive", "形容詞", "Jangan pasif dalam diskusi.", "討論で受け身にならないでください。"],
    ["positif", "肯定的な", "positive", "形容詞", "Berpikirlah secara positif.", "前向きに考えましょう。"],
    ["negatif", "否定的な", "negative", "形容詞", "Berita itu memberi kesan negatif.", "そのニュースは否定的な印象を与えます。"],
    ["populer", "人気のある", "popular", "形容詞", "Lagu itu populer di kalangan anak muda.", "その歌は若者の間で人気です。"],
    ["unik", "独特な", "unique", "形容詞", "Desain gedung itu unik.", "その建物のデザインは独特です。"],
    ["indah", "美しい", "beautiful", "形容詞", "Pemandangan gunung itu indah.", "その山の景色は美しいです。"],
    ["cantik", "きれいな", "pretty; beautiful", "形容詞", "Bunga itu cantik.", "その花はきれいです。"],
    ["tampan", "ハンサムな", "handsome", "形容詞", "Aktor itu tampan.", "その俳優はハンサムです。"],
    ["gemuk", "太った", "fat", "形容詞", "Kucing itu gemuk.", "その猫は太っています。"],
    ["kurus", "やせた", "thin; skinny", "形容詞", "Dia kelihatan lebih kurus.", "彼は前よりやせて見えます。"],
    ["kuat", "強い、丈夫な", "strong", "形容詞", "Tali ini kuat.", "このひもは丈夫です。"],
    ["lemah", "弱い", "weak", "形容詞", "Sinyal di sini lemah.", "ここの電波は弱いです。"],
    ["cerdas", "聡明な", "intelligent", "形容詞", "Anak itu cerdas.", "その子は聡明です。"],
    ["bijaksana", "賢明な", "wise", "形容詞", "Keputusan itu bijaksana.", "その決定は賢明です。"],
    ["egois", "わがままな、利己的な", "selfish", "形容詞", "Jangan bersikap egois.", "わがままな態度を取らないでください。"],
    ["sombong", "傲慢な", "arrogant", "形容詞", "Orang itu sombong.", "その人は傲慢です。"],
    ["rendah hati", "謙虚な", "humble", "形容詞", "Dia sukses tetapi tetap rendah hati.", "彼は成功しても謙虚なままです。"],
    ["pemalu", "恥ずかしがりの", "shy", "形容詞", "Anak itu pemalu.", "その子は恥ずかしがり屋です。"],
    ["optimis", "楽観的な", "optimistic", "形容詞", "Kami optimis tentang masa depan.", "私たちは将来について楽観的です。"],
    ["pesimis", "悲観的な", "pessimistic", "形容詞", "Jangan terlalu pesimis.", "悲観的になりすぎないでください。"],
    ["hambar", "味が薄い", "tasteless; bland", "形容詞", "Sup ini hambar.", "このスープは味が薄いです。"],
    ["kental", "濃い、どろっとした", "thick (liquid)", "形容詞", "Kopi ini terlalu kental.", "このコーヒーは濃すぎます。"],
    ["renyah", "サクサクした", "crispy", "形容詞", "Kerupuk ini renyah.", "このクルプック(揚げせんべい)はサクサクしています。"],
    ["empuk", "柔らかい(肉・椅子など)", "tender; soft", "形容詞", "Daging ini empuk.", "この肉は柔らかいです。"],
    ["awet", "長持ちする", "durable; long-lasting", "形容詞", "Sepatu ini awet.", "この靴は長持ちします。"],
    ["murah hati", "気前がよい", "generous", "形容詞", "Orang itu murah hati.", "その人は気前がいいです。"],
    ["setia", "忠実な", "loyal; faithful", "形容詞", "Anjing adalah binatang yang setia.", "犬は忠実な動物です。"],
    ["curang", "ずるい、不正な", "cheating; unfair", "形容詞", "Pemain itu curang dalam pertandingan.", "その選手は試合で不正をしました。"],
    ["damai", "平和な", "peaceful", "形容詞", "Desa itu tenang dan damai.", "その村は静かで平和です。"],
    ["makmur", "繁栄した", "prosperous", "形容詞", "Negara itu makmur.", "その国は繁栄しています。"],
    ["maju", "進んだ、発展した", "advanced", "形容詞", "Teknologi negara itu maju.", "その国の技術は進んでいます。"],
    ["kuno", "古代の、古めかしい", "ancient; old-fashioned", "形容詞", "Candi itu bangunan kuno.", "その寺院遺跡は古い建造物です。"],
    // --- 追加機能語(第2弾) ---
    ["melalui", "〜を通じて", "through; via", "前置詞", "Informasi itu disampaikan melalui email.", "その情報はメールで伝えられました。"],
    ["bagi", "〜にとって", "for", "前置詞", "Air bersih penting bagi kesehatan.", "清潔な水は健康にとって重要です。"],
    ["bahwa", "〜ということ", "that", "接続詞", "Saya percaya bahwa dia jujur.", "私は彼が正直だと信じています。"],
    ["sehingga", "その結果〜", "so that; as a result", "接続詞", "Hujan deras sehingga jalan banjir.", "雨が激しかったので道が冠水しました。"],
    ["ketika", "〜するとき", "when", "接続詞", "Ketika saya datang, dia sedang makan.", "私が来たとき、彼は食事中でした。"],
    ["saat", "〜するとき、時", "when; moment", "接続詞", "Saat hujan, jalan menjadi licin.", "雨のとき、道は滑りやすくなります。"],
    ["selagi", "〜する間に", "while", "接続詞", "Selagi muda, belajarlah banyak hal.", "若いうちに多くのことを学びなさい。"],
    ["jika", "もし〜なら", "if", "接続詞", "Jika ada masalah, hubungi kami.", "問題があれば私たちに連絡してください。"],
    ["bila", "もし〜なら", "if; when", "接続詞", "Bila perlu, saya akan datang.", "必要なら私は行きます。"],
    ["yakni", "すなわち", "namely", "接続詞", "Ada dua masalah, yakni biaya dan waktu.", "2つの問題、すなわち費用と時間があります。"]
  ];

  additionalRows.forEach(([word, japanese, english, partOfSpeech, example, exampleJapanese]) => {
    addCard({
      word,
      japanese,
      english,
      partOfSpeech,
      example,
      exampleJapanese,
      note: "C級で会話・読解の幅を広げる重要語彙。"
    });
  });

  const chosen = [];
  candidates.forEach((card) => {
    const key = card.word.toLowerCase();
    if (!usedWords.has(key) && !chosen.some((item) => item.word.toLowerCase() === key)) {
      chosen.push(card);
    }
  });

  chosen.forEach((card, index) => {
    appData.words.push({
      id: `c-${String(currentMaxNumber + index + 1).padStart(3, "0")}`,
      ...card
    });
  });
})();
