(function () {
  const appData = window.INDONESIAN_FLASHCARD_DATA;
  if (!appData) {
    return;
  }

  appData.phraseItems = appData.phraseItems || [];

  function add(level, rows) {
    rows.forEach(([phrase, japanese, category, note], index) => {
      appData.phraseItems.push({
        id: `phrase-${level.toLowerCase()}-${String(index + 1).padStart(3, "0")}`,
        level,
        phrase,
        japanese,
        category,
        note
      });
    });
  }

  add("E", [
    ["Selamat pagi.", "おはようございます。", "挨拶", "朝の基本挨拶。siang/sore/malam に入れ替えられる。"],
    ["Apa kabar?", "お元気ですか。", "挨拶", "返事は Baik. や Baik-baik saja. が自然。"],
    ["Nama saya Taro.", "私の名前は太郎です。", "自己紹介", "自己紹介の最初に使う定型文。"],
    ["Saya orang Jepang.", "私は日本人です。", "自己紹介", "orang + 国名で国籍を表す。"],
    ["Saya belajar bahasa Indonesia.", "私はインドネシア語を勉強しています。", "自己紹介", "検定の作文でも使いやすい基本文。"],
    ["Saya tinggal di Jepang.", "私は日本に住んでいます。", "自己紹介", "tinggal di + 場所。"],
    ["Ini apa?", "これは何ですか。", "質問", "物の名前を聞く最短表現。"],
    ["Berapa harganya?", "値段はいくらですか。", "買い物", "harganya は「その値段」。"],
    ["Saya mau ini.", "私はこれがほしいです。", "買い物", "mau は日常会話でよく使う「ほしい・したい」。"],
    ["Tolong ulangi sekali lagi.", "もう一度繰り返してください。", "依頼", "聞き取れないときの必須表現。"],
    ["Maaf, saya tidak mengerti.", "すみません、分かりません。", "会話", "検定の会話文でも使える。"],
    ["Bisa bicara pelan-pelan?", "ゆっくり話してもらえますか。", "依頼", "pelan-pelan は「ゆっくり」。"],
    ["Di mana toilet?", "トイレはどこですか。", "日常", "場所を聞く di mana。"],
    ["Saya mau pergi ke stasiun.", "私は駅へ行きたいです。", "移動", "pergi ke + 目的地。"],
    ["Terima kasih banyak.", "どうもありがとうございます。", "挨拶", "丁寧なお礼。"],
    ["Sama-sama.", "どういたしまして。", "挨拶", "Terima kasih への返事。"],
    ["Tidak apa-apa.", "大丈夫です。", "日常", "謝罪への返事にも使える。"],
    ["Saya suka makanan Indonesia.", "私はインドネシア料理が好きです。", "日常", "suka + 名詞。"],
    ["Saya belum tahu.", "私はまだ知りません。", "会話", "belum は「まだ〜していない」。"],
    ["Sampai jumpa lagi.", "また会いましょう。", "挨拶", "別れの挨拶。"],
    ["Permisi, boleh tanya?", "すみません、質問してもいいですか。", "依頼", "話しかけるときに便利な表現。"],
    ["Saya baik-baik saja.", "私は元気です。", "挨拶", "Apa kabar? への自然な返事。"],
    ["Maaf, saya terlambat.", "すみません、遅れました。", "日常", "terlambat は「遅れる」。"],
    ["Apa artinya ini?", "これはどういう意味ですか。", "学習", "artinya は「意味」。"],
    ["Tolong tulis di sini.", "ここに書いてください。", "依頼", "tulis は「書く」。"],
    ["Saya mau air putih.", "水がほしいです。", "飲食", "air putih は飲み水。"],
    ["Saya lapar.", "お腹がすきました。", "日常", "体調・状態を伝える基本文。"],
    ["Saya haus.", "のどが渇きました。", "日常", "飲み物を頼む前にも使える。"],
    ["Saya lelah.", "疲れました。", "日常", "lelah は「疲れた」。"],
    ["Jam berapa sekarang?", "今何時ですか。", "質問", "時刻を聞く基本表現。"],
    ["Besok saya libur.", "明日私は休みです。", "予定", "libur は休日・休み。"],
    ["Hari ini panas.", "今日は暑いです。", "天気", "cuaca の話題に入りやすい文。"],
    ["Rumah saya dekat stasiun.", "私の家は駅の近くです。", "自己紹介", "dekat + 場所で「〜の近く」。"],
    ["Saya pergi dengan teman.", "私は友だちと行きます。", "移動", "dengan は「〜と一緒に」。"],
    ["Saya naik bus.", "私はバスに乗ります。", "移動", "naik + 乗り物。"],
    ["Tolong ambil foto saya.", "私の写真を撮ってください。", "旅行", "旅行先で使いやすい依頼。"],
    ["Saya mencari hotel.", "私はホテルを探しています。", "旅行", "mencari は「探す」。"],
    ["Di mana pintu keluar?", "出口はどこですか。", "移動", "pintu keluar は「出口」。"],
    ["Bisa bayar dengan kartu?", "カードで払えますか。", "買い物", "dengan kartu で「カードで」。"],
    ["Sampai besok.", "また明日。", "挨拶", "短い別れの挨拶。"]
  ]);

  add("D", [
    ["Saya ingin memesan kamar.", "部屋を予約したいです。", "旅行", "ingin + 動詞で「〜したい」。"],
    ["Apakah masih ada kursi kosong?", "まだ空席はありますか。", "移動", "Apakah で丁寧な疑問文にする。"],
    ["Saya akan pergi besok pagi.", "私は明日の朝行く予定です。", "予定", "akan は未来・予定。"],
    ["Saya sudah membeli tiket.", "私はもうチケットを買いました。", "旅行", "sudah は完了を表す。"],
    ["Saya belum menerima pesan itu.", "私はまだそのメッセージを受け取っていません。", "日常", "belum + 動詞。"],
    ["Tolong hubungi saya lewat WhatsApp.", "WhatsAppで私に連絡してください。", "依頼", "hubungi は「連絡する」。"],
    ["Saya sedang mencari alamat ini.", "私はこの住所を探しています。", "移動", "sedang は進行中。"],
    ["Boleh saya coba?", "試してもいいですか。", "買い物", "boleh saya + 動詞。"],
    ["Ukuran ini terlalu besar.", "このサイズは大きすぎます。", "買い物", "terlalu は「〜すぎる」。"],
    ["Mana yang lebih murah?", "どちらがより安いですか。", "比較", "lebih + 形容詞で比較。"],
    ["Saya lebih suka yang ini.", "私はこちらの方が好きです。", "買い物", "yang ini は「こちらのもの」。"],
    ["Kalau hujan, saya tidak pergi.", "雨なら私は行きません。", "条件", "kalau は日常的な条件表現。"],
    ["Karena sakit, saya pulang lebih awal.", "病気なので早く帰ります。", "理由", "karena で理由を示す。"],
    ["Sebelum makan, saya cuci tangan.", "食べる前に手を洗います。", "日常", "sebelum は「〜前に」。"],
    ["Setelah bekerja, saya belajar.", "仕事の後で勉強します。", "日常", "setelah は「〜後で」。"],
    ["Saya pernah pergi ke Bali.", "私はバリへ行ったことがあります。", "経験", "pernah は経験。"],
    ["Saya harus mengisi formulir ini.", "この用紙に記入しなければなりません。", "手続き", "harus は義務。"],
    ["Kapan kantor ini buka?", "この事務所はいつ開きますか。", "質問", "kapan は時を聞く。"],
    ["Saya tidak bisa datang hari ini.", "私は今日行けません。", "連絡", "tidak bisa は「できない」。"],
    ["Mohon tunggu sebentar.", "少々お待ちください。", "丁寧表現", "mohon は丁寧な依頼。"],
    ["Saya ingin menukar uang.", "両替したいです。", "旅行", "menukar uang は「両替する」。"],
    ["Saya perlu pergi ke apotek.", "薬局へ行く必要があります。", "医療", "perlu + 動詞で必要性を表す。"],
    ["Apakah bisa lebih murah?", "もっと安くできますか。", "買い物", "lebih murah は「より安い」。"],
    ["Saya pesan satu porsi nasi goreng.", "ナシゴレンを一人前注文します。", "飲食", "satu porsi は「一人前」。"],
    ["Makanan ini terlalu pedas untuk saya.", "この料理は私には辛すぎます。", "飲食", "terlalu ... untuk saya の形。"],
    ["Saya sedang menunggu teman di lobi.", "私はロビーで友だちを待っています。", "日常", "sedang + 動詞で進行中。"],
    ["Tolong kirim alamatnya kepada saya.", "その住所を私に送ってください。", "依頼", "kirim A kepada B。"],
    ["Saya akan kembali sekitar jam tiga.", "私は3時ごろ戻ります。", "予定", "sekitar は「およそ」。"],
    ["Karena macet, saya datang terlambat.", "渋滞のため、私は遅れて来ました。", "理由", "macet は交通渋滞。"],
    ["Kalau tidak keberatan, boleh saya duduk di sini?", "差し支えなければ、ここに座ってもいいですか。", "丁寧表現", "tidak keberatan は「差し支えない」。"],
    ["Sebelum berangkat, saya mengecek jadwal.", "出発前に予定を確認します。", "予定", "sebelum + 動詞。"],
    ["Setelah rapat selesai, saya akan menelepon Anda.", "会議が終わった後、あなたに電話します。", "仕事", "setelah + 文の形。"],
    ["Saya pernah membaca artikel itu.", "私はその記事を読んだことがあります。", "経験", "pernah + 動詞。"],
    ["Saya harus membawa paspor.", "私はパスポートを持っていかなければなりません。", "旅行", "harus + 動詞。"],
    ["Apakah ada biaya tambahan?", "追加料金はありますか。", "質問", "biaya tambahan は「追加料金」。"],
    ["Saya tidak bisa membuka file ini.", "このファイルを開けません。", "仕事", "tidak bisa + 動詞。"],
    ["Mohon isi nama dan alamat Anda.", "お名前と住所を記入してください。", "手続き", "mohon + 動詞で丁寧な依頼。"],
    ["Tolong beri tahu saya kalau sudah selesai.", "終わったら私に知らせてください。", "連絡", "beri tahu は「知らせる」。"],
    ["Yang ini sama dengan yang itu.", "これはそれと同じです。", "比較", "sama dengan は「〜と同じ」。"],
    ["Saya ingin bertanya tentang jadwal ujian.", "試験日程について質問したいです。", "検定", "tentang + 名詞で「〜について」。"]
  ]);

  add("C", [
    ["Formulir itu harus diisi dengan lengkap.", "その用紙は完全に記入されなければなりません。", "検定", "diisi は受動態。案内文でよく出る。"],
    ["Barang yang rusak dapat dikembalikan.", "壊れた商品は返品できます。", "買い物", "yang で名詞を後ろから説明する。"],
    ["Saya menghubungi kantor mengenai jadwal baru.", "私は新しい予定について事務所に連絡しました。", "連絡", "mengenai は「〜について」。"],
    ["Harga tiket naik karena biaya operasional meningkat.", "運営費が増えたため、チケット価格が上がりました。", "理由", "原因と結果を読む練習に良い文。"],
    ["Meskipun sibuk, saya tetap belajar setiap hari.", "忙しくても、私は毎日勉強し続けます。", "逆接", "meskipun + 文。"],
    ["Jika ada perubahan, kami akan memberi tahu Anda.", "変更があれば、私たちはあなたに知らせます。", "案内", "通知文で使いやすい条件文。"],
    ["Saya memilih yang paling sederhana.", "私は一番簡単なものを選びます。", "比較", "yang + paling で「一番〜なもの」。"],
    ["Pendaftaran dibuka sampai hari Jumat.", "登録は金曜日まで受け付けています。", "手続き", "dibuka は受動・状態的に使われる。"],
    ["Keputusan itu dibuat berdasarkan data terbaru.", "その決定は最新データに基づいて行われました。", "検定", "berdasarkan は読解頻出。"],
    ["Tolong jelaskan perbedaan antara kedua kata itu.", "その2つの単語の違いを説明してください。", "学習", "antara A dan B。"],
    ["Saya belum yakin apakah jawaban ini benar.", "この答えが正しいかどうかまだ確信がありません。", "検定", "apakah の間接疑問。"],
    ["Kami berdiskusi tentang cara meningkatkan layanan.", "私たちはサービスを向上させる方法について議論しました。", "仕事", "cara + 動詞で「〜する方法」。"],
    ["Masalah ini perlu diselesaikan secepatnya.", "この問題はできるだけ早く解決される必要があります。", "仕事", "perlu + di- で必要性を表す。"],
    ["Saya tidak hanya belajar kosakata, tetapi juga tata bahasa.", "私は語彙だけでなく文法も勉強しています。", "学習", "tidak hanya A, tetapi juga B。"],
    ["Menurut laporan itu, jumlah wisatawan meningkat.", "その報告によると、観光客数は増えました。", "読解", "menurut は資料・人による情報源。"],
    ["Pemerintah berusaha mengurangi kemacetan lalu lintas.", "政府は交通渋滞を減らそうとしています。", "ニュース", "berusaha + 動詞。"],
    ["Saya ingin mengetahui alasan di balik keputusan itu.", "私はその決定の背後にある理由を知りたいです。", "読解", "di balik は「〜の背後に」。"],
    ["Semua peserta diminta membawa kartu identitas.", "すべての参加者は身分証を持参するよう求められています。", "案内", "diminta + 動詞。"],
    ["Akibat hujan deras, beberapa jalan ditutup.", "大雨のため、いくつかの道路が閉鎖されました。", "ニュース", "akibat + 名詞で原因。"],
    ["Dengan demikian, jadwal harus diubah.", "したがって、予定は変更されなければなりません。", "論理", "結論を導く表現。"],
    ["Peserta yang terlambat lebih dari sepuluh menit tidak diperkenankan masuk.", "10分以上遅れた参加者は入室を許可されません。", "検定", "案内文で出やすい受動表現。"],
    ["Dokumen tersebut perlu dilampirkan pada formulir pendaftaran.", "その書類は登録用紙に添付される必要があります。", "手続き", "dilampirkan は「添付される」。"],
    ["Saya ingin memastikan apakah pembayaran sudah diterima.", "支払いが受け取られたか確認したいです。", "手続き", "memastikan apakah ... の間接疑問。"],
    ["Apabila terjadi kesalahan, hubungi petugas yang bertanggung jawab.", "誤りが発生した場合、担当係員に連絡してください。", "案内", "apabila はやや硬い条件表現。"],
    ["Kegiatan ini bertujuan meningkatkan pemahaman masyarakat.", "この活動は社会の理解を高めることを目的としています。", "説明", "bertujuan + 動詞。"],
    ["Berbeda dengan tahun lalu, jumlah peserta tahun ini meningkat.", "昨年と違って、今年の参加者数は増えました。", "比較", "berbeda dengan は「〜と異なる」。"],
    ["Selain biaya transportasi, peserta juga harus menanggung biaya makan.", "交通費に加えて、参加者は食費も負担しなければなりません。", "案内", "selain A, juga B。"],
    ["Informasi lebih lanjut dapat dilihat di situs resmi.", "詳しい情報は公式サイトで見ることができます。", "案内", "lebih lanjut は「さらに詳しい」。"],
    ["Keputusan akhir akan diumumkan setelah proses seleksi selesai.", "最終決定は選考過程が終わった後に発表されます。", "手続き", "akan diumumkan の受動未来。"],
    ["Mereka sedang menyiapkan laporan yang akan diserahkan besok.", "彼らは明日提出される報告書を準備しています。", "仕事", "yang akan ... で後ろから説明。"],
    ["Saya kurang setuju dengan pendapat tersebut karena datanya belum cukup.", "データがまだ十分でないため、その意見にはあまり賛成できません。", "意見", "kurang setuju はやわらかい反対。"],
    ["Dalam beberapa tahun terakhir, penggunaan internet meningkat pesat.", "ここ数年で、インターネット利用は急速に増えました。", "ニュース", "dalam beberapa tahun terakhir は読解頻出。"],
    ["Jika dibandingkan dengan daerah lain, kota ini lebih padat.", "他の地域と比べると、この都市はより人口密度が高いです。", "比較", "jika dibandingkan dengan ...。"],
    ["Pihak sekolah meminta orang tua memperhatikan kesehatan anak.", "学校側は保護者に子どもの健康に注意するよう求めています。", "案内", "meminta A + 動詞。"],
    ["Tidak semua peserta memahami petunjuk yang diberikan.", "すべての参加者が与えられた指示を理解しているわけではありません。", "検定", "tidak semua は部分否定。"],
    ["Kereta tertunda akibat gangguan teknis.", "技術的な障害のため列車が遅れました。", "ニュース", "akibat + 名詞で原因。"],
    ["Sementara itu, panitia sedang mempersiapkan ruang ujian.", "その一方で、委員会は試験会場を準備しています。", "論理", "sementara itu は場面転換。"],
    ["Saya membutuhkan penjelasan yang lebih rinci.", "私はより詳しい説明が必要です。", "学習", "lebih rinci は「より詳細な」。"],
    ["Masalah itu dapat dicegah dengan perencanaan yang baik.", "その問題は良い計画によって防ぐことができます。", "仕事", "dapat dicegah の受動可能。"],
    ["Dengan adanya sistem baru, proses pendaftaran menjadi lebih cepat.", "新しいシステムがあることで、登録手続きはより速くなります。", "説明", "dengan adanya ... は説明文で便利。"]
  ]);

  add("B", [
    ["Kebijakan itu dinilai efektif dalam mengurangi ketimpangan.", "その政策は格差を減らす上で有効だと評価されています。", "論説", "dinilai + 形容詞。"],
    ["Masalah ini tidak terlepas dari faktor ekonomi.", "この問題は経済的要因と切り離せません。", "論説", "tidak terlepas dari はB級以上で重要。"],
    ["Data menunjukkan bahwa permintaan terus meningkat.", "データは需要が増え続けていることを示しています。", "読解", "bahwa 節で内容を説明する。"],
    ["Program ini diharapkan dapat meningkatkan kualitas layanan.", "この計画はサービス品質を高めることが期待されています。", "ニュース", "diharapkan dapat + 動詞。"],
    ["Mengingat risikonya besar, keputusan itu perlu ditinjau ulang.", "リスクが大きいことを考慮すると、その決定は再検討される必要があります。", "論理", "mengingat は判断の根拠。"],
    ["Di satu sisi, digitalisasi memudahkan akses; di sisi lain, risiko keamanan meningkat.", "一方でデジタル化はアクセスを容易にしますが、他方で安全リスクが高まります。", "論説", "対比構造の定型文。"],
    ["Bukan hanya biaya, tetapi juga kualitas harus dipertimbangkan.", "費用だけでなく品質も考慮されなければなりません。", "意見", "bukan hanya A, tetapi juga B。"],
    ["Semakin baik pelayanan, semakin tinggi kepuasan warga.", "サービスが良いほど住民満足度は高くなります。", "比較", "semakin A, semakin B。"],
    ["Kebijakan tersebut berpotensi menimbulkan dampak jangka panjang.", "その政策は長期的な影響を生む可能性があります。", "論説", "berpotensi + 動詞。"],
    ["Pemerintah perlu memperkuat mekanisme pengawasan.", "政府は監督の仕組みを強化する必要があります。", "ニュース", "memperkuat + 抽象名詞。"],
    ["Terlepas dari kritik yang ada, program itu tetap dilanjutkan.", "既存の批判にかかわらず、その計画は継続されました。", "逆接", "terlepas dari + 名詞。"],
    ["Keputusan itu dibuat berdasarkan pertimbangan yang matang.", "その決定は十分な検討に基づいて行われました。", "検定", "berdasarkan + 名詞句。"],
    ["Tidak semua masalah dapat diselesaikan melalui pendekatan yang sama.", "すべての問題が同じアプローチで解決できるわけではありません。", "論説", "tidak semua は部分否定。"],
    ["Pendekatan ini dianggap lebih sesuai dengan kebutuhan masyarakat.", "このアプローチは社会の必要により合っていると見なされています。", "論説", "dianggap + 比較表現。"],
    ["Dalam konteks ini, partisipasi warga menjadi sangat penting.", "この文脈では、住民参加が非常に重要になります。", "論説", "dalam konteks ini は段落展開に便利。"],
    ["Apabila data belum lengkap, kesimpulan harus dibuat dengan hati-hati.", "データが不十分な場合、結論は慎重に出されなければなりません。", "検定", "apabila は硬めの条件。"],
    ["Kenaikan harga berdampak pada daya beli masyarakat.", "価格上昇は社会の購買力に影響します。", "経済", "berdampak pada + 名詞。"],
    ["Tujuan utama program ini adalah memperluas akses pendidikan.", "この計画の主な目的は教育へのアクセスを広げることです。", "説明", "tujuan utama ... adalah ...。"],
    ["Sejauh ini, hasil yang dicapai belum maksimal.", "これまでのところ、達成された結果はまだ十分ではありません。", "報告", "sejauh ini は報告文で使いやすい。"],
    ["Dengan kata lain, masalahnya bersifat struktural.", "言い換えれば、その問題は構造的なものです。", "論理", "言い換えの定型表現。"],
    ["Isu tersebut perlu dilihat dari sudut pandang yang lebih luas.", "その問題はより広い視点から見られる必要があります。", "論説", "sudut pandang は「視点」。"],
    ["Peningkatan produktivitas tidak selalu sejalan dengan kesejahteraan pekerja.", "生産性の向上は必ずしも労働者の福祉と一致するわけではありません。", "論説", "tidak selalu は部分否定。"],
    ["Jika tidak ditangani secara serius, persoalan ini dapat berkembang menjadi krisis.", "真剣に対処されなければ、この問題は危機へ発展する可能性があります。", "論理", "条件から結果を述べる型。"],
    ["Temuan penelitian ini memperlihatkan hubungan antara pendidikan dan pendapatan.", "この研究結果は教育と所得の関係を示しています。", "報告", "temuan penelitian は報告文で頻出。"],
    ["Walaupun memiliki potensi besar, sektor ini masih menghadapi banyak kendala.", "大きな可能性があるものの、この分野はなお多くの制約に直面しています。", "逆接", "walaupun + 文。"],
    ["Pemerintah dituntut untuk mengambil langkah yang lebih transparan.", "政府はより透明な措置を取ることを求められています。", "ニュース", "dituntut untuk + 動詞。"],
    ["Kebijakan ini menuai kritik karena dianggap kurang berpihak pada kelompok rentan.", "この政策は弱い立場の集団にあまり寄り添っていないと見なされ、批判を招いています。", "批判", "menuai kritik は「批判を招く」。"],
    ["Dalam jangka pendek, dampaknya mungkin belum terlihat secara jelas.", "短期的には、その影響はまだ明確に見えないかもしれません。", "報告", "dalam jangka pendek は期間を示す。"],
    ["Perubahan iklim memperparah risiko bencana di wilayah pesisir.", "気候変動は沿岸地域の災害リスクを悪化させています。", "環境", "memperparah は「悪化させる」。"],
    ["Salah satu tantangan utama adalah kurangnya koordinasi antarlembaga.", "主な課題の一つは機関間の調整不足です。", "説明", "salah satu ... utama は論説で便利。"],
    ["Oleh karena itu, evaluasi berkala menjadi sangat diperlukan.", "そのため、定期的な評価が非常に必要になります。", "論理", "oleh karena itu で結論へつなぐ。"],
    ["Tidak dapat dipungkiri bahwa teknologi mengubah pola interaksi sosial.", "技術が社会的相互作用の形を変えることは否定できません。", "論説", "tidak dapat dipungkiri bahwa ...。"],
    ["Keberhasilan program ini sangat bergantung pada partisipasi masyarakat.", "この計画の成功は社会参加に大きく依存しています。", "論説", "bergantung pada + 名詞。"],
    ["Sebaliknya, pendekatan yang terlalu kaku dapat menghambat inovasi.", "反対に、硬直しすぎたアプローチは革新を妨げる可能性があります。", "対比", "sebaliknya は対比の接続表現。"],
    ["Dari perspektif ekonomi, kebijakan tersebut cukup masuk akal.", "経済的視点から見ると、その政策はかなり理にかなっています。", "論説", "dari perspektif ...。"],
    ["Namun demikian, manfaatnya perlu dibandingkan dengan biaya sosial yang muncul.", "しかしながら、その利益は生じる社会的費用と比較される必要があります。", "論理", "namun demikian は硬めの逆接。"],
    ["Laporan itu menyoroti perlunya perlindungan data pribadi.", "その報告書は個人データ保護の必要性を強調しています。", "ニュース", "menyoroti は「焦点を当てる」。"],
    ["Kondisi ini menunjukkan bahwa reformasi belum berjalan secara optimal.", "この状況は改革がまだ最適に進んでいないことを示しています。", "論説", "berjalan secara optimal は報告文で便利。"],
    ["Agar tujuan tercapai, indikator keberhasilan harus dirumuskan dengan jelas.", "目的が達成されるためには、成功指標が明確に定められなければなりません。", "検定", "agar + 目的。"],
    ["Pada tahap awal, fokus utama adalah membangun kepercayaan publik.", "初期段階では、主な焦点は公共の信頼を築くことです。", "説明", "pada tahap awal は段階を示す。"]
  ]);

  add("A", [
    ["Tulisan ini berargumen bahwa reformasi kelembagaan perlu dipercepat.", "本稿は制度改革を加速する必要があると主張しています。", "論説", "A級の読解で主張を示す型。"],
    ["Persoalan tersebut tidak dapat dipahami secara terpisah dari konteks historisnya.", "その問題は歴史的文脈から切り離して理解することはできません。", "論説", "secara terpisah dari は高度読解向け。"],
    ["Perlu digarisbawahi bahwa data ini masih bersifat sementara.", "このデータはまだ暫定的なものである点を強調すべきです。", "論説", "筆者の強調点を示す定型文。"],
    ["Dapat dikatakan bahwa kebijakan ini memiliki implikasi yang luas.", "この政策は広範な含意を持つと言えます。", "要約", "結論をやわらかく述べる表現。"],
    ["Di satu sisi, pendekatan ini menawarkan solusi praktis; di sisi lain, ia menyisakan persoalan normatif.", "一方でこのアプローチは実践的解決策を提示しますが、他方で規範的問題を残します。", "論説", "A級らしい対比の型。"],
    ["Bukan semata-mata persoalan teknis, melainkan juga persoalan legitimasi.", "それは単なる技術的問題ではなく、正当性の問題でもあります。", "論説", "bukan semata-mata A, melainkan B。"],
    ["Berangkat dari asumsi tersebut, analisis ini menempatkan warga sebagai aktor utama.", "その仮定を出発点として、この分析は住民を主要な主体として位置づけます。", "学術", "berangkat dari + 名詞句。"],
    ["Krisis ini berimplikasi pada cara negara merumuskan kebijakan publik.", "この危機は国家が公共政策を策定する方法に影響を持ちます。", "論説", "berimplikasi pada + 名詞句。"],
    ["Sejauh menyangkut hak warga, transparansi merupakan prinsip yang tidak dapat diabaikan.", "住民の権利に関する限り、透明性は無視できない原則です。", "論説", "sejauh menyangkut で範囲を限定。"],
    ["Terlepas dari kenyataan bahwa biayanya tinggi, program tersebut tetap relevan.", "費用が高いという事実にかかわらず、その計画はなお妥当です。", "逆接", "高度な譲歩表現。"],
    ["Fenomena ini menunjukkan adanya pergeseran dalam relasi kekuasaan.", "この現象は権力関係における変化の存在を示しています。", "読解", "adanya + 名詞で存在を示す。"],
    ["Pada tataran konseptual, istilah ini masih diperdebatkan.", "概念レベルでは、この用語はまだ議論されています。", "学術", "pada tataran + 名詞。"],
    ["Analisis ini tidak bermaksud menolak modernisasi, melainkan meninjau batas-batasnya.", "この分析は近代化を否定するのではなく、その限界を検討することを意図しています。", "論説", "bukan/ tidak ... melainkan ... の高度な型。"],
    ["Sebagaimana dikemukakan dalam laporan tersebut, ketimpangan akses masih menjadi hambatan utama.", "その報告で述べられているように、アクセス格差はなお主要な障害です。", "引用", "引用・参照表現。"],
    ["Dengan mempertimbangkan kompleksitas masalah, solusi tunggal tidak memadai.", "問題の複雑さを考慮すると、単一の解決策では不十分です。", "論説", "条件を添えて結論を述べる。"],
    ["Alih-alih menyelesaikan konflik, kebijakan itu justru memperdalam polarisasi.", "対立を解決するどころか、その政策はむしろ分極化を深めました。", "批判", "批判的論説で使える定型文。"],
    ["Semakin kuat dominasi pasar, semakin terbatas ruang intervensi negara.", "市場の支配が強くなるほど、国家の介入余地は限られます。", "論説", "semakin A, semakin B の高度版。"],
    ["Pertanyaan utamanya adalah sejauh mana kebijakan itu mampu menjawab kebutuhan warga.", "主な問いは、その政策が住民の必要にどの程度応えられるかです。", "学術", "研究課題を示す型。"],
    ["Dalam kerangka pembangunan berkelanjutan, pertumbuhan ekonomi harus diseimbangkan dengan perlindungan lingkungan.", "持続可能な開発の枠組みでは、経済成長は環境保護と均衡させなければなりません。", "論説", "A級の環境・政策文で使いやすい。"],
    ["Pada akhirnya, persoalan ini menuntut rekonsiliasi antara efisiensi dan keadilan.", "最終的に、この問題は効率と正義の調整を求めています。", "結論", "結論部で使いやすい定型文。"],
    ["Argumen tersebut berangkat dari pemahaman bahwa pembangunan tidak netral secara sosial.", "その議論は、開発が社会的に中立ではないという理解から出発しています。", "論説", "berangkat dari pemahaman bahwa ...。"],
    ["Dengan menelaah proses historisnya, tampak bahwa konflik ini memiliki akar yang panjang.", "その歴史的過程を検討すると、この対立には長い根があることが分かります。", "学術", "dengan menelaah ... で分析の前提を示す。"],
    ["Kendati demikian, generalisasi semacam itu perlu diperlakukan dengan hati-hati.", "とはいえ、そのような一般化は慎重に扱われる必要があります。", "論理", "kendati demikian は高度な逆接。"],
    ["Apa yang dipersoalkan bukan sekadar hasil, melainkan mekanisme yang menghasilkan ketimpangan.", "問題とされているのは単なる結果ではなく、格差を生み出す仕組みです。", "論説", "bukan sekadar A, melainkan B。"],
    ["Di balik keberhasilan ekonomi tersebut, terdapat persoalan distribusi yang belum terselesaikan.", "その経済的成功の背後には、未解決の分配問題があります。", "批判", "di balik ... terdapat ...。"],
    ["Paradigma ini menggeser perhatian dari pertumbuhan menuju keberlanjutan.", "このパラダイムは注意を成長から持続可能性へ移します。", "学術", "menggeser perhatian dari A menuju B。"],
    ["Dalam wacana publik, istilah ini kerap digunakan tanpa definisi yang memadai.", "公共の議論では、この用語は十分な定義なしにしばしば使われます。", "論説", "wacana publik はA級読解向け。"],
    ["Analisis komparatif menunjukkan bahwa respons tiap daerah sangat dipengaruhi kapasitas institusional.", "比較分析は、各地域の対応が制度的能力に大きく左右されることを示しています。", "学術", "dipengaruhi + 名詞。"],
    ["Kebijakan yang tampak netral dapat menghasilkan konsekuensi yang tidak merata.", "中立に見える政策が、不均等な結果を生み出すことがあります。", "論説", "tampak + 形容詞。"],
    ["Pertanyaan tersebut membuka ruang untuk meninjau kembali asumsi dasar penelitian.", "その問いは研究の基本的仮定を見直す余地を開きます。", "学術", "membuka ruang untuk ...。"],
    ["Sejauh bukti yang tersedia, klaim tersebut belum dapat dipertahankan sepenuhnya.", "入手可能な証拠の範囲では、その主張はまだ完全には維持できません。", "論説", "sejauh ... で範囲を限定。"],
    ["Keterbatasan data bukan alasan untuk mengabaikan kecenderungan yang muncul.", "データの限界は、現れつつある傾向を無視する理由にはなりません。", "論説", "bukan alasan untuk ...。"],
    ["Dari sudut pandang normatif, legitimasi kebijakan bergantung pada proses partisipatif.", "規範的な視点からは、政策の正当性は参加型プロセスに依存します。", "学術", "dari sudut pandang normatif。"],
    ["Krisis ini memperlihatkan rapuhnya fondasi tata kelola yang ada.", "この危機は既存の統治基盤の脆弱さを示しています。", "論説", "rapuhnya + 名詞で抽象名詞化。"],
    ["Alih-alih memusatkan perhatian pada gejala, analisis perlu diarahkan pada struktur penyebabnya.", "症状に注意を集中するのではなく、分析は原因構造へ向けられる必要があります。", "批判", "alih-alih A, B。"],
    ["Kesimpulan tersebut harus dibaca dalam konteks keterbatasan metodologis penelitian.", "その結論は研究方法上の限界という文脈で読まれなければなりません。", "学術", "dalam konteks + 名詞句。"],
    ["Secara teoritis, konsep ini menjembatani perdebatan antara agensi dan struktur.", "理論的には、この概念は行為主体性と構造の間の議論を橋渡しします。", "学術", "secara teoritis は論文調の副詞句。"],
    ["Ketegangan antara efisiensi pasar dan perlindungan sosial menjadi tema sentral pembahasan ini.", "市場効率と社会的保護の間の緊張が、この議論の中心テーマになります。", "論説", "ketegangan antara A dan B。"],
    ["Dengan demikian, solusi yang ditawarkan harus bersifat multidimensional.", "したがって、提示される解決策は多面的なものでなければなりません。", "結論", "bersifat multidimensional は高度な結論表現。"],
    ["Pada titik ini, perbedaan antara kompromi dan konsesi menjadi semakin penting.", "この時点で、妥協と譲歩の違いがますます重要になります。", "論説", "pada titik ini は議論の転換点を示す。"]
  ]);
})();
