(function () {
  const appData = window.INDONESIAN_FLASHCARD_DATA;
  if (!appData || !Array.isArray(appData.words)) {
    return;
  }

  const targetAdditional = 576;
  const startNumber = 25;
  const usedWords = new Set(appData.words.map((word) => word.word.toLowerCase()));

  // 「予約する、注文する」のような複数語義から文用の語義(先頭)だけを取り出す
  const jpMain = (text) => String(text || "").split("、")[0];

  // [word, japanese, english, object, objectJapanese, exampleOverride?, exampleJapaneseOverride?]
  // 例文は「Saya {動詞} {目的語}.」を基本とし、日本語で「を」が合わない語は個別に上書きする。
  const transitiveVerbs = [
    ["membayar", "支払う", "to pay", "tagihan", "請求書"],
    ["menerima", "受け取る", "to receive", "surat", "手紙"],
    ["mengirim", "送る", "to send", "paket", "荷物"],
    ["mengambil", "取る、受け取る", "to take; pick up", "uang", "お金"],
    ["menaruh", "置く", "to put", "kunci", "鍵"],
    ["memakai", "使う、身につける", "to use; wear", "sepatu", "靴", "Saya memakai sepatu.", "私は靴を身につける。"],
    ["menggunakan", "使用する", "to use", "komputer", "コンピューター"],
    ["mencoba", "試す", "to try", "baju", "服"],
    ["menjual", "売る", "to sell", "makanan", "食べ物"],
    ["menyewa", "借りる", "to rent", "kamar", "部屋"],
    ["memesan", "予約する、注文する", "to reserve; order", "tiket", "チケット"],
    ["menukar", "交換する、両替する", "to exchange", "uang", "お金"],
    ["memberi", "与える", "to give", "hadiah", "プレゼント"],
    ["mengajar", "教える", "to teach", "bahasa Indonesia", "インドネシア語"],
    ["mempelajari", "学ぶ", "to study; learn", "tata bahasa", "文法"],
    ["menonton", "見る、鑑賞する", "to watch", "film", "映画"],
    ["mendengarkan", "聞く", "to listen to", "lagu", "歌"],
    ["menelepon", "電話する", "to call", "dokter", "医者", "Saya menelepon dokter.", "私は医者に電話する。"],
    ["menghubungi", "連絡する", "to contact", "kantor", "会社", "Saya menghubungi kantor.", "私は会社に連絡する。"],
    ["mengundang", "招待する", "to invite", "teman", "友だち"],
    ["mengunjungi", "訪問する", "to visit", "museum", "博物館"],
    ["membantu", "手伝う、助ける", "to help", "ibu", "母"],
    ["membersihkan", "掃除する、きれいにする", "to clean", "kamar", "部屋"],
    ["mencuci", "洗う", "to wash", "pakaian", "服"],
    ["menyapu", "掃く", "to sweep", "lantai", "床"],
    ["mengepel", "モップをかける", "to mop", "lantai", "床", "Saya mengepel lantai.", "私は床にモップをかける。"],
    ["menyetrika", "アイロンをかける", "to iron", "baju", "服", "Saya menyetrika baju.", "私は服にアイロンをかける。"],
    ["memperbaiki", "修理する", "to repair", "sepeda", "自転車"],
    ["merusak", "壊す", "to damage", "mesin", "機械"],
    ["menyiapkan", "準備する", "to prepare", "sarapan", "朝食"],
    ["menyimpan", "保管する、貯める", "to keep; save", "uang", "お金"],
    ["membuang", "捨てる", "to throw away", "sampah", "ごみ"],
    ["mengganti", "替える、交換する", "to replace", "pakaian", "服"],
    ["melepas", "脱ぐ、外す", "to take off", "sepatu", "靴"],
    ["menyalakan", "つける", "to turn on", "lampu", "電気"],
    ["mematikan", "消す", "to turn off", "lampu", "電気"],
    ["mengunci", "鍵をかける", "to lock", "pintu", "ドア", "Saya mengunci pintu.", "私はドアに鍵をかける。"],
    ["memotong", "切る", "to cut", "buah", "果物"],
    ["memasukkan", "入れる", "to put in", "buku", "本"],
    ["mengeluarkan", "出す", "to take out", "dompet", "財布"],
    ["menaikkan", "上げる", "to raise", "harga", "値段"],
    ["menurunkan", "下げる", "to lower", "harga", "値段"],
    ["mencatat", "メモする、記録する", "to note down", "alamat", "住所"],
    ["mencetak", "印刷する", "to print", "dokumen", "書類"],
    ["menyalin", "写す、コピーする", "to copy", "kalimat", "文"],
    ["menerjemahkan", "翻訳する", "to translate", "surat", "手紙"],
    ["menjelaskan", "説明する", "to explain", "aturan", "規則"],
    ["mengulang", "繰り返す、復習する", "to repeat", "pelajaran", "授業内容"],
    ["melanjutkan", "続ける", "to continue", "pekerjaan", "仕事"],
    ["menghentikan", "止める", "to stop", "mobil", "車"],
    ["memulai", "始める", "to start", "rapat", "会議"],
    ["menyelesaikan", "終える、完成させる", "to finish", "tugas", "課題"],
    ["mengerjakan", "取り組む、する", "to do; work on", "PR", "宿題", "Saya mengerjakan PR.", "私は宿題に取り組む。"],
    ["mengumpulkan", "集める、提出する", "to collect; submit", "formulir", "用紙"],
    ["memeriksa", "確認する、検査する", "to check", "paspor", "パスポート"],
    ["mengukur", "測る", "to measure", "suhu", "温度"],
    ["menghitung", "数える、計算する", "to count", "uang", "お金"],
    ["menimbang", "量る", "to weigh", "barang", "品物"],
    ["menekan", "押す", "to press", "tombol", "ボタン"],
    ["menarik", "引く", "to pull", "pintu", "ドア"],
    ["mendorong", "押す", "to push", "kursi", "椅子"],
    ["mengangkat", "持ち上げる", "to lift", "koper", "スーツケース"],
    ["meletakkan", "置く", "to place", "gelas", "コップ"],
    ["mengembalikan", "返す", "to return", "buku", "本"],
    ["meminjam", "借りる", "to borrow", "payung", "傘"],
    ["meminjamkan", "貸す", "to lend", "buku", "本"],
    ["menyukai", "好む", "to like", "musik", "音楽"],
    ["mengenal", "知っている、知り合う", "to know; be acquainted", "tetangga", "近所の人"],
    ["memperkenalkan", "紹介する", "to introduce", "diri", "自分"],
    ["memotret", "写真を撮る", "to photograph", "pemandangan", "景色", "Saya memotret pemandangan.", "私は景色の写真を撮る。"],
    ["merekam", "録音する、録画する", "to record", "suara", "音"],
    ["menggambar", "描く", "to draw", "peta", "地図"],
    ["mewarnai", "色を塗る", "to color", "gambar", "絵", "Saya mewarnai gambar.", "私は絵に色を塗る。"],
    ["menghafal", "暗記する", "to memorize", "kata", "単語"],
    ["mengingat", "覚えている、思い出す", "to remember", "janji", "約束"],
    ["melupakan", "忘れる", "to forget", "nama", "名前"],
    ["menanyakan", "尋ねる", "to ask about", "harga", "値段"],
    ["menyebut", "述べる、呼ぶ", "to mention; call", "nama", "名前"],
    ["menunjukkan", "示す、見せる", "to show", "jalan", "道"],
    ["menunjuk", "指す", "to point at", "gambar", "絵"],
    ["mengikuti", "参加する、従う", "to join; follow", "kelas", "授業", "Saya mengikuti kelas.", "私は授業に参加する。"],
    ["menyeberangi", "横断する", "to cross", "jalan", "道"],
    ["mengantre", "列に並ぶ", "to queue", "loket", "窓口", "Saya mengantre di loket.", "私は窓口で列に並ぶ。"],
    ["menjemput", "迎えに行く", "to pick up", "anak", "子ども"],
    ["mengantar", "送って行く", "to take; escort", "tamu", "客"],
    ["mendapatkan", "得る、手に入れる", "to get", "pekerjaan", "仕事"],
    ["menemukan", "見つける", "to find", "dompet", "財布"],
    ["kehilangan", "なくす、失う", "to lose", "kunci", "鍵"],
    ["mengadakan", "開催する", "to hold", "rapat", "会議"],
    ["menghadiri", "出席する", "to attend", "pesta", "パーティー", "Saya menghadiri pesta.", "私はパーティーに出席する。"],
    ["menyampaikan", "伝える", "to convey", "pesan", "伝言"],
    ["menolak", "断る、拒否する", "to refuse", "ajakan", "誘い"],
    ["menyetujui", "同意する", "to agree to", "rencana", "計画", "Saya menyetujui rencana.", "私は計画に同意する。"],
    ["merencanakan", "計画する", "to plan", "perjalanan", "旅行"],
    ["mengatur", "整える、調整する", "to arrange", "jadwal", "予定"],
    ["mengurus", "手続きする、世話する", "to handle", "visa", "ビザ", "Saya mengurus visa.", "私はビザの手続きをする。"],
    ["menandatangani", "署名する", "to sign", "formulir", "用紙", "Saya menandatangani formulir.", "私は用紙に署名する。"],
    ["memfotokopi", "コピーする", "to photocopy", "paspor", "パスポート"],
    ["melampirkan", "添付する", "to attach", "foto", "写真"],
    ["menjaga", "守る、世話する", "to guard; care for", "kesehatan", "健康"],
    ["merawat", "世話する、看病する", "to take care of", "anak", "子ども"],
    ["mengobati", "治療する", "to treat", "pasien", "患者"],
    ["menawar", "値切る", "to bargain", "harga", "値段"],
    ["membungkus", "包む", "to wrap", "hadiah", "プレゼント"],
    ["menghias", "飾る", "to decorate", "kamar", "部屋"],
    ["mencicipi", "味見する", "to taste", "makanan", "食べ物"],
    ["menggoreng", "揚げる、炒める", "to fry", "ikan", "魚"],
    ["merebus", "ゆでる、煮る", "to boil", "telur", "卵"],
    ["memanggang", "焼く", "to grill; bake", "roti", "パン"],
    ["menuang", "注ぐ", "to pour", "air", "水"],
    ["mencampur", "混ぜる", "to mix", "gula", "砂糖"],
    ["mengaduk", "かき混ぜる", "to stir", "kopi", "コーヒー"],
    ["mengupas", "皮をむく", "to peel", "mangga", "マンゴー", "Saya mengupas mangga.", "私はマンゴーの皮をむく。"],
    ["menyikat", "磨く", "to brush", "gigi", "歯"],
    ["melayani", "接客する、対応する", "to serve", "pelanggan", "客", "Saya melayani pelanggan.", "私は客に対応する。"],
    ["memanggil", "呼ぶ", "to call", "taksi", "タクシー"],
    ["mengejar", "追いかける", "to chase", "bus", "バス"],
    ["menyusul", "後から追いつく", "to catch up with", "teman", "友だち", "Saya menyusul teman.", "私は後から友だちに追いつく。"],
    ["memarkir", "駐車する", "to park", "mobil", "車"],
    ["menyetir", "運転する", "to drive", "mobil", "車"],
    ["memperpanjang", "延長する", "to extend", "paspor", "パスポート"],
    ["memperpendek", "短くする", "to shorten", "tali", "ひも"],
    ["memperbesar", "大きくする", "to enlarge", "gambar", "画像"],
    ["memperkecil", "小さくする", "to reduce", "ukuran", "サイズ"],
    ["mempercepat", "速める", "to speed up", "proses", "過程"],
    ["memperlambat", "遅くする", "to slow down", "langkah", "歩み"],
    ["mengurangi", "減らす", "to reduce", "gula", "砂糖"],
    ["menambah", "加える、増やす", "to add", "garam", "塩"],
    ["memenuhi", "満たす", "to fulfill", "syarat", "条件"],
    ["membutuhkan", "必要とする", "to need", "bantuan", "助け"],
    ["mengusulkan", "提案する", "to propose", "ide", "考え"],
    ["membatalkan", "取り消す", "to cancel", "pesanan", "予約"],
    ["menentukan", "決める", "to decide", "tanggal", "日付"],
    ["mengubah", "変える", "to change", "jadwal", "予定"],
    ["menyusun", "作成する、並べる", "to arrange", "rencana", "計画", "Saya menyusun rencana.", "私は計画を作成する。"],
    ["membandingkan", "比較する", "to compare", "harga", "値段"],
    ["memperhatikan", "注意する", "to pay attention to", "penjelasan", "説明", "Saya memperhatikan penjelasan.", "私は説明に注意を払う。"],
    ["mengerti", "理解する", "to understand", "arti kata", "単語の意味"],
    ["memahami", "理解する", "to understand", "kalimat", "文"],
    ["meminta maaf", "謝る", "to apologize", "kesalahan", "間違い", "Saya meminta maaf atas kesalahan saya.", "私は自分の間違いを謝る。"],
    ["mengucapkan", "述べる、言う", "to say; utter", "terima kasih", "感謝", "Saya mengucapkan terima kasih.", "私はお礼を言う。"],
    ["mengajak", "誘う", "to invite", "teman", "友だち"],
    ["menikmati", "楽しむ、味わう", "to enjoy", "liburan", "休暇"],
    ["menghemat", "節約する", "to save", "uang", "お金"],
    ["menghabiskan", "使い切る、過ごす", "to spend", "waktu", "時間"],
    ["menitipkan", "預ける", "to leave in someone's care", "tas", "かばん"],
    ["mengambilkan", "取ってあげる", "to get for someone", "air", "水"],
    ["membawakan", "持ってきてあげる", "to bring for someone", "payung", "傘"],
    ["memulai ulang", "再起動する", "to restart", "komputer", "コンピューター"],
    ["memindahkan", "移動させる", "to move", "meja", "机"],
    ["mendekati", "近づく", "to approach", "pintu", "ドア", "Saya mendekati pintu.", "私はドアに近づく。"],
    ["menjauhi", "遠ざかる、避ける", "to avoid; keep away from", "bahaya", "危険", "Saya menjauhi bahaya.", "私は危険から遠ざかる。"],
    ["mencari tahu", "調べる", "to find out", "informasi", "情報"]
  ];

  // [word, japanese, english, 補語, 補語の訳, 主語(省略時は Saya), 主語の訳]
  // 無生物が主語になる動詞は主語を明示して「私は鳴る」のような誤文を避ける。
  const intransitiveVerbs = [
    ["berjalan", "歩く", "to walk", "di taman", "公園で"],
    ["berlari", "走る", "to run", "di lapangan", "広場で"],
    ["berhenti", "止まる", "to stop", "di halte", "停留所で"],
    ["berangkat", "出発する", "to depart", "ke kantor", "会社へ"],
    ["tiba", "到着する", "to arrive", "di stasiun", "駅に"],
    ["kembali", "戻る", "to return", "ke rumah", "家へ"],
    ["naik", "乗る、上がる", "to ride; go up", "bus", "バスに"],
    ["turun", "降りる、下がる", "to get off; go down", "dari kereta", "電車から"],
    ["lewat", "通る", "to pass by", "jalan ini", "この道を"],
    ["belok", "曲がる", "to turn", "ke kanan", "右へ"],
    ["bermain", "遊ぶ", "to play", "di luar", "外で"],
    ["beristirahat", "休む", "to rest", "di kamar", "部屋で"],
    ["berolahraga", "運動する", "to exercise", "setiap pagi", "毎朝"],
    ["berbelanja", "買い物をする", "to shop", "di pasar", "市場で"],
    ["berlibur", "休暇を過ごす", "to go on holiday", "di Bali", "バリで"],
    ["bepergian", "出かける、旅行する", "to travel", "dengan keluarga", "家族と"],
    ["bekerja sama", "協力する", "to cooperate", "dengan teman", "友だちと"],
    ["berdoa", "祈る", "to pray", "di masjid", "モスクで"],
    ["bersekolah", "学校に通う", "to attend school", "di Jakarta", "ジャカルタで"],
    ["bertemu", "会う", "to meet", "dengan guru", "先生と"],
    ["bertanya", "質問する", "to ask", "kepada petugas", "係員に"],
    ["tersenyum", "ほほえむ", "to smile", "kepada tamu", "客に"],
    ["tertawa", "笑う", "to laugh", "bersama teman", "友だちと"],
    ["menangis", "泣く", "to cry", "karena sedih", "悲しくて"],
    ["sembuh", "治る", "to recover", "dari sakit", "病気から"],
    ["lahir", "生まれる", "to be born", "di Surabaya", "スラバヤで"],
    ["meninggal", "亡くなる", "to pass away", "tahun lalu", "去年", "Kakek saya", "私の祖父は"],
    ["pindah", "引っ越す、移る", "to move", "ke kota lain", "別の町へ"],
    ["menikah", "結婚する", "to marry", "bulan depan", "来月"],
    ["bercerai", "離婚する", "to divorce", "tahun ini", "今年", "Mereka", "彼らは"],
    ["bertamu", "客として訪ねる", "to visit as a guest", "ke rumah teman", "友人の家へ"],
    ["menginap", "泊まる", "to stay overnight", "di hotel", "ホテルに"],
    ["berubah", "変わる", "to change", "sedikit", "少し", "Jadwal", "予定は"],
    ["bertambah", "増える", "to increase", "setiap hari", "毎日", "Penumpang", "乗客は"],
    ["membaik", "良くなる", "to improve", "pelan-pelan", "少しずつ", "Kondisinya", "状態は"],
    ["memburuk", "悪くなる", "to get worse", "karena hujan", "雨のため", "Kondisi jalan", "道の状態は"],
    ["berhasil", "成功する", "to succeed", "dalam ujian", "試験で"],
    ["gagal", "失敗する", "to fail", "sekali", "一度"],
    ["berkumpul", "集まる", "to gather", "di aula", "ホールに", "Kami", "私たちは"],
    ["berpisah", "別れる", "to separate", "di stasiun", "駅で", "Kami", "私たちは"],
    ["berlatih", "練習する", "to practice", "setiap hari", "毎日"],
    ["bernyanyi", "歌う", "to sing", "di kelas", "教室で"],
    ["menari", "踊る", "to dance", "di pesta", "パーティーで"],
    ["bersepeda", "自転車に乗る", "to ride a bicycle", "ke sekolah", "学校へ"],
    ["berlayar", "船で行く", "to sail", "ke pulau", "島へ"],
    ["terbang", "飛ぶ", "to fly", "ke Jakarta", "ジャカルタへ", "Pesawat itu", "その飛行機は"],
    ["mengalir", "流れる", "to flow", "ke laut", "海へ", "Sungai itu", "その川は"],
    ["berbunyi", "鳴る", "to sound", "keras", "大きく", "Telepon", "電話は"],
    ["menyala", "点く", "to be on", "di malam hari", "夜に", "Lampu", "電灯は"],
    ["padam", "消える", "to go out", "tiba-tiba", "突然", "Lampu", "電灯は"],
    ["terbuka", "開いている", "to be open", "sejak pagi", "朝から", "Pintu itu", "そのドアは"],
    ["tertutup", "閉まっている", "to be closed", "hari ini", "今日", "Toko itu", "その店は"],
    ["terlambat", "遅れる", "to be late", "ke sekolah", "学校に"],
    ["tertidur", "眠ってしまう", "to fall asleep", "di bus", "バスで"],
    ["terjatuh", "転ぶ、落ちる", "to fall", "di jalan", "道で"],
    ["tersesat", "道に迷う", "to get lost", "di kota", "町で"],
    ["terkejut", "驚く", "to be surprised", "karena suara", "音に"],
    ["terbakar", "燃える、焦げる", "to burn", "di dapur", "台所で", "Roti", "パンは"],
    ["terluka", "けがをする", "to be injured", "di kaki", "足に"],
    ["berjanji", "約束する", "to promise", "kepada teman", "友だちに"],
    ["berpikir", "考える", "to think", "tentang rencana", "計画について"],
    ["berharap", "期待する、望む", "to hope", "agar lulus", "合格することを"],
    ["berminat", "興味がある", "to be interested", "pada musik", "音楽に"],
    ["tertarik", "興味を持つ", "to be interested", "pada budaya", "文化に"],
    ["percaya", "信じる", "to believe", "kepada teman", "友だちを"],
    ["ragu", "迷う、疑う", "to doubt", "sedikit", "少し"],
    ["setuju", "賛成する", "to agree", "dengan ide itu", "その考えに"],
    ["menyerah", "あきらめる", "to give up", "sekarang", "今"],
    ["berkorban", "犠牲を払う", "to sacrifice", "untuk keluarga", "家族のために"],
    ["berkebun", "庭仕事をする", "to garden", "di halaman", "庭で"],
    ["berkemah", "キャンプする", "to camp", "di gunung", "山で"],
    ["berfoto", "写真を撮る", "to take a photo", "di pantai", "海岸で"],
    ["berkeliling", "歩き回る、巡る", "to go around", "di kota", "町を"]
  ];

  const functionWords = [
    ["sebagai", "〜として", "as", "前置詞", "Dia bekerja sebagai guru.", "彼は先生として働いています。"],
    ["seperti", "〜のように", "like; such as", "前置詞", "Rumah itu besar seperti hotel.", "その家はホテルのように大きいです。"],
    ["daripada", "〜よりも", "than", "前置詞", "Kopi lebih pahit daripada teh.", "コーヒーはお茶より苦いです。"],
    ["kepada", "〜へ、〜に", "to", "前置詞", "Saya memberi surat kepada guru.", "私は先生に手紙を渡します。"],
    ["oleh", "〜によって", "by", "前置詞", "Buku itu ditulis oleh guru.", "その本は先生によって書かれました。"],
    ["tanpa", "〜なしで", "without", "前置詞", "Saya pergi tanpa payung.", "私は傘なしで行きます。"],
    ["selama", "〜の間", "during; for", "前置詞", "Saya tinggal di Bali selama seminggu.", "私は1週間バリに滞在します。"],
    ["sejak", "〜以来", "since", "前置詞", "Saya belajar sejak tahun lalu.", "私は去年から勉強しています。"],
    ["sambil", "〜しながら", "while", "接続詞", "Saya makan sambil menonton TV.", "私はテレビを見ながら食べます。"],
    ["supaya", "〜するように", "so that", "接続詞", "Saya belajar supaya lulus ujian.", "私は試験に合格するように勉強します。"],
    ["agar", "〜するように", "so that", "接続詞", "Tolong datang pagi agar tidak terlambat.", "遅れないように朝来てください。"],
    ["sebelum itu", "その前に", "before that", "接続詞", "Sebelum itu, saya makan dulu.", "その前に、私は先に食べます。"],
    ["sesudah itu", "その後で", "after that", "接続詞", "Sesudah itu, kami pulang.", "その後で私たちは帰ります。"],
    ["walaupun", "〜だけれども", "although", "接続詞", "Walaupun hujan, saya pergi.", "雨だけれども、私は行きます。"],
    ["namun", "しかし", "however", "接続詞", "Dia sibuk, namun tetap datang.", "彼は忙しいですが、それでも来ます。"],
    ["jadi", "だから、つまり", "so; therefore", "接続詞", "Hari hujan, jadi saya di rumah.", "雨なので、私は家にいます。"],
    ["berarti", "つまり、意味する", "meaning; means", "接続詞", "Ini berarti kita harus menunggu.", "これは私たちが待たなければならないという意味です。"],
    ["yaitu", "すなわち", "namely", "接続詞", "Saya punya dua hobi, yaitu musik dan film.", "私には音楽と映画という2つの趣味があります。"],
    ["misalnya", "例えば", "for example", "接続詞", "Saya suka buah, misalnya mangga.", "私は果物、例えばマンゴーが好きです。"],
    ["selain itu", "そのほかに", "besides that", "接続詞", "Selain itu, harganya murah.", "そのほかに、値段が安いです。"],
    ["oleh karena itu", "そのため", "therefore", "接続詞", "Oleh karena itu, kami pulang.", "そのため、私たちは帰りました。"],
    ["bagaimanapun", "いずれにしても", "anyway; however", "接続詞", "Bagaimanapun, kita harus mencoba.", "いずれにしても、私たちは試すべきです。"],
    ["masing-masing", "それぞれ", "each", "副詞", "Masing-masing orang mendapat satu tiket.", "それぞれの人がチケットを1枚受け取ります。"],
    ["setiap", "毎〜、それぞれの", "each; every", "数詞", "Saya belajar setiap hari.", "私は毎日勉強します。"],
    ["beberapa", "いくつかの", "several", "数詞", "Saya membeli beberapa buku.", "私は本を数冊買います。"],
    ["sebagian", "一部", "part; some", "数詞", "Sebagian murid sudah pulang.", "生徒の一部はもう帰りました。"],
    ["separuh", "半分", "half", "数詞", "Saya makan separuh roti.", "私はパンを半分食べます。"],
    ["semacam", "一種の", "a kind of", "数詞", "Ini semacam obat tradisional.", "これは一種の伝統薬です。"],
    ["para", "〜たち", "plural marker", "数詞", "Para guru sedang rapat.", "先生たちは会議中です。"],
    ["seseorang", "誰か", "someone", "代名詞", "Seseorang menunggu di depan.", "誰かが前で待っています。"],
    ["sesuatu", "何か", "something", "代名詞", "Saya mencari sesuatu di tas.", "私はかばんの中で何かを探しています。"],
    ["siapa saja", "誰でも", "anyone", "代名詞", "Siapa saja boleh masuk.", "誰でも入れます。"],
    ["apa saja", "何でも", "anything", "代名詞", "Saya mau makan apa saja.", "私は何でも食べたいです。"],
    ["yang mana", "どちら、どれ", "which one", "疑問詞", "Yang mana milik Anda?", "どれがあなたのものですか。"],
    ["berapa lama", "どのくらいの期間", "how long", "疑問詞", "Berapa lama Anda tinggal di sini?", "あなたはここにどのくらい滞在しますか。"],
    ["berapa kali", "何回", "how many times", "疑問詞", "Berapa kali Anda ke Bali?", "あなたは何回バリへ行きましたか。"],
    ["jam berapa", "何時", "what time", "疑問詞", "Jam berapa kereta berangkat?", "電車は何時に出発しますか。"],
    ["bolehkah", "〜してもいいですか", "may I", "表現", "Bolehkah saya masuk?", "入ってもいいですか。"],
    ["maukah", "〜してくれますか", "would you", "表現", "Maukah Anda membantu saya?", "私を手伝ってくれますか。"],
    ["tidak apa-apa", "大丈夫です", "it is okay", "表現", "Tidak apa-apa, saya bisa menunggu.", "大丈夫です、私は待てます。"],
    ["hati-hati", "気をつけて", "be careful", "表現", "Hati-hati di jalan.", "道中気をつけてください。"],
    ["selamat jalan", "行ってらっしゃい、さようなら", "goodbye", "表現", "Selamat jalan, sampai jumpa.", "行ってらっしゃい、また会いましょう。"],
    ["selamat datang", "ようこそ", "welcome", "表現", "Selamat datang di Jakarta.", "ジャカルタへようこそ。"],
    ["selamat ulang tahun", "誕生日おめでとう", "happy birthday", "表現", "Selamat ulang tahun, Rina.", "リナさん、誕生日おめでとう。"],
    ["mohon maaf", "申し訳ありません", "please forgive me", "表現", "Mohon maaf, saya terlambat.", "申し訳ありません、遅れました。"],
    ["dengan senang hati", "喜んで", "with pleasure", "表現", "Dengan senang hati saya membantu.", "喜んでお手伝いします。"],
    ["sama-sama", "どういたしまして", "you are welcome", "表現", "Sama-sama, tidak apa-apa.", "どういたしまして、大丈夫です。"],
    ["apa kabar", "お元気ですか", "how are you", "表現", "Apa kabar hari ini?", "今日はお元気ですか。"],
    ["baik-baik saja", "元気です、大丈夫です", "fine", "表現", "Saya baik-baik saja.", "私は元気です。"]
  ];

  // 副詞は語順(動詞の前か後か)が語ごとに違うため、全行に例文を明記する。
  // [word, japanese, english, example, exampleJapanese]
  const adverbs = [
    ["pelan-pelan", "ゆっくり", "slowly", "Saya berjalan pelan-pelan.", "私はゆっくり歩きます。"],
    ["cepat-cepat", "急いで", "quickly", "Saya pulang cepat-cepat.", "私は急いで帰ります。"],
    ["sering", "よく、しばしば", "often", "Saya sering makan di warung itu.", "私はよくその食堂で食べます。"],
    ["jarang", "めったに〜ない", "rarely", "Saya jarang menonton TV.", "私はめったにテレビを見ません。"],
    ["kadang-kadang", "ときどき", "sometimes", "Kadang-kadang saya memasak sendiri.", "ときどき私は自分で料理します。"],
    ["selalu", "いつも", "always", "Dia selalu datang tepat waktu.", "彼はいつも時間どおりに来ます。"],
    ["biasanya", "ふつう、たいてい", "usually", "Biasanya saya bangun jam enam.", "ふつう私は6時に起きます。"],
    ["segera", "すぐに", "immediately", "Saya akan segera menghubungi Anda.", "すぐにあなたに連絡します。"],
    ["baru saja", "たった今", "just now", "Dia baru saja pulang.", "彼はたった今帰りました。"],
    ["hampir", "ほとんど、もう少しで", "almost", "Saya hampir terlambat.", "私はもう少しで遅れるところでした。"],
    ["kira-kira", "およそ", "approximately", "Perjalanan memakan waktu kira-kira satu jam.", "移動にはおよそ1時間かかります。"],
    ["sekitar", "約、周辺に", "around", "Saya menunggu sekitar sepuluh menit.", "私は約10分待ちます。"],
    ["terlalu", "〜すぎる", "too", "Tas ini terlalu berat.", "このかばんは重すぎます。"],
    ["cukup", "かなり、十分に", "enough; quite", "Kamar ini cukup luas.", "この部屋はかなり広いです。"],
    ["sangat", "とても", "very", "Makanan ini sangat enak.", "この料理はとてもおいしいです。"],
    ["sekali", "とても", "very", "Pemandangannya bagus sekali.", "景色はとてもすばらしいです。"],
    ["lebih dulu", "先に", "first; beforehand", "Silakan masuk lebih dulu.", "先にお入りください。"],
    ["nanti malam", "今夜あとで", "later tonight", "Saya akan menelepon nanti malam.", "今夜あとで電話します。"],
    ["besok pagi", "明日の朝", "tomorrow morning", "Kami berangkat besok pagi.", "私たちは明日の朝出発します。"],
    ["kemarin sore", "昨日の夕方", "yesterday afternoon", "Saya tiba kemarin sore.", "私は昨日の夕方到着しました。"],
    ["minggu depan", "来週", "next week", "Ujian dimulai minggu depan.", "試験は来週始まります。"],
    ["bulan depan", "来月", "next month", "Saya pindah bulan depan.", "私は来月引っ越します。"],
    ["tahun depan", "来年", "next year", "Dia akan menikah tahun depan.", "彼は来年結婚します。"],
    ["minggu lalu", "先週", "last week", "Saya bertemu dia minggu lalu.", "私は先週彼に会いました。"],
    ["bulan lalu", "先月", "last month", "Toko itu buka bulan lalu.", "その店は先月開店しました。"],
    ["tahun lalu", "去年", "last year", "Kami pindah ke sini tahun lalu.", "私たちは去年ここへ引っ越しました。"],
    ["di sini", "ここで、ここに", "here", "Silakan tunggu di sini.", "ここでお待ちください。"],
    ["di sana", "そこで、そこに", "there", "Dia bekerja di sana.", "彼はそこで働いています。"],
    ["di situ", "そこで、そこに", "there", "Taruh tas Anda di situ.", "かばんはそこに置いてください。"],
    ["ke sini", "こちらへ", "to here", "Tolong datang ke sini.", "こちらへ来てください。"],
    ["ke sana", "あちらへ", "to there", "Kami akan pergi ke sana besok.", "私たちは明日あちらへ行きます。"],
    ["dari sini", "ここから", "from here", "Stasiun terlihat dari sini.", "ここから駅が見えます。"],
    ["dari sana", "そこから", "from there", "Dia baru kembali dari sana.", "彼はそこから戻ったばかりです。"],
    ["bersama-sama", "一緒に", "together", "Kami belajar bersama-sama.", "私たちは一緒に勉強します。"],
    ["sendirian", "一人で", "alone", "Saya tinggal sendirian.", "私は一人で暮らしています。"],
    ["diam-diam", "黙って、こっそり", "quietly", "Dia keluar diam-diam.", "彼はこっそり出て行きました。"],
    ["terus", "続けて、ずっと", "continuously", "Hujan turun terus.", "雨がずっと降り続いています。"],
    ["langsung", "直接、すぐに", "directly", "Setelah rapat, saya langsung pulang.", "会議の後、私はすぐに帰ります。"],
    ["sebaiknya", "〜したほうがよい", "had better", "Sebaiknya Anda istirahat dulu.", "まず休んだほうがいいですよ。"],
    ["seharusnya", "本来〜すべき", "should", "Seharusnya dia sudah tiba.", "本来なら彼はもう着いているはずです。"],
    ["mungkin", "たぶん", "maybe", "Mungkin dia sedang sibuk.", "たぶん彼は忙しいのでしょう。"],
    ["pasti", "きっと、必ず", "certainly", "Saya pasti datang.", "私は必ず行きます。"],
    ["tentu saja", "もちろん", "of course", "Tentu saja saya mau membantu.", "もちろん私は手伝いたいです。"],
    ["sebenarnya", "実は", "actually", "Sebenarnya saya kurang setuju.", "実は私はあまり賛成ではありません。"],
    ["akhirnya", "ついに", "finally", "Akhirnya bus itu datang.", "ついにそのバスが来ました。"],
    ["mulanya", "最初は", "at first", "Mulanya saya tidak mengerti.", "最初は私は分かりませんでした。"],
    ["kemudian", "その後", "then", "Saya makan, kemudian belajar.", "私は食べて、その後勉強します。"],
    ["lalu", "それから", "then", "Dia mandi, lalu tidur.", "彼はシャワーを浴びて、それから寝ます。"],
    ["baru", "〜したばかり", "just", "Saya baru sampai di rumah.", "私は家に着いたばかりです。"],
    ["masih", "まだ", "still", "Saya masih menunggu jawaban.", "私はまだ返事を待っています。"],
    ["pernah", "〜したことがある", "ever", "Saya pernah tinggal di Bali.", "私はバリに住んだことがあります。"],
    ["belum pernah", "まだ〜したことがない", "never yet", "Saya belum pernah makan durian.", "私はまだドリアンを食べたことがありません。"],
    ["sudah pernah", "すでに〜したことがある", "have ever", "Saya sudah pernah ke sana.", "私はそこへ行ったことがあります。"],
    ["tidak pernah", "一度も〜ない", "never", "Dia tidak pernah terlambat.", "彼は一度も遅れたことがありません。"],
    ["boleh", "〜してよい", "may", "Anda boleh duduk di sini.", "あなたはここに座ってもいいです。"],
    ["harus", "〜しなければならない", "must", "Saya harus berangkat sekarang.", "私は今出発しなければなりません。"],
    ["dapat", "〜できる", "can", "Anda dapat membayar dengan kartu.", "あなたはカードで支払うことができます。"],
    ["bisa", "〜できる", "can", "Saya bisa berbicara bahasa Indonesia sedikit.", "私は少しインドネシア語が話せます。"],
    ["akan", "〜するつもり、〜だろう", "will", "Saya akan mengirim email besok.", "私は明日メールを送ります。"],
    ["sedang", "〜しているところ", "currently", "Dia sedang mandi.", "彼はシャワーを浴びているところです。"],
    ["sedikit lagi", "もう少しで", "almost", "Sedikit lagi pekerjaan ini selesai.", "もう少しでこの仕事は終わります。"],
    ["begitu", "そのように", "like that", "Jangan berbicara begitu.", "そんなふうに話さないでください。"],
    ["begini", "このように", "like this", "Caranya begini.", "やり方はこうです。"],
    ["barangkali", "おそらく", "perhaps", "Barangkali dia lupa janji.", "おそらく彼は約束を忘れたのでしょう。"]
  ];

  const months = [
    ["Januari", "1月", "January"], ["Februari", "2月", "February"], ["Maret", "3月", "March"], ["April", "4月", "April"],
    ["Mei", "5月", "May"], ["Juni", "6月", "June"], ["Juli", "7月", "July"], ["Agustus", "8月", "August"],
    ["September", "9月", "September"], ["Oktober", "10月", "October"], ["November", "11月", "November"], ["Desember", "12月", "December"]
  ];

  const numberWords = [
    ["tiga belas", "13", "thirteen"], ["empat belas", "14", "fourteen"], ["lima belas", "15", "fifteen"], ["enam belas", "16", "sixteen"],
    ["tujuh belas", "17", "seventeen"], ["delapan belas", "18", "eighteen"], ["sembilan belas", "19", "nineteen"], ["dua puluh", "20", "twenty"],
    ["tiga puluh", "30", "thirty"], ["empat puluh", "40", "forty"], ["lima puluh", "50", "fifty"], ["enam puluh", "60", "sixty"],
    ["tujuh puluh", "70", "seventy"], ["delapan puluh", "80", "eighty"], ["sembilan puluh", "90", "ninety"], ["dua ratus", "200", "two hundred"],
    ["seribu", "1000", "one thousand"], ["sejuta", "100万", "one million"]
  ];

  // 形容詞は主語との組み合わせで不自然になりやすいため、全行に例文を明記する。
  // [word, japanese, english, example, exampleJapanese]
  const adjectives = [
    ["aman", "安全な", "safe", "Daerah ini aman.", "この地域は安全です。"],
    ["berbahaya", "危険な", "dangerous", "Jalan itu berbahaya.", "その道は危険です。"],
    ["sibuk", "忙しい", "busy", "Saya sibuk hari ini.", "私は今日忙しいです。"],
    ["kosong", "空の、空いている", "empty", "Kamar itu kosong.", "その部屋は空いています。"],
    ["penuh", "満員の、いっぱいの", "full", "Bus itu penuh.", "そのバスは満員です。"],
    ["sempit", "狭い", "narrow", "Kamar ini sempit.", "この部屋は狭いです。"],
    ["luas", "広い", "wide; spacious", "Rumah itu luas.", "その家は広いです。"],
    ["berat", "重い", "heavy", "Koper ini berat.", "このスーツケースは重いです。"],
    ["ringan", "軽い", "light", "Tas ini ringan.", "このかばんは軽いです。"],
    ["tebal", "厚い", "thick", "Buku ini tebal.", "この本は厚いです。"],
    ["tipis", "薄い", "thin", "Dompet saya tipis.", "私の財布は薄いです。"],
    ["keras", "硬い、激しい", "hard; loud", "Roti ini keras.", "このパンは硬いです。"],
    ["lembut", "柔らかい", "soft", "Kain ini lembut.", "この布は柔らかいです。"],
    ["halus", "なめらかな、細かい", "smooth", "Permukaannya halus.", "表面はなめらかです。"],
    ["kasar", "粗い、乱暴な", "rough", "Kertas ini kasar.", "この紙はざらざらしています。"],
    ["tajam", "鋭い", "sharp", "Pisau ini tajam.", "このナイフは鋭いです。"],
    ["tumpul", "鈍い", "blunt", "Gunting ini tumpul.", "このはさみは切れ味が悪いです。"],
    ["licin", "滑りやすい", "slippery", "Jalan itu licin setelah hujan.", "その道は雨の後滑りやすいです。"],
    ["basah", "濡れた", "wet", "Baju saya basah.", "私の服は濡れています。"],
    ["kering", "乾いた", "dry", "Handuk ini sudah kering.", "このタオルはもう乾いています。"],
    ["segar", "新鮮な、さわやかな", "fresh", "Sayur ini segar.", "この野菜は新鮮です。"],
    ["busuk", "腐った", "rotten", "Buah itu busuk.", "その果物は腐っています。"],
    ["matang", "熟した、火が通った", "ripe; cooked", "Pisang ini sudah matang.", "このバナナはもう熟しています。"],
    ["mentah", "生の、未加工の", "raw", "Daging itu masih mentah.", "その肉はまだ生です。"],
    ["asin", "塩辛い", "salty", "Sup ini terlalu asin.", "このスープは塩辛すぎます。"],
    ["asam", "酸っぱい", "sour", "Jeruk ini asam.", "このみかんは酸っぱいです。"],
    ["pahit", "苦い", "bitter", "Obat ini pahit.", "この薬は苦いです。"],
    ["gurih", "うま味のある", "savory", "Ayam goreng ini gurih.", "この揚げ鶏はうま味があります。"],
    ["lezat", "とてもおいしい", "delicious", "Masakan ibu lezat.", "母の料理はとてもおいしいです。"],
    ["hangat", "暖かい", "warm", "Air ini hangat.", "この水は温かいです。"],
    ["sejuk", "涼しい", "cool", "Udara pagi sejuk.", "朝の空気は涼しいです。"],
    ["gelap", "暗い", "dark", "Kamar itu gelap.", "その部屋は暗いです。"],
    ["terang", "明るい", "bright", "Ruangan ini terang.", "この部屋は明るいです。"],
    ["ribut", "騒がしい", "noisy", "Kelas itu ribut.", "その教室は騒がしいです。"],
    ["tenang", "落ち着いた、静かな", "calm", "Tempat ini tenang.", "この場所は落ち着いています。"],
    ["nyaman", "快適な", "comfortable", "Hotel itu nyaman.", "そのホテルは快適です。"],
    ["lengkap", "完全な、そろった", "complete", "Dokumennya sudah lengkap.", "書類はもうそろっています。"],
    ["kurang", "足りない", "lacking", "Waktunya kurang.", "時間が足りません。"],
    ["sederhana", "簡単な、質素な", "simple", "Rumah itu sederhana.", "その家は質素です。"],
    ["mewah", "豪華な", "luxurious", "Hotel itu mewah.", "そのホテルは豪華です。"],
    ["modern", "現代的な", "modern", "Gedung ini modern.", "この建物は現代的です。"],
    ["tradisional", "伝統的な", "traditional", "Pasar itu tradisional.", "その市場は伝統的です。"],
    ["terkenal", "有名な", "famous", "Restoran ini terkenal.", "このレストランは有名です。"],
    ["biasa", "普通の", "ordinary", "Ini hari biasa.", "今日は普通の日です。"],
    ["luar biasa", "並外れた", "extraordinary", "Pemandangannya luar biasa.", "景色は並外れてすばらしいです。"],
    ["penting", "重要な", "important", "Rapat ini penting.", "この会議は重要です。"],
    ["berguna", "役に立つ", "useful", "Kamus ini berguna.", "この辞書は役に立ちます。"],
    ["sia-sia", "無駄な", "useless", "Usahanya tidak sia-sia.", "彼の努力は無駄ではありません。"],
    ["jelas", "明らかな", "clear", "Penjelasannya jelas.", "説明は明快です。"],
    ["kabur", "ぼんやりした", "unclear; blurry", "Fotonya kabur.", "写真はぼやけています。"],
    ["siap", "準備できた", "ready", "Makanan sudah siap.", "食事はもう準備できています。"],
    ["capek", "疲れた", "tired", "Saya capek setelah bekerja.", "私は仕事の後疲れています。"],
    ["lelah", "疲れた", "tired", "Badan saya lelah.", "体が疲れています。"],
    ["mengantuk", "眠い", "sleepy", "Saya mengantuk di kelas.", "私は授業中眠いです。"],
    ["takut", "怖い", "afraid", "Anak itu takut anjing.", "その子は犬が怖いです。"],
    ["marah", "怒った", "angry", "Ayah marah kepada saya.", "父は私に怒っています。"],
    ["malu", "恥ずかしい", "embarrassed", "Saya malu berbicara di depan orang banyak.", "私は大勢の前で話すのが恥ずかしいです。"],
    ["bangga", "誇りに思う", "proud", "Ibu bangga kepada anaknya.", "母は子どもを誇りに思っています。"],
    ["khawatir", "心配な", "worried", "Saya khawatir tentang ujian.", "私は試験が心配です。"],
    ["tenar", "有名な", "popular", "Penyanyi itu tenar.", "その歌手は有名です。"],
    ["ramah", "親しみやすい", "friendly", "Orang-orang di sini ramah.", "ここの人々は親切です。"],
    ["sopan", "礼儀正しい", "polite", "Anak itu sopan.", "その子は礼儀正しいです。"],
    ["jujur", "正直な", "honest", "Dia orang yang jujur.", "彼は正直な人です。"],
    ["nakal", "いたずらな", "naughty", "Kucing itu nakal.", "その猫はいたずら好きです。"],
    ["rajin", "勤勉な", "diligent", "Murid itu rajin belajar.", "その生徒は熱心に勉強します。"],
    ["malas", "怠けた", "lazy", "Saya malas keluar hari ini.", "私は今日出かけるのが面倒です。"],
    ["pintar", "賢い", "smart", "Anak itu pintar.", "その子は賢いです。"],
    ["bodoh", "愚かな", "stupid", "Keputusan itu bodoh.", "その決定は愚かです。"],
    ["kaya", "裕福な", "rich", "Keluarga itu kaya.", "その家族は裕福です。"],
    ["miskin", "貧しい", "poor", "Daerah itu masih miskin.", "その地域はまだ貧しいです。"],
    ["gratis", "無料の", "free of charge", "Tiket masuknya gratis.", "入場券は無料です。"],
    ["terakhir", "最後の", "last", "Ini halaman terakhir.", "これは最後のページです。"],
    ["pertama", "最初の", "first", "Ini kunjungan pertama saya.", "これは私の初めての訪問です。"],
    ["kedua", "2番目の", "second", "Anak kedua saya masih kecil.", "私の2番目の子はまだ小さいです。"],
    ["ketiga", "3番目の", "third", "Dia duduk di baris ketiga.", "彼は3列目に座っています。"],
    ["sendiri", "自分自身の、一人で", "own; alone", "Saya datang sendiri.", "私は一人で来ました。"],
    ["bersama", "一緒の", "together", "Kami makan malam bersama.", "私たちは一緒に夕食を食べます。"],
    ["lain", "他の", "other", "Saya mau melihat yang lain.", "他のものを見たいです。"],
    ["sama", "同じ", "same", "Harganya sama.", "値段は同じです。"],
    ["berbeda", "異なる", "different", "Pendapat kami berbeda.", "私たちの意見は異なります。"],
    ["bening", "澄んだ", "clear", "Air sungai itu bening.", "その川の水は澄んでいます。"],
    ["keruh", "濁った", "cloudy", "Airnya keruh setelah hujan.", "雨の後、水は濁っています。"],
    ["rapi", "整った", "neat", "Kamarnya selalu rapi.", "彼の部屋はいつも整っています。"],
    ["berantakan", "散らかった", "messy", "Meja saya berantakan.", "私の机は散らかっています。"],
    ["rusak", "壊れた", "broken", "Ponsel saya rusak.", "私の携帯電話は壊れています。"],
    ["lama", "長い、古い", "long; old", "Saya menunggu lama.", "私は長い間待ちました。"],
    ["sementara", "一時的な", "temporary", "Ini alamat sementara saya.", "これは私の一時的な住所です。"],
    ["tetap", "固定の、変わらない", "fixed", "Harganya tetap.", "値段は変わりません。"]
  ];

  // 名詞も語ごとに自然な文が異なるため、全行に例文を明記する。
  // [word, japanese, english, example, exampleJapanese]
  const nouns = [
    ["alamat", "住所", "address", "Saya perlu alamat hotel itu.", "私はそのホテルの住所が必要です。"],
    ["desa wisata", "観光村", "tourist village", "Kami mengunjungi desa wisata.", "私たちは観光村を訪れます。"],
    ["nomor", "番号", "number", "Nomor kamar saya 302.", "私の部屋番号は302です。"],
    ["nomor telepon", "電話番号", "telephone number", "Boleh saya minta nomor telepon Anda?", "電話番号を教えてもらえますか。"],
    ["email", "メール", "email", "Saya akan mengirim email besok.", "私は明日メールを送ります。"],
    ["surat", "手紙", "letter", "Saya menulis surat untuk teman.", "私は友だちに手紙を書きます。"],
    ["pesan", "伝言、メッセージ", "message", "Ada pesan untuk Anda.", "あなたに伝言があります。"],
    ["paket", "荷物、小包", "package", "Paket itu sudah tiba.", "その小包はもう届きました。"],
    ["kartu", "カード", "card", "Saya membayar dengan kartu.", "私はカードで支払います。"],
    ["kartu nama", "名刺", "business card", "Ini kartu nama saya.", "これは私の名刺です。"],
    ["kartu identitas", "身分証", "identity card", "Tolong bawa kartu identitas.", "身分証を持って来てください。"],
    ["KTP", "住民身分証", "Indonesian ID card", "Dia menunjukkan KTP di loket.", "彼は窓口で身分証を見せます。"],
    ["SIM", "運転免許証", "driver's license", "Saya belum punya SIM.", "私はまだ運転免許証を持っていません。"],
    ["visa", "ビザ", "visa", "Visa saya berlaku satu tahun.", "私のビザは1年間有効です。"],
    ["izin", "許可", "permission", "Saya minta izin kepada guru.", "私は先生に許可をもらいます。"],
    ["syarat", "条件", "requirement", "Apa syarat pendaftaran ini?", "この登録の条件は何ですか。"],
    ["tanda tangan", "署名", "signature", "Tulis tanda tangan di sini.", "ここに署名してください。"],
    ["foto", "写真", "photo", "Saya melihat foto keluarga.", "私は家族の写真を見ます。"],
    ["dokumen", "書類", "document", "Dokumen itu ada di tas saya.", "その書類は私のかばんにあります。"],
    ["salinan", "コピー、写し", "copy", "Saya perlu salinan paspor.", "私はパスポートの写しが必要です。"],
    ["asli", "原本、本物", "original", "Ini dokumen asli.", "これは原本です。"],
    ["daftar", "リスト、名簿", "list", "Nama saya ada di daftar.", "私の名前はリストにあります。"],
    ["jadwal", "予定、スケジュール", "schedule", "Jadwal hari ini penuh.", "今日の予定はいっぱいです。"],
    ["janji", "約束、予約", "promise; appointment", "Saya punya janji jam tiga.", "私は3時に約束があります。"],
    ["undangan", "招待状", "invitation", "Saya menerima undangan pesta.", "私はパーティーの招待状を受け取ります。"],
    ["acara", "行事、イベント", "event", "Ada acara besar besok.", "明日大きな行事があります。"],
    ["pesta", "パーティー", "party", "Kami mengadakan pesta kecil.", "私たちは小さなパーティーを開きます。"],
    ["rapat", "会議", "meeting", "Rapat dimulai jam sembilan.", "会議は9時に始まります。"],
    ["kelas malam", "夜間クラス", "evening class", "Saya mengikuti kelas malam.", "私は夜間クラスに参加します。"],
    ["kursus", "講座", "course", "Saya ikut kursus bahasa.", "私は語学講座に参加します。"],
    ["ujian", "試験", "exam", "Saya punya ujian besok.", "私は明日試験があります。"],
    ["nilai", "点数、価値", "score; value", "Nilai saya bagus.", "私の点数は良いです。"],
    ["jawaban", "答え", "answer", "Jawaban ini benar.", "この答えは正しいです。"],
    ["pertanyaan", "質問", "question", "Saya punya pertanyaan.", "私は質問があります。"],
    ["latihan", "練習", "practice", "Saya perlu banyak latihan.", "私はたくさんの練習が必要です。"],
    ["tugas", "課題、仕事", "task", "Tugas ini sulit.", "この課題は難しいです。"],
    ["pelajaran", "授業、学課", "lesson", "Saya suka pelajaran ini.", "私はこの授業が好きです。"],
    ["kamus", "辞書", "dictionary", "Saya perlu kamus baru.", "私は新しい辞書が必要です。"],
    ["arti", "意味", "meaning", "Apa arti kata ini?", "この単語の意味は何ですか。"],
    ["kalimat", "文", "sentence", "Kalimat ini panjang.", "この文は長いです。"],
    ["huruf", "文字", "letter", "Huruf ini terlalu kecil.", "この文字は小さすぎます。"],
    ["suara", "声、音", "voice; sound", "Suara itu keras.", "その音は大きいです。"],
    ["lagu", "歌", "song", "Saya suka lagu ini.", "私はこの歌が好きです。"],
    ["musik", "音楽", "music", "Kami mendengarkan musik.", "私たちは音楽を聞きます。"],
    ["film", "映画", "movie", "Kami menonton film di rumah.", "私たちは家で映画を見ます。"],
    ["berita", "ニュース", "news", "Saya membaca berita pagi ini.", "私は今朝ニュースを読みます。"],
    ["koran", "新聞", "newspaper", "Ayah membaca koran.", "父は新聞を読みます。"],
    ["majalah", "雑誌", "magazine", "Saya membeli majalah di stasiun.", "私は駅で雑誌を買います。"],
    ["iklan", "広告", "advertisement", "Saya melihat iklan itu di TV.", "私はその広告をテレビで見ます。"],
    ["papan petunjuk", "案内板", "signboard", "Lihat papan petunjuk itu.", "その案内板を見てください。"],
    ["tanda", "印、標識", "sign; mark", "Apa arti tanda ini?", "この標識の意味は何ですか。"],
    ["rambu", "標識", "traffic sign", "Perhatikan rambu di jalan.", "道路の標識に注意してください。"],
    ["lampu lalu lintas", "信号", "traffic light", "Berhenti di lampu lalu lintas.", "信号で止まってください。"],
    ["trotoar", "歩道", "sidewalk", "Kami berjalan di trotoar.", "私たちは歩道を歩きます。"],
    ["perempatan", "十字路", "intersection", "Belok kiri di perempatan.", "十字路で左に曲がってください。"],
    ["pertigaan", "三叉路", "three-way intersection", "Rumah saya dekat pertigaan.", "私の家は三叉路の近くです。"],
    ["tikungan", "曲がり角", "bend; turn", "Hati-hati di tikungan.", "曲がり角では気をつけてください。"],
    ["arah", "方向", "direction", "Kami berjalan ke arah stasiun.", "私たちは駅の方向へ歩きます。"],
    ["kanan", "右", "right", "Belok kanan di perempatan.", "十字路で右に曲がってください。"],
    ["kiri", "左", "left", "Toko itu ada di sebelah kiri.", "その店は左側にあります。"],
    ["utara", "北", "north", "Kota itu ada di utara Jakarta.", "その町はジャカルタの北にあります。"],
    ["selatan", "南", "south", "Angin bertiup dari selatan.", "風は南から吹きます。"],
    ["timur", "東", "east", "Matahari terbit di timur.", "太陽は東から昇ります。"],
    ["barat", "西", "west", "Kamar ini menghadap ke barat.", "この部屋は西向きです。"],
    ["pusat kota", "市中心部", "city center", "Hotel itu ada di pusat kota.", "そのホテルは市中心部にあります。"],
    ["pinggir kota", "郊外", "outskirts", "Mereka tinggal di pinggir kota.", "彼らは郊外に住んでいます。"],
    ["daerah", "地域", "area", "Saya tinggal di daerah ini.", "私はこの地域に住んでいます。"],
    ["provinsi", "州、県", "province", "Bali adalah nama provinsi.", "バリは州の名前です。"],
    ["pulau", "島", "island", "Indonesia punya banyak pulau.", "インドネシアには多くの島があります。"],
    ["danau", "湖", "lake", "Kami berenang di danau.", "私たちは湖で泳ぎます。"],
    ["hutan", "森", "forest", "Hutan itu luas.", "その森は広いです。"],
    ["sawah", "田んぼ", "rice field", "Petani bekerja di sawah.", "農民は田んぼで働きます。"],
    ["kebun", "畑、庭園", "garden; plantation", "Kebun itu luas.", "その畑は広いです。"],
    ["lapangan", "広場、グラウンド", "field", "Anak-anak bermain di lapangan.", "子どもたちは広場で遊びます。"],
    ["kolam", "池、プール", "pond; pool", "Ada ikan di kolam.", "池には魚がいます。"],
    ["kolam renang", "プール", "swimming pool", "Kami berenang di kolam renang.", "私たちはプールで泳ぎます。"],
    ["gedung", "建物", "building", "Gedung itu tinggi.", "その建物は高いです。"],
    ["lantai", "床、階", "floor", "Lantai ini bersih.", "この床は清潔です。"],
    ["atap", "屋根", "roof", "Atap rumah itu merah.", "その家の屋根は赤いです。"],
    ["dinding", "壁", "wall", "Dinding kamar saya putih.", "私の部屋の壁は白いです。"],
    ["tangga", "階段", "stairs", "Naik tangga ke lantai dua.", "階段で2階へ上がってください。"],
    ["lift", "エレベーター", "elevator", "Lift ada di sebelah kiri.", "エレベーターは左側にあります。"],
    ["gudang", "倉庫", "warehouse", "Barang itu ada di gudang.", "その品物は倉庫にあります。"],
    ["ruang tamu", "居間、客間", "living room", "Tamu menunggu di ruang tamu.", "客は居間で待っています。"],
    ["ruang makan", "食堂", "dining room", "Kami makan di ruang makan.", "私たちは食堂で食べます。"],
    ["kamar mandi", "浴室、トイレ", "bathroom", "Kamar mandi ada di belakang.", "浴室は奥にあります。"],
    ["garasi", "車庫", "garage", "Mobil ada di garasi.", "車は車庫にあります。"],
    ["kos", "下宿", "boarding room", "Saya tinggal di kos.", "私は下宿に住んでいます。"],
    ["apartemen", "アパート", "apartment", "Dia tinggal di apartemen.", "彼はアパートに住んでいます。"],
    ["kontrakan", "賃貸住宅", "rental house", "Kami mencari kontrakan murah.", "私たちは安い賃貸住宅を探しています。"],
    ["sewa", "賃貸、賃料", "rent", "Sewa kamar ini murah.", "この部屋の家賃は安いです。"],
    ["biaya", "費用", "cost", "Biaya sekolah naik.", "学費が上がります。"],
    ["ongkos", "料金、運賃", "fare; fee", "Berapa ongkos bus ke kota?", "町行きのバス運賃はいくらですか。"],
    ["tarif", "料金表、料金", "tariff; rate", "Tarif taksi naik.", "タクシー料金が上がります。"],
    ["diskon", "割引", "discount", "Ada diskon hari ini?", "今日は割引がありますか。"],
    ["kembalian", "お釣り", "change", "Ini kembalian Anda.", "こちらがお釣りです。"],
    ["struk", "レシート", "receipt", "Boleh saya minta struk?", "レシートをもらえますか。"],
    ["nota", "伝票、領収書", "note; receipt", "Minta nota, ya.", "伝票をください。"],
    ["barang", "品物", "goods", "Barang ini bagus.", "この品物は良いです。"],
    ["produk", "製品", "product", "Produk ini baru.", "この製品は新しいです。"],
    ["ukuran", "サイズ", "size", "Ada ukuran yang lebih besar?", "もっと大きいサイズはありますか。"],
    ["tinggi badan", "身長", "height", "Tinggi badan saya 170 senti.", "私の身長は170センチです。"],
    ["bahan", "材料", "material", "Bahan baju ini halus.", "この服の生地はなめらかです。"],
    ["kualitas", "品質", "quality", "Kualitasnya bagus.", "品質は良いです。"],
    ["merek", "ブランド", "brand", "Merek ini terkenal.", "このブランドは有名です。"],
    ["pelanggan", "客、顧客", "customer", "Toko itu punya banyak pelanggan.", "その店には多くの顧客がいます。"],
    ["kasir", "レジ係", "cashier", "Silakan bayar di kasir.", "レジでお支払いください。"],
    ["toko buku", "書店", "bookstore", "Saya pergi ke toko buku.", "私は書店へ行きます。"],
    ["apotek", "薬局", "pharmacy", "Saya membeli obat di apotek.", "私は薬局で薬を買います。"],
    ["warung", "小さな店、食堂", "small shop; food stall", "Kami makan di warung.", "私たちは食堂で食べます。"],
    ["minimarket", "コンビニ、小型スーパー", "minimarket", "Ada minimarket dekat sini?", "近くにコンビニはありますか。"],
    ["pusat perbelanjaan", "ショッピングセンター", "shopping center", "Pusat perbelanjaan itu ramai.", "そのショッピングセンターは混んでいます。"],
    ["lantai dua", "2階", "second floor", "Toko buku ada di lantai dua.", "書店は2階にあります。"],
    ["pintu masuk", "入口", "entrance", "Pintu masuk ada di sebelah kanan.", "入口は右側にあります。"],
    ["pintu keluar", "出口", "exit", "Di mana pintu keluar?", "出口はどこですか。"],
    ["loket", "窓口", "ticket counter", "Silakan bayar di loket.", "窓口でお支払いください。"],
    ["antrean", "列", "queue", "Antrean di bank panjang.", "銀行の列は長いです。"],
    ["nomor antrean", "受付番号", "queue number", "Ambil nomor antrean dulu.", "まず受付番号を取ってください。"],
    ["koper", "スーツケース", "suitcase", "Koper saya berat.", "私のスーツケースは重いです。"],
    ["dompet", "財布", "wallet", "Dompet saya ada di tas.", "私の財布はかばんの中にあります。"],
    ["payung", "傘", "umbrella", "Jangan lupa membawa payung.", "傘を持って行くのを忘れないでください。"],
    ["jas hujan", "レインコート", "raincoat", "Saya memakai jas hujan.", "私はレインコートを着ます。"],
    ["kacamata", "眼鏡", "glasses", "Kacamata saya baru.", "私の眼鏡は新しいです。"],
    ["kamera", "カメラ", "camera", "Saya membawa kamera ke Bali.", "私はバリへカメラを持って行きます。"],
    ["charger", "充電器", "charger", "Saya lupa membawa charger.", "私は充電器を持って来るのを忘れました。"],
    ["baterai", "電池", "battery", "Baterai ponsel saya habis.", "私の携帯の電池が切れました。"],
    ["layar", "画面", "screen", "Layar ponsel saya rusak.", "私の携帯の画面は壊れています。"],
    ["tombol", "ボタン", "button", "Tekan tombol merah itu.", "その赤いボタンを押してください。"],
    ["mesin", "機械", "machine", "Mesin ini rusak.", "この機械は壊れています。"],
    ["alat", "道具", "tool", "Alat ini mudah dipakai.", "この道具は使いやすいです。"],
    ["sikat gigi", "歯ブラシ", "toothbrush", "Saya membeli sikat gigi baru.", "私は新しい歯ブラシを買います。"],
    ["pasta gigi", "歯磨き粉", "toothpaste", "Pasta gigi ada di kamar mandi.", "歯磨き粉は浴室にあります。"],
    ["sampo", "シャンプー", "shampoo", "Sampo ini wangi.", "このシャンプーは良い香りです。"],
    ["tisu", "ティッシュ", "tissue", "Boleh saya minta tisu?", "ティッシュをもらえますか。"],
    ["sapu", "ほうき", "broom", "Saya menyapu lantai dengan sapu.", "私はほうきで床を掃きます。"],
    ["pel", "モップ", "mop", "Pel itu ada di dapur.", "モップは台所にあります。"],
    ["ember", "バケツ", "bucket", "Isi ember ini dengan air.", "このバケツに水を入れてください。"],
    ["piring", "皿", "plate", "Piring itu sudah bersih.", "その皿はもうきれいです。"],
    ["mangkuk", "茶碗、ボウル", "bowl", "Sup ada di mangkuk.", "スープはボウルに入っています。"],
    ["gelas", "コップ", "glass", "Saya minum air dari gelas.", "私はコップで水を飲みます。"],
    ["sendok", "スプーン", "spoon", "Saya makan dengan sendok.", "私はスプーンで食べます。"],
    ["garpu", "フォーク", "fork", "Boleh minta garpu?", "フォークをもらえますか。"],
    ["kompor", "コンロ", "stove", "Ibu memasak dengan kompor.", "母はコンロで料理します。"],
    ["panci", "鍋", "pot", "Panci itu besar.", "その鍋は大きいです。"],
    ["wajan", "フライパン", "frying pan", "Saya menggoreng telur di wajan.", "私はフライパンで卵を焼きます。"],
    ["minyak goreng", "食用油", "cooking oil", "Minyak goreng hampir habis.", "食用油がもうすぐなくなります。"],
    ["tepung", "小麦粉、粉", "flour", "Kue ini dibuat dari tepung.", "このお菓子は小麦粉から作られます。"],
    ["beras", "米", "rice grain", "Ibu membeli beras di pasar.", "母は市場で米を買います。"],
    ["bumbu", "調味料", "seasoning", "Masakan ini pakai banyak bumbu.", "この料理はたくさんの調味料を使います。"],
    ["saus", "ソース", "sauce", "Saya suka saus pedas.", "私は辛いソースが好きです。"],
    ["kecap", "しょうゆ風ソース", "soy sauce", "Tambahkan sedikit kecap.", "ケチャップマニスを少し加えてください。"],
    ["cuka", "酢", "vinegar", "Cuka ini terlalu asam.", "この酢は酸っぱすぎます。"],
    ["keju", "チーズ", "cheese", "Roti ini pakai keju.", "このパンにはチーズが入っています。"],
    ["mentega", "バター", "butter", "Oleskan mentega pada roti.", "パンにバターを塗ってください。"],
    ["kentang", "じゃがいも", "potato", "Ibu merebus kentang.", "母はじゃがいもをゆでます。"],
    ["wortel", "にんじん", "carrot", "Wortel ini segar.", "このにんじんは新鮮です。"],
    ["tomat", "トマト", "tomato", "Saya memotong tomat.", "私はトマトを切ります。"],
    ["bawang", "玉ねぎ、にんにく類", "onion; garlic", "Bawang ini pedas.", "この玉ねぎは辛いです。"],
    ["cabai", "唐辛子", "chili", "Jangan pakai banyak cabai.", "唐辛子をたくさん使わないでください。"],
    ["kelapa", "ココナツ", "coconut", "Air kelapa ini segar.", "このココナツジュースはさわやかです。"],
    ["kacang", "豆、ナッツ", "bean; nut", "Saya suka kacang goreng.", "私は揚げた豆が好きです。"],
    ["udang", "えび", "shrimp", "Udang ini besar.", "このえびは大きいです。"],
    ["cumi-cumi", "いか", "squid", "Kami makan cumi-cumi goreng.", "私たちはいかの揚げ物を食べます。"],
    ["daging sapi", "牛肉", "beef", "Daging sapi ini mahal.", "この牛肉は高いです。"],
    ["daging ayam", "鶏肉", "chicken meat", "Ibu memasak daging ayam.", "母は鶏肉を料理します。"],
    ["es krim", "アイスクリーム", "ice cream", "Anak-anak suka es krim.", "子どもたちはアイスクリームが好きです。"],
    ["minuman", "飲み物", "drink", "Minuman ini dingin.", "この飲み物は冷たいです。"],
    ["makanan ringan", "軽食、スナック", "snack", "Saya membeli makanan ringan.", "私はスナックを買います。"],
    ["resep", "レシピ", "recipe", "Ibu punya resep baru.", "母は新しいレシピを持っています。"],
    ["rasa", "味", "taste", "Rasanya enak.", "味はおいしいです。"],
    ["bau", "におい", "smell", "Bau masakan ini enak.", "この料理のにおいは良いです。"],
    ["cuaca", "天気", "weather", "Cuaca hari ini bagus.", "今日の天気は良いです。"],
    ["udara", "空気", "air", "Udara di gunung sejuk.", "山の空気は涼しいです。"],
    ["awan", "雲", "cloud", "Awan hitam muncul di langit.", "黒い雲が空に現れます。"],
    ["hujan deras", "大雨", "heavy rain", "Hujan deras turun tadi malam.", "昨夜大雨が降りました。"],
    ["gerimis", "霧雨、小雨", "drizzle", "Gerimis turun sejak pagi.", "朝から小雨が降っています。"],
    ["banjir", "洪水", "flood", "Banjir terjadi di kota itu.", "その町で洪水が起きました。"],
    ["musim", "季節", "season", "Indonesia punya dua musim.", "インドネシアには2つの季節があります。"],
    ["musim hujan", "雨季", "rainy season", "Sekarang musim hujan.", "今は雨季です。"],
    ["musim kemarau", "乾季", "dry season", "Musim kemarau berlangsung lama.", "乾季は長く続きます。"],
    ["suhu", "温度", "temperature", "Suhu hari ini tinggi.", "今日の気温は高いです。"],
    ["derajat", "度", "degree", "Suhunya tiga puluh derajat.", "気温は30度です。"],
    ["panas matahari", "日差し", "sunlight", "Panas matahari sangat kuat hari ini.", "今日は日差しがとても強いです。"],
    ["kesehatan", "健康", "health", "Kesehatan sangat penting.", "健康はとても重要です。"],
    ["penyakit", "病気", "disease", "Penyakit itu berbahaya.", "その病気は危険です。"],
    ["demam", "熱", "fever", "Anak saya demam.", "私の子どもは熱があります。"],
    ["batuk", "咳", "cough", "Saya batuk sejak kemarin.", "私は昨日から咳が出ます。"],
    ["pilek", "風邪、鼻風邪", "cold", "Saya sedang pilek.", "私は風邪をひいています。"],
    ["pusing", "めまい、頭痛", "dizziness", "Kepala saya pusing.", "頭がくらくらします。"],
    ["mual", "吐き気", "nausea", "Saya merasa mual.", "吐き気がします。"],
    ["luka", "傷", "wound", "Luka itu belum sembuh.", "その傷はまだ治っていません。"],
    ["pasien", "患者", "patient", "Pasien itu menunggu dokter.", "その患者は医者を待っています。"],
    ["perawat", "看護師", "nurse", "Perawat itu ramah.", "その看護師は親切です。"],
    ["klinik", "クリニック", "clinic", "Saya pergi ke klinik.", "私はクリニックへ行きます。"],
    ["resep obat", "処方箋", "prescription", "Dokter memberi resep obat.", "医者は処方箋を出します。"],
    ["janji dokter", "診察予約", "doctor appointment", "Saya punya janji dokter besok.", "私は明日診察の予約があります。"],
    ["asuransi", "保険", "insurance", "Saya punya asuransi kesehatan.", "私は健康保険に入っています。"],
    ["bantuan", "助け", "help", "Saya perlu bantuan Anda.", "私はあなたの助けが必要です。"],
    ["masalah", "問題", "problem", "Masalah ini kecil.", "この問題は小さいです。"],
    ["kesalahan", "間違い", "mistake", "Ada kesalahan di formulir ini.", "この用紙に間違いがあります。"],
    ["alasan", "理由", "reason", "Apa alasan Anda datang terlambat?", "遅れて来た理由は何ですか。"],
    ["tujuan", "目的", "purpose", "Apa tujuan perjalanan Anda?", "あなたの旅行の目的は何ですか。"],
    ["rencana", "計画", "plan", "Kami punya rencana baru.", "私たちには新しい計画があります。"],
    ["pengalaman", "経験", "experience", "Saya punya pengalaman kerja.", "私は仕事の経験があります。"],
    ["kesempatan", "機会", "opportunity", "Ini kesempatan yang baik.", "これは良い機会です。"],
    ["kebiasaan", "習慣", "habit", "Bangun pagi adalah kebiasaan saya.", "早起きは私の習慣です。"],
    ["kebutuhan", "必要なもの", "need", "Air adalah kebutuhan semua orang.", "水はすべての人に必要なものです。"],
    ["keinginan", "願い、欲求", "desire", "Keinginan saya sederhana.", "私の願いはささやかです。"],
    ["keputusan", "決定", "decision", "Keputusan itu sudah dibuat.", "その決定はもう下されました。"],
    ["pilihan", "選択", "choice", "Ada dua pilihan.", "選択肢は2つあります。"],
    ["aturan", "規則", "rule", "Ikuti aturan di sini.", "ここの規則に従ってください。"],
    ["larangan", "禁止", "prohibition", "Ada larangan merokok di sini.", "ここでは喫煙が禁止されています。"],
    ["perintah", "命令", "command", "Dia mengikuti perintah atasan.", "彼は上司の命令に従います。"],
    ["permintaan", "依頼", "request", "Saya menerima permintaan itu.", "私はその依頼を受けます。"],
    ["ajakan", "誘い", "invitation", "Saya menolak ajakan itu.", "私はその誘いを断ります。"],
    ["saran", "提案、助言", "suggestion", "Terima kasih atas sarannya.", "助言をありがとうございます。"],
    ["pendapat", "意見", "opinion", "Apa pendapat Anda?", "あなたの意見は何ですか。"],
    ["cerita", "話、物語", "story", "Cerita itu menarik.", "その話は面白いです。"],
    ["kabar", "知らせ、様子", "news; condition", "Ada kabar baik hari ini.", "今日は良い知らせがあります。"],
    ["hubungan", "関係", "relationship", "Hubungan kami baik.", "私たちの関係は良好です。"],
    ["perbedaan", "違い", "difference", "Perbedaannya kecil.", "違いは小さいです。"],
    ["persamaan", "共通点", "similarity", "Ada persamaan antara keduanya.", "両者には共通点があります。"],
    ["bagian", "部分", "part", "Bagian ini penting.", "この部分は重要です。"],
    ["contoh", "例", "example", "Tolong beri contoh.", "例を挙げてください。"],
    ["cara", "方法", "way; method", "Saya belajar cara memasak.", "私は料理の仕方を学びます。"],
    ["langkah", "手順、歩み", "step", "Ikuti langkah berikut.", "次の手順に従ってください。"],
    ["hasil", "結果", "result", "Hasilnya bagus.", "結果は良いです。"],
    ["proses", "過程", "process", "Prosesnya cepat.", "手続きは速いです。"],
    ["waktu luang", "自由時間", "free time", "Saya membaca buku pada waktu luang.", "私は自由時間に本を読みます。"],
    ["liburan", "休暇", "holiday", "Saya perlu liburan.", "私は休暇が必要です。"],
    ["perjalanan", "旅行", "trip", "Perjalanan ke Bali lima jam.", "バリへの旅は5時間です。"],
    ["pemandangan", "景色", "scenery", "Pemandangan dari sini bagus.", "ここからの景色は良いです。"],
    ["oleh-oleh", "お土産", "souvenir", "Saya membeli oleh-oleh untuk keluarga.", "私は家族へのお土産を買います。"],
    ["tempat wisata", "観光地", "tourist spot", "Tempat wisata itu ramai.", "その観光地は混んでいます。"],
    ["pemandu wisata", "観光ガイド", "tour guide", "Pemandu wisata itu ramah.", "その観光ガイドは親切です。"],
    ["penumpang", "乗客", "passenger", "Penumpang bus itu banyak.", "そのバスの乗客は多いです。"],
    ["pengemudi", "運転者", "driver", "Pengemudi taksi itu sopan.", "そのタクシー運転手は礼儀正しいです。"],
    ["karcis", "切符", "ticket", "Saya membeli karcis kereta.", "私は電車の切符を買います。"],
    ["bagasi", "荷物、手荷物", "baggage", "Bagasi saya berat.", "私の荷物は重いです。"],
    ["jadwal penerbangan", "飛行機の時刻表", "flight schedule", "Saya melihat jadwal penerbangan.", "私は飛行機の時刻表を見ます。"],
    ["penerbangan", "フライト", "flight", "Penerbangan ke Bali dua jam.", "バリへのフライトは2時間です。"],
    ["keberangkatan", "出発", "departure", "Waktu keberangkatan jam delapan.", "出発時刻は8時です。"],
    ["kedatangan", "到着", "arrival", "Kedatangan bus terlambat.", "バスの到着は遅れました。"],
    ["kapal", "船", "ship", "Kami naik kapal ke pulau itu.", "私たちは船でその島へ行きます。"],
    ["perahu", "小舟", "boat", "Perahu itu kecil.", "その小舟は小さいです。"],
    ["sepeda", "自転車", "bicycle", "Saya naik sepeda ke sekolah.", "私は自転車で学校へ行きます。"],
    ["sepeda motor", "オートバイ", "motorcycle", "Dia naik sepeda motor.", "彼はオートバイに乗ります。"],
    ["angkot", "乗合ミニバス", "public minivan", "Saya naik angkot ke pasar.", "私は乗合ミニバスで市場へ行きます。"],
    ["ojek", "バイクタクシー", "motorcycle taxi", "Saya naik ojek ke stasiun.", "私はバイクタクシーで駅へ行きます。"],
    ["jalan tol", "高速道路", "toll road", "Kami lewat jalan tol.", "私たちは高速道路を通ります。"],
    ["pom bensin", "ガソリンスタンド", "gas station", "Kami berhenti di pom bensin.", "私たちはガソリンスタンドで止まります。"],
    ["bensin", "ガソリン", "gasoline", "Saya membeli bensin.", "私はガソリンを買います。"],
    ["bengkel", "修理工場", "repair shop", "Mobil saya ada di bengkel.", "私の車は修理工場にあります。"],
    ["ban", "タイヤ", "tire", "Ban sepeda saya rusak.", "私の自転車のタイヤは壊れています。"]
  ];

  const rows = []
    .concat(transitiveVerbs.map(([word, japanese, english, object, objectJapanese, example, exampleJapanese]) => ({
      word,
      japanese,
      english,
      partOfSpeech: "動詞",
      category: "動詞",
      example: example || `Saya ${word} ${object}.`,
      exampleJapanese: exampleJapanese || `私は${objectJapanese}を${jpMain(japanese)}。`,
      note: "D級で覚えたい他動詞。目的語と一緒に例文ごと覚える。"
    })))
    .concat(intransitiveVerbs.map(([word, japanese, english, place, placeJapanese, subject, subjectJapanese]) => ({
      word,
      japanese,
      english,
      partOfSpeech: "動詞",
      category: "動詞",
      example: `${subject || "Saya"} ${word} ${place}.`,
      exampleJapanese: `${subjectJapanese || "私は"}${placeJapanese}${jpMain(japanese)}。`,
      note: "D級で覚えたい動詞。場所や時間の語と一緒に使いやすい。"
    })))
    .concat(functionWords.map(([word, japanese, english, partOfSpeech, example, exampleJapanese]) => ({
      word,
      japanese,
      english,
      partOfSpeech,
      category: partOfSpeech,
      example,
      exampleJapanese,
      note: "D級で覚えたい機能語・表現。短い文の中で使い方を確認する。"
    })))
    .concat(adverbs.map(([word, japanese, english, example, exampleJapanese]) => ({
      word,
      japanese,
      english,
      partOfSpeech: "副詞",
      category: "副詞",
      example,
      exampleJapanese,
      note: "D級で覚えたい副詞。動詞の前に置く語と後ろに置く語を例文で確認する。"
    })))
    .concat(months.map(([word, japanese, english]) => ({
      word,
      japanese,
      english,
      partOfSpeech: "名詞",
      category: "名詞",
      example: `Saya pergi pada bulan ${word}.`,
      exampleJapanese: `私は${japanese}に行きます。`,
      note: "月の名前。日付や予定を言うときに使う。"
    })))
    .concat(numberWords.map(([word, japanese, english]) => ({
      word,
      japanese,
      english,
      partOfSpeech: "数詞",
      category: "数詞",
      example: `Saya menulis angka ${word}.`,
      exampleJapanese: `私は${japanese}という数字を書きます。`,
      note: "数を表す語。値段、時間、数量でよく使う。"
    })))
    .concat(adjectives.map(([word, japanese, english, example, exampleJapanese]) => ({
      word,
      japanese,
      english,
      partOfSpeech: "形容詞",
      category: "形容詞",
      example,
      exampleJapanese,
      note: "D級で覚えたい形容詞。名詞の後ろに置いて説明できる。"
    })))
    .concat(nouns.map(([word, japanese, english, example, exampleJapanese]) => ({
      word,
      japanese,
      english,
      partOfSpeech: word.includes(" ") ? "名詞句" : "名詞",
      category: word.includes(" ") ? "名詞句" : "名詞",
      example,
      exampleJapanese,
      note: "D級で覚えたい名詞。手続き、旅行、日常生活で使いやすい。"
    })));

  const selectedRows = [];
  rows.forEach((row) => {
    const key = row.word.toLowerCase();
    if (!usedWords.has(key) && !selectedRows.some((item) => item.word.toLowerCase() === key)) {
      selectedRows.push(row);
    }
  });

  selectedRows.slice(0, targetAdditional).forEach((row, index) => {
    appData.words.push({
      id: `d-${String(startNumber + index).padStart(3, "0")}`,
      level: "D",
      word: row.word,
      japanese: row.japanese,
      english: row.english,
      partOfSpeech: row.partOfSpeech,
      category: row.category,
      example: row.example,
      exampleJapanese: row.exampleJapanese,
      note: row.note
    });
  });
})();
