window.INDONESIAN_FLASHCARD_DATA = {
  words: [
    {
      id: "e-001",
      level: "E",
      word: "saya",
      japanese: "私",
      english: "I; me",
      partOfSpeech: "代名詞",
      category: "基本",
      example: "Saya tinggal di Tokyo.",
      exampleJapanese: "私は東京に住んでいます。",
      note: "丁寧で中立的な一人称。"
    },
    {
      id: "e-002",
      level: "E",
      word: "Anda",
      japanese: "あなた",
      english: "you",
      partOfSpeech: "代名詞",
      category: "基本",
      example: "Anda berasal dari mana?",
      exampleJapanese: "あなたはどこの出身ですか。",
      note: "初対面や文書で使いやすい二人称。"
    },
    {
      id: "e-003",
      level: "E",
      word: "makan",
      japanese: "食べる",
      english: "to eat",
      partOfSpeech: "動詞",
      category: "日常",
      example: "Saya makan nasi goreng.",
      exampleJapanese: "私はナシゴレンを食べます。",
      note: "目的語をそのまま後ろに置ける基本動詞。"
    },
    {
      id: "e-004",
      level: "E",
      word: "minum",
      japanese: "飲む",
      english: "to drink",
      partOfSpeech: "動詞",
      category: "日常",
      example: "Dia minum air putih.",
      exampleJapanese: "彼は水を飲みます。",
      note: "air putih は飲料水の意味。"
    },
    {
      id: "e-005",
      level: "E",
      word: "pisau",
      japanese: "ナイフ",
      english: "knife",
      partOfSpeech: "名詞",
      category: "家・道具",
      example: "Ibu memakai pisau kecil.",
      exampleJapanese: "母は小さいナイフを使います。",
      note: "つづりは pisau。母音の並びに注意。"
    },
    {
      id: "e-006",
      level: "E",
      word: "rumah",
      japanese: "家",
      english: "house; home",
      partOfSpeech: "名詞",
      category: "場所",
      example: "Rumah saya dekat stasiun.",
      exampleJapanese: "私の家は駅の近くです。",
      note: "rumah makan は食堂、レストラン。"
    },
    {
      id: "e-007",
      level: "E",
      word: "sekolah",
      japanese: "学校",
      english: "school",
      partOfSpeech: "名詞",
      category: "場所",
      example: "Adik saya pergi ke sekolah.",
      exampleJapanese: "私の弟は学校へ行きます。",
      note: "ke は方向を表す前置詞。"
    },
    {
      id: "e-008",
      level: "E",
      word: "di",
      japanese: "〜で、〜に",
      english: "at; in; on",
      partOfSpeech: "前置詞",
      category: "文法語",
      example: "Saya belajar di rumah.",
      exampleJapanese: "私は家で勉強します。",
      note: "場所を表す。受動態の接頭辞 di- とは別。"
    },
    {
      id: "e-009",
      level: "E",
      word: "dengan",
      japanese: "〜と、〜で",
      english: "with; by",
      partOfSpeech: "前置詞",
      category: "文法語",
      example: "Saya pergi dengan teman.",
      exampleJapanese: "私は友だちと行きます。",
      note: "相手や手段を表す。"
    },
    {
      id: "e-010",
      level: "E",
      word: "besar",
      japanese: "大きい",
      english: "big; large",
      partOfSpeech: "形容詞",
      category: "形容",
      example: "Kamar ini besar.",
      exampleJapanese: "この部屋は大きいです。",
      note: "名詞の後ろに置くことが多い。"
    },
    {
      id: "e-011",
      level: "E",
      word: "kecil",
      japanese: "小さい",
      english: "small",
      partOfSpeech: "形容詞",
      category: "形容",
      example: "Saya membeli tas kecil.",
      exampleJapanese: "私は小さいかばんを買います。",
      note: "tas kecil のように名詞の後ろ。"
    },
    {
      id: "e-012",
      level: "E",
      word: "paling",
      japanese: "最も、一番",
      english: "most",
      partOfSpeech: "副詞",
      category: "文法語",
      example: "Mangga paling enak.",
      exampleJapanese: "マンゴーが一番おいしいです。",
      note: "paling + 形容詞で最上級。"
    },
    {
      id: "d-001",
      level: "D",
      word: "upacara",
      japanese: "儀式、式典",
      english: "ceremony",
      partOfSpeech: "名詞",
      category: "社会",
      example: "Upacara dimulai pukul sembilan.",
      exampleJapanese: "式典は9時に始まります。",
      note: "つづりは upacara。"
    },
    {
      id: "d-002",
      level: "D",
      word: "formulir",
      japanese: "用紙、フォーム",
      english: "form",
      partOfSpeech: "名詞",
      category: "手続き",
      example: "Saya mengisi formulir ini.",
      exampleJapanese: "私はこの用紙に記入します。",
      note: "mengisi は isi に meN- が付いた形。"
    },
    {
      id: "d-003",
      level: "D",
      word: "tanggal lahir",
      japanese: "生年月日",
      english: "date of birth",
      partOfSpeech: "名詞句",
      category: "手続き",
      example: "Tulis tanggal lahir Anda di sini.",
      exampleJapanese: "ここにあなたの生年月日を書いてください。",
      note: "tanggal は日付、lahir は生まれる。"
    },
    {
      id: "d-004",
      level: "D",
      word: "berasal",
      japanese: "出身である、由来する",
      english: "to come from; to originate",
      partOfSpeech: "動詞",
      category: "自己紹介",
      example: "Bapak Didi berasal dari Surabaya.",
      exampleJapanese: "ディディさんはスラバヤ出身です。",
      note: "ber- + asal。dari とよく使う。"
    },
    {
      id: "d-005",
      level: "D",
      word: "membeli",
      japanese: "買う",
      english: "to buy",
      partOfSpeech: "動詞",
      category: "買い物",
      example: "Saya membeli baju renang.",
      exampleJapanese: "私は水着を買います。",
      note: "語幹 beli。meN- が付いた形。"
    },
    {
      id: "d-006",
      level: "D",
      word: "harga",
      japanese: "値段、価格",
      english: "price",
      partOfSpeech: "名詞",
      category: "買い物",
      example: "Berapa harga tiket ini?",
      exampleJapanese: "このチケットはいくらですか。",
      note: "berapa は数量や値段を聞く疑問詞。"
    },
    {
      id: "d-007",
      level: "D",
      word: "lebih",
      japanese: "より、もっと",
      english: "more",
      partOfSpeech: "副詞",
      category: "比較",
      example: "Mana yang lebih sedap?",
      exampleJapanese: "どちらがよりおいしいですか。",
      note: "lebih + 形容詞で比較。"
    },
    {
      id: "d-008",
      level: "D",
      word: "sedap",
      japanese: "おいしい、風味がよい",
      english: "delicious; tasty",
      partOfSpeech: "形容詞",
      category: "食べ物",
      example: "Mie goreng ini sedap.",
      exampleJapanese: "このミーゴレンはおいしいです。",
      note: "enak より少し書きことば寄りでも使える。"
    },
    {
      id: "d-009",
      level: "D",
      word: "hapus",
      japanese: "消す、拭く",
      english: "to erase; to wipe",
      partOfSpeech: "動詞",
      category: "日常",
      example: "Hapuslah air matamu.",
      exampleJapanese: "涙を拭きなさい。",
      note: "-lah は命令をやわらげたり強調したりする。"
    },
    {
      id: "d-010",
      level: "D",
      word: "mengisi",
      japanese: "記入する、満たす",
      english: "to fill in; to fill",
      partOfSpeech: "動詞",
      category: "手続き",
      example: "Untuk mengisi formulir, saya perlu pena.",
      exampleJapanese: "用紙に記入するために、私はペンが必要です。",
      note: "語幹 isi。母音始まりなので meng- になる。"
    },
    {
      id: "d-011",
      level: "D",
      word: "perlu",
      japanese: "必要である",
      english: "to need; necessary",
      partOfSpeech: "形容詞",
      category: "日常",
      example: "Saya perlu berbicara dengan guru.",
      exampleJapanese: "私は先生と話す必要があります。",
      note: "perlu + 動詞で「〜する必要がある」。"
    },
    {
      id: "d-012",
      level: "D",
      word: "berbicara",
      japanese: "話す",
      english: "to speak; to talk",
      partOfSpeech: "動詞",
      category: "会話",
      example: "Kami berbicara dengan pelan.",
      exampleJapanese: "私たちはゆっくり話します。",
      note: "ber- 動詞。dengan と相性がよい。"
    },
    {
      id: "c-001",
      level: "C",
      word: "berkenan",
      japanese: "気に入る、差し支えない",
      english: "to be pleased; to be willing",
      partOfSpeech: "動詞",
      category: "表現",
      example: "Apakah Bapak berkenan hadir besok?",
      exampleJapanese: "明日ご出席いただけますでしょうか。",
      note: "丁寧な依頼や確認で使われる。"
    },
    {
      id: "c-002",
      level: "C",
      word: "bebas",
      japanese: "自由な、免れている",
      english: "free; free from",
      partOfSpeech: "形容詞",
      category: "状態",
      example: "Daerah itu bebas dari malaria.",
      exampleJapanese: "その地域はマラリアの被害がありません。",
      note: "bebas dari ... で「〜がない、〜から自由」。"
    },
    {
      id: "c-003",
      level: "C",
      word: "menghiraukan",
      japanese: "気にかける、顧みる",
      english: "to care about; to heed",
      partOfSpeech: "動詞",
      category: "態度",
      example: "Dia menyeberang tanpa menghiraukan keselamatan.",
      exampleJapanese: "彼は安全を顧みずに横断しました。",
      note: "tanpa + 動詞で「〜せずに」。"
    },
    {
      id: "c-004",
      level: "C",
      word: "keselamatan",
      japanese: "安全",
      english: "safety",
      partOfSpeech: "名詞",
      category: "社会",
      example: "Keselamatan penumpang sangat penting.",
      exampleJapanese: "乗客の安全はとても重要です。",
      note: "selamat から派生した ke-an 名詞。"
    },
    {
      id: "c-005",
      level: "C",
      word: "dihargai",
      japanese: "評価される、尊重される",
      english: "to be appreciated; valued",
      partOfSpeech: "動詞",
      category: "仕事",
      example: "Karyawan merasa dihargai oleh pemimpinnya.",
      exampleJapanese: "社員たちはリーダーに評価されていると感じました。",
      note: "di- 受動態。語幹は harga。"
    },
    {
      id: "c-006",
      level: "C",
      word: "karyawan",
      japanese: "社員、従業員",
      english: "employee",
      partOfSpeech: "名詞",
      category: "仕事",
      example: "Karyawan itu bekerja keras.",
      exampleJapanese: "その社員は一生懸命働きます。",
      note: "pegawai も従業員を表す。"
    },
    {
      id: "c-007",
      level: "C",
      word: "pemimpin",
      japanese: "リーダー、指導者",
      english: "leader",
      partOfSpeech: "名詞",
      category: "仕事",
      example: "Pemimpin harus memberi contoh.",
      exampleJapanese: "リーダーは手本を示すべきです。",
      note: "pimpin に peN- が付いた名詞。"
    },
    {
      id: "c-008",
      level: "C",
      word: "melanda",
      japanese: "襲う、見舞う",
      english: "to hit; to strike",
      partOfSpeech: "動詞",
      category: "ニュース",
      example: "Badai melanda wilayah ini.",
      exampleJapanese: "嵐がこの地域を襲いました。",
      note: "災害や問題が地域を襲う表現で使う。"
    },
    {
      id: "c-009",
      level: "C",
      word: "wilayah",
      japanese: "地域、区域",
      english: "area; region",
      partOfSpeech: "名詞",
      category: "場所",
      example: "Wilayah ini sering hujan.",
      exampleJapanese: "この地域はよく雨が降ります。",
      note: "daerah と近いが、行政・範囲の響きがある。"
    },
    {
      id: "c-010",
      level: "C",
      word: "asal",
      japanese: "〜でさえあれば、由来",
      english: "as long as; origin",
      partOfSpeech: "接続詞",
      category: "文法語",
      example: "Silakan ambil foto, asal jangan pakai blitz.",
      exampleJapanese: "フラッシュを使わなければ、写真を撮ってもいいです。",
      note: "条件を表す asal は「〜である限り」。"
    },
    {
      id: "c-011",
      level: "C",
      word: "padahal",
      japanese: "〜なのに、実は",
      english: "even though; whereas",
      partOfSpeech: "接続詞",
      category: "文法語",
      example: "Dia datang, padahal baru sembuh.",
      exampleJapanese: "彼は治ったばかりなのに来ました。",
      note: "意外性や対比を表す接続詞。"
    },
    {
      id: "c-012",
      level: "C",
      word: "laporan",
      japanese: "報告書、報告",
      english: "report",
      partOfSpeech: "名詞",
      category: "仕事",
      example: "Buatkan laporan singkat hari ini.",
      exampleJapanese: "今日、短い報告書を作ってください。",
      note: "lapor から派生した -an 名詞。"
    },
    {
      id: "b-001",
      level: "B",
      word: "maya",
      japanese: "仮想の、幻想の",
      english: "virtual; imaginary",
      partOfSpeech: "形容詞",
      category: "社会",
      example: "Mereka membangun dunia maya sendiri.",
      exampleJapanese: "彼らは自分たちの仮想世界を作りました。",
      note: "dunia maya はインターネット空間の意味でも使う。"
    },
    {
      id: "b-002",
      level: "B",
      word: "nyata",
      japanese: "現実の、明らかな",
      english: "real; evident",
      partOfSpeech: "形容詞",
      category: "社会",
      example: "Dampaknya sudah nyata.",
      exampleJapanese: "その影響はすでに明らかです。",
      note: "maya の反対語として出やすい。"
    },
    {
      id: "b-003",
      level: "B",
      word: "menghanguskan",
      japanese: "焼き尽くす",
      english: "to burn down",
      partOfSpeech: "動詞",
      category: "ニュース",
      example: "Kebakaran itu menghanguskan tiga rumah.",
      exampleJapanese: "その火事は3軒の家を焼き尽くしました。",
      note: "hangus は黒焦げになる。"
    },
    {
      id: "b-004",
      level: "B",
      word: "bertujuan",
      japanese: "目的としている",
      english: "to aim; to be intended",
      partOfSpeech: "動詞",
      category: "論理",
      example: "Program ini bertujuan membantu masyarakat.",
      exampleJapanese: "このプログラムは住民を支援することを目的としています。",
      note: "tujuan は目的。bertujuan untuk ... と使う。"
    },
    {
      id: "b-005",
      level: "B",
      word: "pemulihan",
      japanese: "復旧、回復",
      english: "recovery; restoration",
      partOfSpeech: "名詞",
      category: "ニュース",
      example: "Pemerintah mendukung pemulihan ekonomi.",
      exampleJapanese: "政府は経済回復を支援しています。",
      note: "pulih から派生した peN-an 名詞。"
    },
    {
      id: "b-006",
      level: "B",
      word: "pascatsunami",
      japanese: "津波後の",
      english: "post-tsunami",
      partOfSpeech: "形容詞",
      category: "ニュース",
      example: "Bantuan diberikan kepada warga pascatsunami.",
      exampleJapanese: "津波後の住民に支援が与えられました。",
      note: "pasca- は「〜後」を表す接頭辞。"
    },
    {
      id: "b-007",
      level: "B",
      word: "bahkan",
      japanese: "それどころか、さらに",
      english: "even; moreover",
      partOfSpeech: "副詞",
      category: "論理",
      example: "Dia tidak takut, bahkan melawan polisi.",
      exampleJapanese: "彼は恐れず、それどころか警察に抵抗しました。",
      note: "前の内容を強める接続表現。"
    },
    {
      id: "b-008",
      level: "B",
      word: "pakar",
      japanese: "専門家",
      english: "expert",
      partOfSpeech: "名詞",
      category: "社会",
      example: "Para pakar membahas masalah kota.",
      exampleJapanese: "専門家たちは都市問題を議論しました。",
      note: "ahli と近い。para は複数を表す。"
    },
    {
      id: "b-009",
      level: "B",
      word: "kemacetan",
      japanese: "渋滞、停滞",
      english: "traffic jam; congestion",
      partOfSpeech: "名詞",
      category: "都市",
      example: "Kemacetan lalu lintas semakin parah.",
      exampleJapanese: "交通渋滞はますます深刻になっています。",
      note: "macet から派生した ke-an 名詞。"
    },
    {
      id: "b-010",
      level: "B",
      word: "pencemaran",
      japanese: "汚染",
      english: "pollution; contamination",
      partOfSpeech: "名詞",
      category: "環境",
      example: "Pencemaran udara menjadi masalah serius.",
      exampleJapanese: "大気汚染は深刻な問題になっています。",
      note: "cemar から派生した peN-an 名詞。"
    },
    {
      id: "b-011",
      level: "B",
      word: "kawasan",
      japanese: "地域、区域",
      english: "area; zone",
      partOfSpeech: "名詞",
      category: "都市",
      example: "Kawasan hijau di kota itu berkurang.",
      exampleJapanese: "その都市の緑地は減っています。",
      note: "kawasan hijau は緑地。"
    },
    {
      id: "b-012",
      level: "B",
      word: "mengkhawatirkan",
      japanese: "心配させる、懸念する",
      english: "to worry; to concern",
      partOfSpeech: "動詞",
      category: "ニュース",
      example: "Pedagang mengkhawatirkan penggusuran.",
      exampleJapanese: "商人たちは立ち退きを心配しています。",
      note: "khawatir に meN-kan が付いた形。"
    },
    {
      id: "a-001",
      level: "A",
      word: "keberadaan",
      japanese: "存在",
      english: "existence",
      partOfSpeech: "名詞",
      category: "抽象",
      example: "Keberadaan sekolah itu penting bagi warga.",
      exampleJapanese: "その学校の存在は住民にとって重要です。",
      note: "berada から派生した ke-an 名詞。"
    },
    {
      id: "a-002",
      level: "A",
      word: "melingkupi",
      japanese: "取り巻く、包み込む",
      english: "to surround; to encompass",
      partOfSpeech: "動詞",
      category: "抽象",
      example: "Budaya melingkupi proses pendidikan.",
      exampleJapanese: "文化は教育過程を取り巻いています。",
      note: "文献調の抽象表現で使われやすい。"
    },
    {
      id: "a-003",
      level: "A",
      word: "antusias",
      japanese: "熱心な、熱狂的な",
      english: "enthusiastic",
      partOfSpeech: "形容詞",
      category: "態度",
      example: "Para orang tua menyambut program itu dengan antusias.",
      exampleJapanese: "保護者たちはそのプログラムを熱心に歓迎しました。",
      note: "dengan antusias で副詞的に使える。"
    },
    {
      id: "a-004",
      level: "A",
      word: "peluncuran",
      japanese: "打ち上げ、開始",
      english: "launch",
      partOfSpeech: "名詞",
      category: "ニュース",
      example: "Peluncuran satelit disiarkan langsung.",
      exampleJapanese: "衛星の打ち上げは生中継されました。",
      note: "luncur から派生した peN-an 名詞。"
    },
    {
      id: "a-005",
      level: "A",
      word: "ketulian",
      japanese: "難聴、聴覚障害",
      english: "deafness",
      partOfSpeech: "名詞",
      category: "医療",
      example: "Paparan suara keras dapat menyebabkan ketulian.",
      exampleJapanese: "大きな音への暴露は難聴を引き起こすことがあります。",
      note: "tuli から派生した ke-an 名詞。"
    },
    {
      id: "a-006",
      level: "A",
      word: "pelaksanaan",
      japanese: "実施、遂行",
      english: "implementation",
      partOfSpeech: "名詞",
      category: "行政",
      example: "Pelaksanaan ujian berjalan tertib.",
      exampleJapanese: "試験の実施は整然と進みました。",
      note: "laksana から派生した peN-an 名詞。"
    },
    {
      id: "a-007",
      level: "A",
      word: "meskipun",
      japanese: "〜にもかかわらず",
      english: "although; even though",
      partOfSpeech: "接続詞",
      category: "論理",
      example: "Meskipun hujan, rapat tetap dimulai.",
      exampleJapanese: "雨にもかかわらず、会議は予定どおり始まりました。",
      note: "譲歩を表す接続詞。"
    },
    {
      id: "a-008",
      level: "A",
      word: "produsen",
      japanese: "生産者、生産国",
      english: "producer",
      partOfSpeech: "名詞",
      category: "経済",
      example: "Indonesia merupakan produsen kopi besar.",
      exampleJapanese: "インドネシアは大きなコーヒー生産国です。",
      note: "merupakan は「〜である」を表す書きことば。"
    },
    {
      id: "a-009",
      level: "A",
      word: "lesu",
      japanese: "停滞した、元気がない",
      english: "sluggish; weak",
      partOfSpeech: "形容詞",
      category: "経済",
      example: "Produksi minyak mentah masih lesu.",
      exampleJapanese: "原油生産はまだ停滞しています。",
      note: "経済や生産活動の低迷に使える。"
    },
    {
      id: "a-010",
      level: "A",
      word: "kelangkaan",
      japanese: "不足、希少性",
      english: "scarcity; shortage",
      partOfSpeech: "名詞",
      category: "経済",
      example: "Kelangkaan bahan bakar memicu antrean panjang.",
      exampleJapanese: "燃料不足が長い行列を引き起こしました。",
      note: "langka から派生した ke-an 名詞。"
    },
    {
      id: "a-011",
      level: "A",
      word: "mewakili",
      japanese: "代表する、代弁する",
      english: "to represent",
      partOfSpeech: "動詞",
      category: "政治",
      example: "Lembaga itu harus mewakili kepentingan rakyat.",
      exampleJapanese: "その機関は国民の利益を代表しなければなりません。",
      note: "wakil は代表者。meN-i で他動詞化。"
    },
    {
      id: "a-012",
      level: "A",
      word: "kepentingan",
      japanese: "利益、関心事",
      english: "interest; importance",
      partOfSpeech: "名詞",
      category: "政治",
      example: "Keputusan itu menyangkut kepentingan semua pihak.",
      exampleJapanese: "その決定はすべての関係者の利益に関わります。",
      note: "penting から派生した ke-an 名詞。"
    }
  ],
  grammarNotes: [
    {
      level: "E",
      title: "基本語順",
      pattern: "Saya makan nasi.",
      points: ["主語 + 動詞 + 目的語が基本。", "形容詞は名詞の後ろに置くことが多い。"]
    },
    {
      level: "D",
      title: "疑問詞と比較",
      pattern: "Berapa harga ini? / Mana yang lebih sedap?",
      points: ["berapa は数や値段を聞く。", "lebih + 形容詞で比較を作る。"]
    },
    {
      level: "C",
      title: "受動態と接続詞",
      pattern: "dihargai / padahal / asal",
      points: ["di- は受動態を作る。", "padahal は逆接、asal は条件を表す。"]
    },
    {
      level: "B",
      title: "派生語",
      pattern: "pemulihan / pencemaran / kemacetan",
      points: ["peN-an、ke-an で抽象名詞を作る。", "ニュースや業務文で頻出。"]
    },
    {
      level: "A",
      title: "論説・翻訳語彙",
      pattern: "meskipun / merupakan / kepentingan",
      points: ["社会問題や時事を説明する語彙が中心。", "抽象名詞と論理表現をまとめて覚える。"]
    }
  ]
};

window.INDONESIAN_FLASHCARD_DATA.words.push(
  ...[
    {
      id: "e-013",
      level: "E",
      word: "aku",
      japanese: "私、僕",
      english: "I; me",
      partOfSpeech: "代名詞",
      category: "基本",
      example: "Aku suka kopi.",
      exampleJapanese: "私はコーヒーが好きです。",
      note: "親しい相手とのくだけた一人称。"
    },
    {
      id: "e-014",
      level: "E",
      word: "dia",
      japanese: "彼、彼女、その人",
      english: "he; she",
      partOfSpeech: "代名詞",
      category: "基本",
      example: "Dia guru bahasa Indonesia.",
      exampleJapanese: "彼女はインドネシア語の先生です。",
      note: "性別を区別せずに使える三人称。"
    },
    {
      id: "e-015",
      level: "E",
      word: "kami",
      japanese: "私たち",
      english: "we; us",
      partOfSpeech: "代名詞",
      category: "基本",
      example: "Kami belajar setiap hari.",
      exampleJapanese: "私たちは毎日勉強します。",
      note: "聞き手を含まない「私たち」。聞き手を含む場合は kita。"
    },
    {
      id: "e-016",
      level: "E",
      word: "ini",
      japanese: "これ、この",
      english: "this",
      partOfSpeech: "指示詞",
      category: "基本",
      example: "Ini buku saya.",
      exampleJapanese: "これは私の本です。",
      note: "名詞の後ろにも置く。buku ini は「この本」。"
    },
    {
      id: "e-017",
      level: "E",
      word: "itu",
      japanese: "それ、あれ、その",
      english: "that",
      partOfSpeech: "指示詞",
      category: "基本",
      example: "Tas itu mahal.",
      exampleJapanese: "そのかばんは高いです。",
      note: "名詞の後ろに置いて「その〜」を表す。"
    },
    {
      id: "e-018",
      level: "E",
      word: "apa",
      japanese: "何",
      english: "what",
      partOfSpeech: "疑問詞",
      category: "文法語",
      example: "Apa nama makanan ini?",
      exampleJapanese: "この料理の名前は何ですか。",
      note: "疑問文の基本語。"
    },
    {
      id: "e-019",
      level: "E",
      word: "siapa",
      japanese: "誰",
      english: "who",
      partOfSpeech: "疑問詞",
      category: "文法語",
      example: "Siapa nama Anda?",
      exampleJapanese: "あなたのお名前は何ですか。",
      note: "人を聞く疑問詞。"
    },
    {
      id: "e-020",
      level: "E",
      word: "kapan",
      japanese: "いつ",
      english: "when",
      partOfSpeech: "疑問詞",
      category: "文法語",
      example: "Kapan Anda pergi ke Bali?",
      exampleJapanese: "あなたはいつバリへ行きますか。",
      note: "時を聞く疑問詞。"
    },
    {
      id: "e-021",
      level: "E",
      word: "ke",
      japanese: "〜へ",
      english: "to",
      partOfSpeech: "前置詞",
      category: "文法語",
      example: "Saya pergi ke kantor.",
      exampleJapanese: "私は会社へ行きます。",
      note: "方向や目的地を表す。"
    },
    {
      id: "e-022",
      level: "E",
      word: "dari",
      japanese: "〜から",
      english: "from",
      partOfSpeech: "前置詞",
      category: "文法語",
      example: "Saya dari Jepang.",
      exampleJapanese: "私は日本から来ました。",
      note: "出身、起点、材料などを表す。"
    },
    {
      id: "e-023",
      level: "E",
      word: "baik",
      japanese: "良い、元気な",
      english: "good; well",
      partOfSpeech: "形容詞",
      category: "形容",
      example: "Kabar saya baik.",
      exampleJapanese: "私は元気です。",
      note: "Apa kabar? への返事で baik を使える。"
    },
    {
      id: "e-024",
      level: "E",
      word: "baru",
      japanese: "新しい、〜したばかり",
      english: "new; just",
      partOfSpeech: "形容詞",
      category: "形容",
      example: "Saya membeli sepatu baru.",
      exampleJapanese: "私は新しい靴を買いました。",
      note: "baru + 動詞で「〜したばかり」も表す。"
    },
    {
      id: "d-013",
      level: "D",
      word: "meminta",
      japanese: "頼む、求める",
      english: "to ask for; to request",
      partOfSpeech: "動詞",
      category: "会話",
      example: "Saya meminta bantuan teman.",
      exampleJapanese: "私は友だちに助けを頼みます。",
      note: "語幹 minta。meN- が付いた形。"
    },
    {
      id: "d-014",
      level: "D",
      word: "menjawab",
      japanese: "答える",
      english: "to answer",
      partOfSpeech: "動詞",
      category: "会話",
      example: "Dia menjawab pertanyaan guru.",
      exampleJapanese: "彼は先生の質問に答えます。",
      note: "jawab に meN- が付いた形。"
    },
    {
      id: "d-015",
      level: "D",
      word: "mencari",
      japanese: "探す",
      english: "to look for",
      partOfSpeech: "動詞",
      category: "日常",
      example: "Saya mencari alamat hotel.",
      exampleJapanese: "私はホテルの住所を探しています。",
      note: "cari に meN- が付いた形。"
    },
    {
      id: "d-016",
      level: "D",
      word: "membawa",
      japanese: "持って行く、持って来る",
      english: "to bring; to carry",
      partOfSpeech: "動詞",
      category: "日常",
      example: "Jangan lupa membawa paspor.",
      exampleJapanese: "パスポートを持って行くのを忘れないでください。",
      note: "bawa に meN- が付いた形。"
    },
    {
      id: "d-017",
      level: "D",
      word: "memilih",
      japanese: "選ぶ",
      english: "to choose",
      partOfSpeech: "動詞",
      category: "買い物",
      example: "Saya memilih warna biru.",
      exampleJapanese: "私は青色を選びます。",
      note: "pilih に meN- が付いた形。"
    },
    {
      id: "d-018",
      level: "D",
      word: "membuka",
      japanese: "開ける、開く",
      english: "to open",
      partOfSpeech: "動詞",
      category: "日常",
      example: "Tolong membuka jendela.",
      exampleJapanese: "窓を開けてください。",
      note: "buka に meN- が付いた形。"
    },
    {
      id: "d-019",
      level: "D",
      word: "menutup",
      japanese: "閉める、閉じる",
      english: "to close",
      partOfSpeech: "動詞",
      category: "日常",
      example: "Dia menutup pintu pelan-pelan.",
      exampleJapanese: "彼はドアをゆっくり閉めます。",
      note: "tutup に meN- が付いた形。"
    },
    {
      id: "d-020",
      level: "D",
      word: "dekat",
      japanese: "近い",
      english: "near; close",
      partOfSpeech: "形容詞",
      category: "場所",
      example: "Apotek dekat rumah saya.",
      exampleJapanese: "薬局は私の家の近くです。",
      note: "dekat dengan ... で「〜に近い」。"
    },
    {
      id: "d-021",
      level: "D",
      word: "jauh",
      japanese: "遠い",
      english: "far",
      partOfSpeech: "形容詞",
      category: "場所",
      example: "Bandara jauh dari pusat kota.",
      exampleJapanese: "空港は市中心部から遠いです。",
      note: "jauh dari ... で「〜から遠い」。"
    },
    {
      id: "d-022",
      level: "D",
      word: "cepat",
      japanese: "速い、早い",
      english: "fast; quick",
      partOfSpeech: "形容詞",
      category: "形容",
      example: "Kereta ini cepat sekali.",
      exampleJapanese: "この電車はとても速いです。",
      note: "cepat-cepat で「急いで」。"
    },
    {
      id: "d-023",
      level: "D",
      word: "lambat",
      japanese: "遅い",
      english: "slow; late",
      partOfSpeech: "形容詞",
      category: "形容",
      example: "Bus datang lambat hari ini.",
      exampleJapanese: "今日はバスが遅れて来ました。",
      note: "動きの遅さにも到着の遅れにも使える。"
    },
    {
      id: "d-024",
      level: "D",
      word: "berenang",
      japanese: "泳ぐ",
      english: "to swim",
      partOfSpeech: "動詞",
      category: "日常",
      example: "Saya mau berenang di pantai.",
      exampleJapanese: "私は海で泳ぎたいです。",
      note: "renang に ber- が付いた形。"
    },
    {
      id: "c-013",
      level: "C",
      word: "terpencil",
      japanese: "辺ぴな、遠く離れた",
      english: "remote; isolated",
      partOfSpeech: "形容詞",
      category: "場所",
      example: "Desa itu terletak di daerah terpencil.",
      exampleJapanese: "その村は辺ぴな地域にあります。",
      note: "地域や村の説明でよく使う。"
    },
    {
      id: "c-014",
      level: "C",
      word: "dinyatakan",
      japanese: "宣言される、表明される",
      english: "to be declared; stated",
      partOfSpeech: "動詞",
      category: "ニュース",
      example: "Wilayah itu dinyatakan aman.",
      exampleJapanese: "その地域は安全だと宣言されました。",
      note: "nyata ではなく nyata の派生ではなく、nyatakan の受動形。"
    },
    {
      id: "c-015",
      level: "C",
      word: "gangguan",
      japanese: "妨害、障害、支障",
      english: "disturbance; disruption",
      partOfSpeech: "名詞",
      category: "状態",
      example: "Tidak ada gangguan listrik hari ini.",
      exampleJapanese: "今日は停電の支障はありません。",
      note: "ganggu から派生した -an 名詞。"
    },
    {
      id: "c-016",
      level: "C",
      word: "melaporkan",
      japanese: "報告する、届け出る",
      english: "to report",
      partOfSpeech: "動詞",
      category: "仕事",
      example: "Petugas melaporkan kejadian itu.",
      exampleJapanese: "係員はその出来事を報告しました。",
      note: "lapor に meN-kan が付いた形。"
    },
    {
      id: "c-017",
      level: "C",
      word: "menyeberang",
      japanese: "横断する、渡る",
      english: "to cross",
      partOfSpeech: "動詞",
      category: "交通",
      example: "Jangan menyeberang jalan di sini.",
      exampleJapanese: "ここで道を横断しないでください。",
      note: "seberang は向こう側。"
    },
    {
      id: "c-018",
      level: "C",
      word: "seenaknya",
      japanese: "勝手に、好きなように",
      english: "as one pleases",
      partOfSpeech: "副詞",
      category: "態度",
      example: "Dia masuk ruangan seenaknya.",
      exampleJapanese: "彼は勝手に部屋に入りました。",
      note: "非難するニュアンスで使われやすい。"
    },
    {
      id: "c-019",
      level: "C",
      word: "badai",
      japanese: "嵐、暴風雨",
      english: "storm",
      partOfSpeech: "名詞",
      category: "天気",
      example: "Badai akan datang malam ini.",
      exampleJapanese: "今夜、嵐が来るでしょう。",
      note: "melanda と組み合わせてニュース表現にしやすい。"
    },
    {
      id: "c-020",
      level: "C",
      word: "ombak",
      japanese: "波",
      english: "wave",
      partOfSpeech: "名詞",
      category: "天気",
      example: "Ombak di pantai itu besar.",
      exampleJapanese: "その浜辺の波は大きいです。",
      note: "海の波。gelombang は波動や波全般にも使う。"
    },
    {
      id: "c-021",
      level: "C",
      word: "museum",
      japanese: "博物館、美術館",
      english: "museum",
      partOfSpeech: "名詞",
      category: "場所",
      example: "Boleh saya ambil foto di museum ini?",
      exampleJapanese: "この博物館で写真を撮ってもいいですか。",
      note: "外来語だが実用場面で頻出。"
    },
    {
      id: "c-022",
      level: "C",
      word: "cahaya",
      japanese: "光",
      english: "light",
      partOfSpeech: "名詞",
      category: "日常",
      example: "Jangan pakai cahaya blitz.",
      exampleJapanese: "フラッシュの光を使わないでください。",
      note: "cahaya matahari は太陽光。"
    },
    {
      id: "c-023",
      level: "C",
      word: "blitz",
      japanese: "フラッシュ",
      english: "flash",
      partOfSpeech: "名詞",
      category: "日常",
      example: "Foto boleh, asal tanpa blitz.",
      exampleJapanese: "フラッシュなしなら写真は可能です。",
      note: "カメラのフラッシュを表す外来語。"
    },
    {
      id: "c-024",
      level: "C",
      word: "apabila",
      japanese: "もし〜なら、〜の場合",
      english: "if; when",
      partOfSpeech: "接続詞",
      category: "文法語",
      example: "Hubungi saya apabila ada masalah.",
      exampleJapanese: "問題があれば私に連絡してください。",
      note: "jika より少し書きことば寄り。"
    },
    {
      id: "b-013",
      level: "B",
      word: "penggusuran",
      japanese: "立ち退き、撤去",
      english: "eviction; clearance",
      partOfSpeech: "名詞",
      category: "社会",
      example: "Warga menolak rencana penggusuran.",
      exampleJapanese: "住民は立ち退き計画に反対しました。",
      note: "gusur から派生した peN-an 名詞。"
    },
    {
      id: "b-014",
      level: "B",
      word: "pedagang",
      japanese: "商人、販売者",
      english: "trader; vendor",
      partOfSpeech: "名詞",
      category: "仕事",
      example: "Pedagang pasar mulai berjualan pagi-pagi.",
      exampleJapanese: "市場の商人たちは朝早くから販売を始めます。",
      note: "dagang から派生した peN- 名詞。"
    },
    {
      id: "b-015",
      level: "B",
      word: "mendukung",
      japanese: "支援する、支持する",
      english: "to support",
      partOfSpeech: "動詞",
      category: "社会",
      example: "Kami mendukung program pendidikan itu.",
      exampleJapanese: "私たちはその教育プログラムを支持しています。",
      note: "dukung に meN- が付いた形。"
    },
    {
      id: "b-016",
      level: "B",
      word: "masyarakat",
      japanese: "社会、住民、人々",
      english: "society; community",
      partOfSpeech: "名詞",
      category: "社会",
      example: "Program ini bermanfaat bagi masyarakat.",
      exampleJapanese: "このプログラムは住民に役立ちます。",
      note: "ニュースや論説で非常に頻出。"
    },
    {
      id: "b-017",
      level: "B",
      word: "jangka pendek",
      japanese: "短期の",
      english: "short-term",
      partOfSpeech: "名詞句",
      category: "論理",
      example: "Bantuan jangka pendek segera diberikan.",
      exampleJapanese: "短期支援がすぐに提供されました。",
      note: "対義表現は jangka panjang。"
    },
    {
      id: "b-018",
      level: "B",
      word: "menyempurnakan",
      japanese: "完成させる、より完全にする",
      english: "to perfect; to improve",
      partOfSpeech: "動詞",
      category: "抽象",
      example: "Tim itu menyempurnakan rencana kerja.",
      exampleJapanese: "そのチームは作業計画を改善しました。",
      note: "sempurna に meN-kan が付いた形。"
    },
    {
      id: "b-019",
      level: "B",
      word: "mengindahkan",
      japanese: "注意を払う、尊重する",
      english: "to heed; to pay attention to",
      partOfSpeech: "動詞",
      category: "態度",
      example: "Pengemudi harus mengindahkan rambu lalu lintas.",
      exampleJapanese: "運転者は交通標識に注意を払わなければなりません。",
      note: "否定形 tidak mengindahkan がよく出る。"
    },
    {
      id: "b-020",
      level: "B",
      word: "peringatan",
      japanese: "警告、記念",
      english: "warning; commemoration",
      partOfSpeech: "名詞",
      category: "社会",
      example: "Polisi memberi tembakan peringatan.",
      exampleJapanese: "警察は威嚇射撃を行いました。",
      note: "peringatan は文脈で警告にも記念にもなる。"
    },
    {
      id: "b-021",
      level: "B",
      word: "pemusatan",
      japanese: "集中",
      english: "concentration; centralization",
      partOfSpeech: "名詞",
      category: "都市",
      example: "Pemusatan penduduk terjadi di kota besar.",
      exampleJapanese: "人口集中は大都市で起きています。",
      note: "pusat から派生した peN-an 名詞。"
    },
    {
      id: "b-022",
      level: "B",
      word: "kepadatan",
      japanese: "密度、過密",
      english: "density; congestion",
      partOfSpeech: "名詞",
      category: "都市",
      example: "Kepadatan penduduk meningkat setiap tahun.",
      exampleJapanese: "人口密度は毎年上昇しています。",
      note: "padat から派生した ke-an 名詞。"
    },
    {
      id: "b-023",
      level: "B",
      word: "polusi",
      japanese: "汚染、公害",
      english: "pollution",
      partOfSpeech: "名詞",
      category: "環境",
      example: "Polusi udara berdampak pada kesehatan.",
      exampleJapanese: "大気汚染は健康に影響します。",
      note: "pencemaran と近いが外来語で会話にも出やすい。"
    },
    {
      id: "b-024",
      level: "B",
      word: "berkurang",
      japanese: "減る、少なくなる",
      english: "to decrease",
      partOfSpeech: "動詞",
      category: "状態",
      example: "Ruang terbuka hijau semakin berkurang.",
      exampleJapanese: "緑のオープンスペースはますます減っています。",
      note: "kurang に ber- が付いた変化表現。"
    },
    {
      id: "a-013",
      level: "A",
      word: "dipisahkan",
      japanese: "分離される、切り離される",
      english: "to be separated",
      partOfSpeech: "動詞",
      category: "抽象",
      example: "Pendidikan tidak dapat dipisahkan dari budaya.",
      exampleJapanese: "教育は文化から切り離すことができません。",
      note: "pisah の受動形。dari とよく使う。"
    },
    {
      id: "a-014",
      level: "A",
      word: "kultur",
      japanese: "文化",
      english: "culture",
      partOfSpeech: "名詞",
      category: "抽象",
      example: "Kultur lokal memengaruhi cara belajar.",
      exampleJapanese: "地域文化は学習方法に影響します。",
      note: "budaya と近いが、論説調で使われる。"
    },
    {
      id: "a-015",
      level: "A",
      word: "akselerasi",
      japanese: "加速、飛び級教育",
      english: "acceleration",
      partOfSpeech: "名詞",
      category: "教育",
      example: "Program kelas akselerasi menarik perhatian orang tua.",
      exampleJapanese: "飛び級クラスのプログラムは保護者の注目を集めました。",
      note: "教育文脈では進度の速いクラスを指すことがある。"
    },
    {
      id: "a-016",
      level: "A",
      word: "diperkenalkan",
      japanese: "紹介される、導入される",
      english: "to be introduced",
      partOfSpeech: "動詞",
      category: "抽象",
      example: "Kebijakan baru diperkenalkan tahun lalu.",
      exampleJapanese: "新しい政策は昨年導入されました。",
      note: "kenal の派生形 perkenalkan の受動形。"
    },
    {
      id: "a-017",
      level: "A",
      word: "menyambut",
      japanese: "迎える、歓迎する",
      english: "to welcome",
      partOfSpeech: "動詞",
      category: "態度",
      example: "Warga menyambut keputusan itu dengan baik.",
      exampleJapanese: "住民はその決定を好意的に歓迎しました。",
      note: "sambut に meN- が付いた形。"
    },
    {
      id: "a-018",
      level: "A",
      word: "berbobot",
      japanese: "重みのある、質の高い",
      english: "weighty; substantial",
      partOfSpeech: "形容詞",
      category: "抽象",
      example: "Artikel itu berisi analisis yang berbobot.",
      exampleJapanese: "その記事には重みのある分析が含まれています。",
      note: "bobot は重さ、価値、質を表す。"
    },
    {
      id: "a-019",
      level: "A",
      word: "bergairah",
      japanese: "活気がある、熱意がある",
      english: "enthusiastic; lively",
      partOfSpeech: "形容詞",
      category: "態度",
      example: "Peserta berdiskusi dengan bergairah.",
      exampleJapanese: "参加者は熱意をもって議論しました。",
      note: "antusias の類義語として出やすい。"
    },
    {
      id: "a-020",
      level: "A",
      word: "menggebu-gebu",
      japanese: "非常に熱心な、燃え立つような",
      english: "fervent; passionate",
      partOfSpeech: "形容詞",
      category: "態度",
      example: "Ia berbicara dengan semangat menggebu-gebu.",
      exampleJapanese: "彼は燃えるような熱意で話しました。",
      note: "強い熱意や感情を表す重複語。"
    },
    {
      id: "a-021",
      level: "A",
      word: "berlebihan",
      japanese: "過度の、過剰な",
      english: "excessive",
      partOfSpeech: "形容詞",
      category: "抽象",
      example: "Pemakaian alat itu secara berlebihan berbahaya.",
      exampleJapanese: "その器具の過度な使用は危険です。",
      note: "lebih から派生した表現。secara berlebihan で副詞的に使う。"
    },
    {
      id: "a-022",
      level: "A",
      word: "menyebabkan",
      japanese: "引き起こす、原因となる",
      english: "to cause",
      partOfSpeech: "動詞",
      category: "論理",
      example: "Hujan deras menyebabkan banjir.",
      exampleJapanese: "大雨が洪水を引き起こしました。",
      note: "sebab に meN-kan が付いた形。因果関係を表す重要語。"
    },
    {
      id: "a-023",
      level: "A",
      word: "tertib",
      japanese: "秩序正しい、整然とした",
      english: "orderly; disciplined",
      partOfSpeech: "形容詞",
      category: "行政",
      example: "Acara berlangsung dengan tertib.",
      exampleJapanese: "行事は整然と行われました。",
      note: "dengan tertib で「整然と」。"
    },
    {
      id: "a-024",
      level: "A",
      word: "minyak mentah",
      japanese: "原油",
      english: "crude oil",
      partOfSpeech: "名詞句",
      category: "経済",
      example: "Harga minyak mentah naik tajam.",
      exampleJapanese: "原油価格が急上昇しました。",
      note: "mentah は未加工、生の意味。"
    }
  ]
);

window.INDONESIAN_FLASHCARD_DATA.examTargets = [
  {
    level: "E",
    targetWords: 300,
    examQuestions: 35,
    neededCorrect: 21,
    passRate: "60%前後",
    focus: "挨拶、自己紹介、看板、短い手紙、基本文"
  },
  {
    level: "D",
    targetWords: 600,
    examQuestions: 45,
    neededCorrect: 27,
    passRate: "60%前後",
    focus: "買い物、道案内、伝言、案内板、チケット"
  },
  {
    level: "C",
    targetWords: 1000,
    examQuestions: 50,
    neededCorrect: 30,
    passRate: "60%前後",
    focus: "日常会話、広告、取扱説明、手紙、受動態"
  },
  {
    level: "B",
    targetWords: 1800,
    examQuestions: 50,
    neededCorrect: 35,
    passRate: "1次70%前後 / 2次75%前後",
    focus: "平易な新聞、業務文書、接辞、時事語、面接"
  },
  {
    level: "A",
    targetWords: 3000,
    examQuestions: 50,
    neededCorrect: 35,
    passRate: "1次70%前後 / 2次75%前後",
    focus: "新聞、文献、社会問題、翻訳、要約、意見表明"
  }
];
