(function () {
  const appData = window.INDONESIAN_FLASHCARD_DATA;
  if (!appData || !Array.isArray(appData.words)) {
    return;
  }

  const sentenceCase = (text) => text.charAt(0).toUpperCase() + text.slice(1);
  const startNumber = 25;
  const rows = [
    ["kita", "私たち", "we; us", "代名詞", "基本", "pronoun", null, null, "聞き手を含む「私たち」。"],
    ["kamu", "君、あなた", "you", "代名詞", "基本", "pronoun", null, null, "親しい相手に使う二人称。"],
    ["mereka", "彼ら、彼女たち", "they; them", "代名詞", "基本", "pronoun"],
    ["nama", "名前", "name", "名詞", "基本", "object", "Saya menulis nama saya.", "私は自分の名前を書きます。"],
    ["orang", "人", "person; people", "名詞", "基本", "person"],
    ["laki-laki", "男性、男の子", "male; man; boy", "名詞", "基本", "person"],
    ["perempuan", "女性、女の子", "female; woman; girl", "名詞", "基本", "person"],
    ["halo", "こんにちは", "hello", "表現", "あいさつ", "expression"],
    ["selamat pagi", "おはようございます", "good morning", "表現", "あいさつ", "expression"],
    ["selamat siang", "こんにちは", "good afternoon", "表現", "あいさつ", "expression"],
    ["selamat sore", "こんにちは、こんばんは", "good late afternoon", "表現", "あいさつ", "expression"],
    ["selamat malam", "こんばんは、おやすみなさい", "good evening; good night", "表現", "あいさつ", "expression"],
    ["sampai jumpa", "また会いましょう", "see you", "表現", "あいさつ", "expression"],
    ["terima kasih", "ありがとう", "thank you", "表現", "あいさつ", "expression"],
    ["maaf", "すみません、ごめんなさい", "sorry; excuse me", "表現", "あいさつ", "expression"],
    ["permisi", "失礼します", "excuse me", "表現", "あいさつ", "expression"],
    ["silakan", "どうぞ", "please; go ahead", "表現", "あいさつ", "expression"],
    ["tolong", "お願いします、助けて", "please; help", "表現", "会話", "expression"],
    ["ya", "はい", "yes", "副詞", "会話", "custom", "Ya, saya mengerti.", "はい、私はわかります。"],
    ["tidak", "いいえ、〜ない", "no; not", "副詞", "文法語", "custom", "Saya tidak tahu.", "私は知りません。"],
    ["bukan", "〜ではない", "not; is not", "副詞", "文法語", "custom", "Ini bukan buku saya.", "これは私の本ではありません。"],
    ["belum", "まだ〜ない", "not yet", "副詞", "文法語", "custom", "Saya belum makan.", "私はまだ食べていません。"],
    ["sudah", "もう、すでに", "already", "副詞", "文法語", "custom", "Saya sudah selesai.", "私はもう終わりました。"],
    ["juga", "〜も、また", "also; too", "副詞", "文法語", "custom", "Saya juga belajar bahasa Indonesia.", "私もインドネシア語を勉強します。"],
    ["di mana", "どこで、どこに", "where", "疑問詞", "文法語", "custom", "Di mana toilet?", "トイレはどこですか。"],
    ["ke mana", "どこへ", "to where", "疑問詞", "文法語", "custom", "Anda mau ke mana?", "あなたはどこへ行きたいですか。"],
    ["dari mana", "どこから", "from where", "疑問詞", "文法語", "custom", "Anda dari mana?", "あなたはどちらから来ましたか。"],
    ["mengapa", "なぜ", "why", "疑問詞", "文法語", "custom", "Mengapa Anda belajar bahasa Indonesia?", "なぜあなたはインドネシア語を勉強しますか。"],
    ["bagaimana", "どのように、どう", "how", "疑問詞", "文法語", "custom", "Bagaimana kabar Anda?", "お元気ですか。"],
    ["berapa", "いくつ、いくら", "how many; how much", "疑問詞", "文法語", "custom", "Berapa harga buku ini?", "この本はいくらですか。"],
    ["mana", "どれ、どちら", "which; where", "疑問詞", "文法語", "custom", "Mana tas Anda?", "あなたのかばんはどれですか。"],
    ["apakah", "〜ですか", "question marker", "疑問詞", "文法語", "custom", "Apakah Anda orang Jepang?", "あなたは日本人ですか。"],
    ["dan", "そして、〜と", "and", "接続詞", "文法語", "custom", "Saya makan roti dan telur.", "私はパンと卵を食べます。"],
    ["atau", "または", "or", "接続詞", "文法語", "custom", "Anda mau kopi atau teh?", "あなたはコーヒーか紅茶が欲しいですか。"],
    ["tetapi", "しかし", "but; however", "接続詞", "文法語", "custom", "Saya suka kopi, tetapi tidak suka susu.", "私はコーヒーが好きですが、牛乳は好きではありません。"],
    ["karena", "なぜなら、〜なので", "because", "接続詞", "文法語", "custom", "Saya tidur karena lelah.", "私は疲れたので寝ます。"],
    ["kalau", "もし〜なら", "if; when", "接続詞", "文法語", "custom", "Kalau hujan, saya di rumah.", "もし雨なら、私は家にいます。"],
    ["untuk", "〜のために、〜用の", "for; to", "前置詞", "文法語", "custom", "Ini hadiah untuk ibu.", "これは母へのプレゼントです。"],
    ["tentang", "〜について", "about", "前置詞", "文法語", "custom", "Kami berbicara tentang makanan.", "私たちは食べ物について話します。"],
    ["dalam", "〜の中に", "inside; in", "前置詞", "文法語", "custom", "Buku ada dalam tas.", "本はかばんの中にあります。"],
    ["luar", "外", "outside", "名詞", "場所", "custom", "Anak-anak bermain di luar.", "子どもたちは外で遊びます。"],
    ["atas", "上", "above; top", "名詞", "場所", "custom", "Buku ada di atas meja.", "本は机の上にあります。"],
    ["bawah", "下", "under; below", "名詞", "場所", "custom", "Sepatu ada di bawah kursi.", "靴は椅子の下にあります。"],
    ["depan", "前", "front", "名詞", "場所", "custom", "Mobil ada di depan rumah.", "車は家の前にあります。"],
    ["belakang", "後ろ", "back; behind", "名詞", "場所", "custom", "Taman ada di belakang sekolah.", "公園は学校の後ろにあります。"],
    ["samping", "横、隣", "side; beside", "名詞", "場所", "custom", "Bank ada di samping toko.", "銀行は店の隣にあります。"],
    ["sebelum", "〜の前に", "before", "前置詞", "文法語", "custom", "Saya mandi sebelum tidur.", "私は寝る前にシャワーを浴びます。"],
    ["sesudah", "〜の後で", "after", "前置詞", "文法語", "custom", "Saya belajar sesudah makan.", "私は食事の後で勉強します。"],
    ["sampai", "〜まで、到着する", "until; arrive", "前置詞", "文法語", "custom", "Saya bekerja sampai jam lima.", "私は5時まで働きます。"],
    ["hanya", "ただ〜だけ", "only", "副詞", "文法語", "custom", "Saya hanya minum air.", "私は水だけ飲みます。"],
    ["semua", "すべての、みんな", "all; everyone", "副詞", "文法語", "custom", "Semua orang datang.", "全員が来ます。"],
    ["banyak", "多い、たくさん", "many; much", "形容詞", "数量", "custom", "Saya punya banyak teman.", "私は友だちがたくさんいます。"],
    ["sedikit", "少ない、少し", "a little; few", "形容詞", "数量", "custom", "Saya minum sedikit kopi.", "私はコーヒーを少し飲みます。"],
    ["lagi", "また、さらに", "again; more", "副詞", "文法語", "custom", "Saya belajar lagi.", "私はまた勉強します。"],
    ["hari ini", "今日", "today", "名詞", "時間", "time"],
    ["besok", "明日", "tomorrow", "名詞", "時間", "time"],
    ["kemarin", "昨日", "yesterday", "名詞", "時間", "time"],
    ["nanti", "あとで、のちほど", "later", "副詞", "時間", "time"],
    ["sekarang", "今", "now", "副詞", "時間", "time"],
    ["pagi", "朝", "morning", "名詞", "時間", "time"],
    ["siang", "昼", "daytime; noon", "名詞", "時間", "time"],
    ["sore", "夕方", "late afternoon", "名詞", "時間", "time"],
    ["malam", "夜", "night; evening", "名詞", "時間", "time"],
    ["hari", "日", "day", "名詞", "時間", "custom", "Hari ini panas.", "今日は暑いです。"],
    ["minggu", "週、日曜日", "week; Sunday", "名詞", "時間", "custom", "Saya bekerja lima hari seminggu.", "私は週に5日働きます。"],
    ["bulan", "月", "month; moon", "名詞", "時間", "custom", "Bulan depan saya pergi ke Bali.", "来月、私はバリへ行きます。"],
    ["tahun", "年", "year", "名詞", "時間", "custom", "Tahun ini saya belajar bahasa Indonesia.", "今年、私はインドネシア語を勉強します。"],
    ["jam", "時、時計、時間", "hour; clock", "名詞", "時間", "custom", "Sekarang jam tujuh.", "今は7時です。"],
    ["pukul", "〜時", "o'clock", "名詞", "時間", "custom", "Saya bangun pukul enam.", "私は6時に起きます。"],
    ["tanggal", "日付", "date", "名詞", "時間", "custom", "Tanggal berapa hari ini?", "今日は何日ですか。"],
    ["Senin", "月曜日", "Monday", "名詞", "曜日", "day"],
    ["Selasa", "火曜日", "Tuesday", "名詞", "曜日", "day"],
    ["Rabu", "水曜日", "Wednesday", "名詞", "曜日", "day"],
    ["Kamis", "木曜日", "Thursday", "名詞", "曜日", "day"],
    ["Jumat", "金曜日", "Friday", "名詞", "曜日", "day"],
    ["Sabtu", "土曜日", "Saturday", "名詞", "曜日", "day"],
    ["hari Minggu", "日曜日", "Sunday", "名詞", "曜日", "custom", "Pada hari Minggu, saya beristirahat.", "日曜日に私は休みます。"],
    ["satu", "1", "one", "数詞", "数字", "number"],
    ["dua", "2", "two", "数詞", "数字", "number"],
    ["tiga", "3", "three", "数詞", "数字", "number"],
    ["empat", "4", "four", "数詞", "数字", "number"],
    ["lima", "5", "five", "数詞", "数字", "number"],
    ["enam", "6", "six", "数詞", "数字", "number"],
    ["tujuh", "7", "seven", "数詞", "数字", "number"],
    ["delapan", "8", "eight", "数詞", "数字", "number"],
    ["sembilan", "9", "nine", "数詞", "数字", "number"],
    ["sepuluh", "10", "ten", "数詞", "数字", "number"],
    ["sebelas", "11", "eleven", "数詞", "数字", "number"],
    ["dua belas", "12", "twelve", "数詞", "数字", "number"],
    ["seratus", "100", "one hundred", "数詞", "数字", "number"],
    ["keluarga", "家族", "family", "名詞", "人", "person"],
    ["ayah", "父", "father", "名詞", "家族", "person"],
    ["ibu", "母", "mother", "名詞", "家族", "person"],
    ["anak", "子ども", "child", "名詞", "家族", "person"],
    ["kakak", "兄、姉", "older sibling", "名詞", "家族", "person"],
    ["adik", "弟、妹", "younger sibling", "名詞", "家族", "person"],
    ["saudara", "兄弟姉妹、親族", "sibling; relative", "名詞", "家族", "person"],
    ["suami", "夫", "husband", "名詞", "家族", "person"],
    ["istri", "妻", "wife", "名詞", "家族", "person"],
    ["kakek", "祖父", "grandfather", "名詞", "家族", "person"],
    ["nenek", "祖母", "grandmother", "名詞", "家族", "person"],
    ["teman", "友だち", "friend", "名詞", "人", "person"],
    ["guru", "先生", "teacher", "名詞", "仕事", "person"],
    ["murid", "生徒", "student; pupil", "名詞", "仕事", "person"],
    ["mahasiswa", "大学生", "university student", "名詞", "仕事", "person"],
    ["dokter", "医者", "doctor", "名詞", "仕事", "person"],
    ["polisi", "警察官", "police officer", "名詞", "仕事", "person"],
    ["sopir", "運転手", "driver", "名詞", "仕事", "person"],
    ["pegawai", "職員", "employee; staff", "名詞", "仕事", "person"],
    ["petani", "農家、農民", "farmer", "名詞", "仕事", "person"],
    ["penjual", "売り手、販売員", "seller", "名詞", "仕事", "person"],
    ["tamu", "客", "guest", "名詞", "人", "person"],
    ["tetangga", "近所の人", "neighbor", "名詞", "人", "person"],
    ["bayi", "赤ちゃん", "baby", "名詞", "家族", "person"],
    ["paman", "おじ", "uncle", "名詞", "家族", "person"],
    ["bibi", "おば", "aunt", "名詞", "家族", "person"],
    ["sepupu", "いとこ", "cousin", "名詞", "家族", "person"],
    ["kepala sekolah", "校長", "principal", "名詞", "仕事", "person"],
    ["pelayan", "店員、給仕", "server; waiter", "名詞", "仕事", "person"],
    ["koki", "料理人", "cook; chef", "名詞", "仕事", "person"],
    ["kantor", "会社、事務所", "office", "名詞", "場所", "place"],
    ["toko", "店", "shop; store", "名詞", "場所", "place"],
    ["pasar", "市場", "market", "名詞", "場所", "place"],
    ["restoran", "レストラン", "restaurant", "名詞", "場所", "place"],
    ["hotel", "ホテル", "hotel", "名詞", "場所", "place"],
    ["bank", "銀行", "bank", "名詞", "場所", "place"],
    ["rumah sakit", "病院", "hospital", "名詞", "場所", "place"],
    ["stasiun", "駅", "station", "名詞", "場所", "place"],
    ["bandara", "空港", "airport", "名詞", "場所", "place"],
    ["terminal", "バスターミナル", "terminal", "名詞", "場所", "place"],
    ["jalan", "道、通り", "road; street", "名詞", "場所", "place"],
    ["kota", "町、都市", "city; town", "名詞", "場所", "place"],
    ["desa", "村", "village", "名詞", "場所", "place"],
    ["kamar", "部屋", "room", "名詞", "場所", "place"],
    ["kelas", "教室、授業", "class; classroom", "名詞", "場所", "place"],
    ["toilet", "トイレ", "toilet", "名詞", "場所", "place"],
    ["dapur", "台所", "kitchen", "名詞", "場所", "place"],
    ["halaman", "庭、ページ", "yard; page", "名詞", "場所", "place"],
    ["taman", "公園、庭", "park; garden", "名詞", "場所", "place"],
    ["perpustakaan", "図書館", "library", "名詞", "場所", "place"],
    ["masjid", "モスク", "mosque", "名詞", "場所", "place"],
    ["gereja", "教会", "church", "名詞", "場所", "place"],
    ["pantai", "海岸", "beach", "名詞", "場所", "place"],
    ["gunung", "山", "mountain", "名詞", "場所", "place"],
    ["laut", "海", "sea", "名詞", "場所", "place"],
    ["sungai", "川", "river", "名詞", "場所", "place"],
    ["jembatan", "橋", "bridge", "名詞", "場所", "place"],
    ["halte", "停留所", "bus stop", "名詞", "交通", "place"],
    ["parkir", "駐車、駐車場", "parking", "名詞", "交通", "place"],
    ["mobil", "車", "car", "名詞", "交通", "transport"],
    ["motor", "バイク", "motorcycle", "名詞", "交通", "transport"],
    ["bus", "バス", "bus", "名詞", "交通", "transport"],
    ["kereta", "電車、列車", "train", "名詞", "交通", "transport"],
    ["taksi", "タクシー", "taxi", "名詞", "交通", "transport"],
    ["pesawat", "飛行機", "airplane", "名詞", "交通", "transport"],
    ["nasi", "ご飯、米飯", "cooked rice", "名詞", "食べ物", "food"],
    ["roti", "パン", "bread", "名詞", "食べ物", "food"],
    ["mie", "麺", "noodles", "名詞", "食べ物", "food"],
    ["ayam", "鶏肉、鶏", "chicken", "名詞", "食べ物", "food"],
    ["ikan", "魚", "fish", "名詞", "食べ物", "food"],
    ["telur", "卵", "egg", "名詞", "食べ物", "food"],
    ["daging", "肉", "meat", "名詞", "食べ物", "food"],
    ["sayur", "野菜", "vegetable", "名詞", "食べ物", "food"],
    ["buah", "果物", "fruit", "名詞", "食べ物", "food"],
    ["apel", "りんご", "apple", "名詞", "食べ物", "food"],
    ["pisang", "バナナ", "banana", "名詞", "食べ物", "food"],
    ["jeruk", "オレンジ、みかん", "orange", "名詞", "食べ物", "food"],
    ["mangga", "マンゴー", "mango", "名詞", "食べ物", "food"],
    ["semangka", "すいか", "watermelon", "名詞", "食べ物", "food"],
    ["kue", "お菓子、ケーキ", "cake; snack", "名詞", "食べ物", "food"],
    ["gula", "砂糖", "sugar", "名詞", "食べ物", "food"],
    ["garam", "塩", "salt", "名詞", "食べ物", "food"],
    ["sambal", "サンバル", "chili sauce", "名詞", "食べ物", "food"],
    ["sup", "スープ", "soup", "名詞", "食べ物", "food"],
    ["sate", "サテ、串焼き", "satay", "名詞", "食べ物", "food"],
    ["bakso", "肉団子スープ", "meatball soup", "名詞", "食べ物", "food"],
    ["air", "水", "water", "名詞", "飲み物", "drink"],
    ["kopi", "コーヒー", "coffee", "名詞", "飲み物", "drink"],
    ["teh", "お茶、紅茶", "tea", "名詞", "飲み物", "drink"],
    ["susu", "牛乳", "milk", "名詞", "飲み物", "drink"],
    ["jus", "ジュース", "juice", "名詞", "飲み物", "drink"],
    ["es", "氷、冷たい飲み物", "ice", "名詞", "飲み物", "drink"],
    ["sarapan", "朝食", "breakfast", "名詞", "食事", "custom", "Saya sarapan pukul tujuh.", "私は7時に朝食を食べます。"],
    ["makan siang", "昼食", "lunch", "名詞", "食事", "custom", "Saya makan siang di kantor.", "私は会社で昼食を食べます。"],
    ["makan malam", "夕食", "dinner", "名詞", "食事", "custom", "Kami makan malam di rumah.", "私たちは家で夕食を食べます。"],
    ["lapar", "お腹がすいた", "hungry", "形容詞", "状態", "custom", "Saya lapar sekarang.", "私は今お腹がすいています。"],
    ["haus", "のどが渇いた", "thirsty", "形容詞", "状態", "custom", "Saya haus setelah berjalan.", "私は歩いたあと、のどが渇いています。"],
    ["kenyang", "満腹の", "full", "形容詞", "状態", "custom", "Saya sudah kenyang.", "私はもう満腹です。"],
    ["pedas", "辛い", "spicy", "形容詞", "味", "adjective"],
    ["manis", "甘い", "sweet", "形容詞", "味", "adjective"],
    ["buku", "本", "book", "名詞", "物", "object"],
    ["pena", "ペン", "pen", "名詞", "物", "object"],
    ["kertas", "紙", "paper", "名詞", "物", "object"],
    ["tas", "かばん", "bag", "名詞", "物", "object"],
    ["sepatu", "靴", "shoes", "名詞", "服", "object"],
    ["baju", "服、シャツ", "clothes; shirt", "名詞", "服", "object"],
    ["celana", "ズボン", "pants", "名詞", "服", "object"],
    ["topi", "帽子", "hat", "名詞", "服", "object"],
    ["jam tangan", "腕時計", "watch", "名詞", "物", "object"],
    ["telepon", "電話", "telephone", "名詞", "物", "object"],
    ["komputer", "コンピューター", "computer", "名詞", "物", "object"],
    ["kunci", "鍵", "key", "名詞", "物", "object"],
    ["uang", "お金", "money", "名詞", "物", "object"],
    ["tiket", "チケット", "ticket", "名詞", "交通", "object"],
    ["paspor", "パスポート", "passport", "名詞", "旅行", "object"],
    ["peta", "地図", "map", "名詞", "旅行", "object"],
    ["meja", "机、テーブル", "table; desk", "名詞", "家・道具", "object"],
    ["kursi", "椅子", "chair", "名詞", "家・道具", "object"],
    ["pintu", "ドア", "door", "名詞", "家・道具", "object"],
    ["jendela", "窓", "window", "名詞", "家・道具", "object"],
    ["tempat tidur", "ベッド", "bed", "名詞", "家・道具", "object"],
    ["lampu", "電灯、ランプ", "lamp; light", "名詞", "家・道具", "object"],
    ["kepala", "頭", "head", "名詞", "体", "body"],
    ["mata", "目", "eye", "名詞", "体", "body"],
    ["telinga", "耳", "ear", "名詞", "体", "body"],
    ["hidung", "鼻", "nose", "名詞", "体", "body"],
    ["mulut", "口", "mouth", "名詞", "体", "body"],
    ["tangan", "手", "hand", "名詞", "体", "body"],
    ["kaki", "足、脚", "foot; leg", "名詞", "体", "body"],
    ["rambut", "髪", "hair", "名詞", "体", "body"],
    ["gigi", "歯", "tooth; teeth", "名詞", "体", "body"],
    ["perut", "お腹", "stomach", "名詞", "体", "body"],
    ["obat", "薬", "medicine", "名詞", "日常", "object"],
    ["sabun", "石けん", "soap", "名詞", "日常", "object"],
    ["handuk", "タオル", "towel", "名詞", "日常", "object"],
    ["enak", "おいしい、快適な", "delicious; pleasant", "形容詞", "形容", "adjective"],
    ["panas", "暑い、熱い", "hot", "形容詞", "形容", "adjective"],
    ["dingin", "寒い、冷たい", "cold", "形容詞", "形容", "adjective"],
    ["mahal", "高い", "expensive", "形容詞", "形容", "adjective"],
    ["murah", "安い", "cheap", "形容詞", "形容", "adjective"],
    ["mudah", "簡単な", "easy", "形容詞", "形容", "adjective"],
    ["sulit", "難しい", "difficult", "形容詞", "形容", "adjective"],
    ["bagus", "良い、すてきな", "good; nice", "形容詞", "形容", "adjective"],
    ["bersih", "清潔な、きれいな", "clean", "形容詞", "形容", "adjective"],
    ["kotor", "汚い", "dirty", "形容詞", "形容", "adjective"],
    ["sakit", "病気の、痛い", "sick; painful", "形容詞", "状態", "adjective"],
    ["sehat", "健康な", "healthy", "形容詞", "状態", "adjective"],
    ["senang", "うれしい、楽しい", "happy; pleased", "形容詞", "感情", "adjective"],
    ["sedih", "悲しい", "sad", "形容詞", "感情", "adjective"],
    ["ramai", "にぎやかな、混んだ", "crowded; lively", "形容詞", "形容", "adjective"],
    ["sepi", "静かな、人けが少ない", "quiet; empty", "形容詞", "形容", "adjective"],
    ["panjang", "長い", "long", "形容詞", "形容", "adjective"],
    ["pendek", "短い、背が低い", "short", "形容詞", "形容", "adjective"],
    ["tinggi", "高い、背が高い", "high; tall", "形容詞", "形容", "adjective"],
    ["rendah", "低い", "low", "形容詞", "形容", "adjective"],
    ["tua", "古い、年をとった", "old", "形容詞", "形容", "adjective"],
    ["muda", "若い", "young", "形容詞", "形容", "adjective"],
    ["benar", "正しい、本当の", "correct; true", "形容詞", "形容", "adjective"],
    ["salah", "間違った", "wrong", "形容詞", "形容", "adjective"],
    ["merah", "赤", "red", "形容詞", "色", "color"],
    ["putih", "白", "white", "形容詞", "色", "color"],
    ["hitam", "黒", "black", "形容詞", "色", "color"],
    ["biru", "青", "blue", "形容詞", "色", "color"],
    ["hijau", "緑", "green", "形容詞", "色", "color"],
    ["kuning", "黄色", "yellow", "形容詞", "色", "color"],
    ["pergi", "行く", "to go", "動詞", "日常", "custom", "Saya pergi ke sekolah.", "私は学校へ行きます。"],
    ["datang", "来る", "to come", "動詞", "日常", "custom", "Dia datang pagi ini.", "彼は今朝来ます。"],
    ["pulang", "帰る", "to go home", "動詞", "日常", "custom", "Saya pulang jam lima.", "私は5時に帰ります。"],
    ["tinggal", "住む", "to live; stay", "動詞", "日常", "custom", "Saya tinggal di Jakarta.", "私はジャカルタに住んでいます。"],
    ["belajar", "勉強する", "to study", "動詞", "日常", "custom", "Saya belajar bahasa Indonesia.", "私はインドネシア語を勉強します。"],
    ["bekerja", "働く", "to work", "動詞", "日常", "custom", "Ayah bekerja di kantor.", "父は会社で働きます。"],
    ["tidur", "寝る", "to sleep", "動詞", "日常", "custom", "Saya tidur pukul sepuluh.", "私は10時に寝ます。"],
    ["bangun", "起きる", "to wake up", "動詞", "日常", "custom", "Saya bangun pagi.", "私は朝起きます。"],
    ["mandi", "水浴びする、シャワーを浴びる", "to bathe; shower", "動詞", "日常", "custom", "Saya mandi sebelum sarapan.", "私は朝食の前にシャワーを浴びます。"],
    ["memasak", "料理する", "to cook", "動詞", "日常", "custom", "Ibu memasak nasi.", "母はご飯を料理します。"],
    ["membaca", "読む", "to read", "動詞", "日常", "custom", "Saya membaca buku.", "私は本を読みます。"],
    ["menulis", "書く", "to write", "動詞", "日常", "custom", "Saya menulis surat.", "私は手紙を書きます。"],
    ["melihat", "見る", "to see; look", "動詞", "日常", "custom", "Kami melihat gunung.", "私たちは山を見ます。"],
    ["mendengar", "聞く", "to hear", "動詞", "日常", "custom", "Saya mendengar suara musik.", "私は音楽の音を聞きます。"],
    ["menunggu", "待つ", "to wait", "動詞", "日常", "custom", "Saya menunggu bus.", "私はバスを待ちます。"],
    ["duduk", "座る", "to sit", "動詞", "日常", "custom", "Silakan duduk di sini.", "ここに座ってください。"],
    ["berdiri", "立つ", "to stand", "動詞", "日常", "custom", "Murid berdiri di depan kelas.", "生徒は教室の前に立っています。"],
    ["masuk", "入る", "to enter", "動詞", "日常", "custom", "Saya masuk kamar.", "私は部屋に入ります。"],
    ["keluar", "出る", "to go out; exit", "動詞", "日常", "custom", "Dia keluar dari rumah.", "彼は家から出ます。"],
    ["suka", "好きである", "to like", "動詞", "感情", "custom", "Saya suka makanan pedas.", "私は辛い食べ物が好きです。"],
    ["mau", "欲しい、〜したい", "to want; will", "動詞", "会話", "custom", "Saya mau minum teh.", "私はお茶を飲みたいです。"]
  ];

  const notesByKind = {
    adjective: "形容詞は名詞の後ろに置くことが多い。",
    body: "体の部位を表す基本語。",
    color: "warna と一緒に使うと「〜色」。",
    day: "曜日名は文の中でも大文字で書くことが多い。",
    drink: "minum と一緒に使う飲み物の語彙。",
    expression: "短い会話でそのまま使える表現。",
    food: "makan と一緒に使う食べ物の語彙。",
    number: "数を表す基本語。値段や時間でも使う。",
    object: "身の回りの物を表す基本語。",
    person: "人や家族、職業を表す基本語。",
    place: "ke や di と一緒に使いやすい場所の語彙。",
    pronoun: "人を指す基本語。",
    time: "時を表す語。文頭や文末に置ける。",
    transport: "naik と一緒に使う乗り物の語彙。"
  };

  function buildExample(word, japanese, kind, example, exampleJapanese) {
    if (example && exampleJapanese) {
      return { example, exampleJapanese };
    }

    const examples = {
      adjective: [`Kamar ini ${word}.`, `この部屋は${japanese}です。`],
      body: [`${sentenceCase(word)} saya sakit.`, `私の${japanese}が痛いです。`],
      color: [`Saya suka warna ${word}.`, `私は${japanese}色が好きです。`],
      day: [`Pada hari ${word}, saya bekerja.`, `${japanese}に私は働きます。`],
      drink: [`Saya minum ${word}.`, `私は${japanese}を飲みます。`],
      expression: [`${sentenceCase(word)}.`, `${japanese}。`],
      food: [`Saya makan ${word}.`, `私は${japanese}を食べます。`],
      number: [`Saya punya ${word} buku.`, `私は本を${japanese}冊持っています。`],
      object: [`Saya punya ${word}.`, `私は${japanese}を持っています。`],
      person: [`${sentenceCase(word)} itu baik.`, `その${japanese}は親切です。`],
      place: [`Saya pergi ke ${word}.`, `私は${japanese}へ行きます。`],
      pronoun: [`${sentenceCase(word)} belajar bahasa Indonesia.`, `${japanese}はインドネシア語を勉強します。`],
      time: [`${sentenceCase(word)}, saya belajar.`, `${japanese}、私は勉強します。`],
      transport: [`Saya naik ${word}.`, `私は${japanese}に乗ります。`]
    };

    const fallback = [`Saya belajar kata ${word}.`, `私は${japanese}という単語を勉強します。`];
    const selected = examples[kind] || fallback;
    return {
      example: selected[0],
      exampleJapanese: selected[1]
    };
  }

  rows.forEach((row, index) => {
    const [word, japanese, english, partOfSpeech, category, kind, example, exampleJapanese, note] = row;
    const built = buildExample(word, japanese, kind, example, exampleJapanese);

    appData.words.push({
      id: `e-${String(startNumber + index).padStart(3, "0")}`,
      level: "E",
      word,
      japanese,
      english,
      partOfSpeech,
      category,
      example: built.example,
      exampleJapanese: built.exampleJapanese,
      note: note || notesByKind[kind] || "E級の基本語彙。短い文で使いやすい。"
    });
  });
})();
